# Generated by Django 3.0 on 2020-01-15 11:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_auto_20200115_1903'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('documents', models.ManyToManyField(related_name='messages', to='documents.Document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='accounts.Account')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communications.Message')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='accounts.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_accounts',
            field=models.ManyToManyField(related_name='received_messages', through='communications.Recipient', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='accounts.Account'),
        ),
    ]
