# Generated by Django 3.0.2 on 2020-01-23 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200123_1922'),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='accounts.Account'),
        ),
    ]
