# Generated by Django 3.1.2 on 2021-07-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relationships', '0091_auto_20210717_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('requested', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('responded', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('response_code', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('user_id', models.CharField(db_index=True, max_length=200)),
                ('device_id', models.CharField(db_index=True, max_length=200)),
                ('event_type', models.CharField(db_index=True, max_length=200)),
                ('time_dt', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('time', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('app_version', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('platform', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('os_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('os_version', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('device_brand', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('device_manufacturer', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('device_model', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('carrier', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('dma', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('language', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('price', models.FloatField(blank=True, db_index=True, null=True)),
                ('quantity', models.IntegerField(blank=True, db_index=True, null=True)),
                ('revenue', models.FloatField(blank=True, db_index=True, null=True)),
                ('product_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('revenue_type', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('location_lat', models.FloatField(blank=True, db_index=True, null=True)),
                ('location_lng', models.FloatField(blank=True, db_index=True, null=True)),
                ('ip', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('idfa', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('idfv', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('adid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('android_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('event_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('session_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('insert_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('key', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('value', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_properties', related_query_name='user_properties', to='amplitude.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('started', models.DateTimeField(db_index=True)),
                ('session_id', models.CharField(db_index=True, max_length=200)),
                ('last_activity', models.DateTimeField(db_index=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', related_query_name='sessions', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('key', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('value', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_properties', related_query_name='event_properties', to='amplitude.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
