# Generated by Django 3.1.2 on 2021-07-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplitude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
