# Generated by Django 3.1.2 on 2021-11-26 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relationships', '0001_initial'),
        ('amplitude', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproperty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_properties', related_query_name='user_properties', to='relationships.user'),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', related_query_name='sessions', to='relationships.user'),
        ),
        migrations.AddField(
            model_name='eventproperty',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_properties', related_query_name='event_properties', to='amplitude.event'),
        ),
    ]
