# Generated by Django 3.1.2 on 2021-07-28 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0091_auto_20210717_2219'),
        ('amplitude', '0002_auto_20210728_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproperty',
            name='event',
        ),
        migrations.AddField(
            model_name='userproperty',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='user_properties', related_query_name='user_properties', to='relationships.user'),
            preserve_default=False,
        ),
    ]
