# Generated by Django 3.1.2 on 2021-07-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplitude', '0003_auto_20210728_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventproperty',
            options={'verbose_name': 'Event property', 'verbose_name_plural': 'Event properties'},
        ),
        migrations.AlterModelOptions(
            name='userproperty',
            options={'verbose_name': 'User property', 'verbose_name_plural': 'User properties'},
        ),
        migrations.AlterField(
            model_name='event',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
