# Generated by Django 3.1.2 on 2021-07-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplitude', '0004_auto_20210729_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
