# Generated by Django 3.1.2 on 2021-11-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amplitude', '0005_event_response_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='session',
            name='started',
        ),
    ]
