# Generated by Django 3.1.2 on 2022-03-02 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relationships', '0044_auto_20220228_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StripeCallbackSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('amount_total', models.IntegerField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('customer', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('customer_details_email', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('mode', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('payment_intent', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('no_payment_required', 'No Payment Required')], db_index=True, max_length=20, null=True)),
                ('success_url', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('cancel_url', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StripeCheckoutSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('mode', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('success_url', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('cancel_url', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StripePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('api_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, db_index=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stripe_prices', related_query_name='stripe_prices', to='payments.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('api_id', models.CharField(db_index=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stripe_customers', related_query_name='stripe_customers', to='relationships.user')),
            ],
            options={
                'unique_together': {('user', 'api_id')},
            },
        ),
        migrations.CreateModel(
            name='StripeCheckoutSessionLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('quantity', models.IntegerField(db_index=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', related_query_name='line_items', to='payments.stripeprice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', related_query_name='line_items', to='payments.stripecheckoutsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stripecheckoutsession',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', related_query_name='checkout_sessions', to='payments.stripecustomer'),
        ),
        migrations.CreateModel(
            name='CreditsEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('value', models.IntegerField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('top-up', 'Top-Up'), ('use', 'Use'), ('admin', 'Admin')], db_index=True, max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits_events', related_query_name='credits_events', to='payments.stripecallbacksession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits_events', related_query_name='credits_events', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
