# Generated by Django 3.1.2 on 2022-04-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20220315_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currencies', 'verbose_name_plural': 'Currencies'},
        ),
    ]
