# Generated by Django 3.1.2 on 2022-09-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20220411_1726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditsEvent',
        ),
    ]
