# Generated by Django 3.1.2 on 2021-05-11 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20210511_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_links', related_query_name='payment_links', to='payments.currency'),
        ),
    ]
