# Generated by Django 3.1.2 on 2022-09-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_delete_creditsevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripecallbacksession',
            old_name='session_id',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='stripeprice',
            old_name='api_id',
            new_name='price_id',
        ),
        migrations.RemoveField(
            model_name='stripeprice',
            name='description',
        ),
    ]
