# Generated by Django 3.1.2 on 2021-05-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20210511_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentevent',
            old_name='session',
            new_name='payment_link',
        ),
    ]
