# Generated by Django 3.1.2 on 2022-09-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20220915_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='api_id',
        ),
    ]
