# Generated by Django 3.1.2 on 2022-09-15 09:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_stripecustomer_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='customer_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=200, unique=True),
        ),
    ]
