# Generated by Django 3.1.2 on 2021-05-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20210511_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentevent',
            name='match',
        ),
        migrations.RemoveField(
            model_name='paymentlink',
            name='match',
        ),
    ]
