# Generated by Django 3.1.2 on 2022-09-15 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_stripecustomer_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNotificationCreditsBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('price_id', models.CharField(db_index=True, max_length=200)),
                ('credits', models.IntegerField(db_index=True)),
                ('expiry_days', models.IntegerField(db_index=True)),
                ('plan_bonus_credits', models.IntegerField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactUserCreditsBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('price_id', models.CharField(db_index=True, max_length=200)),
                ('credits', models.IntegerField(db_index=True)),
                ('expiry_days', models.IntegerField(db_index=True)),
                ('plan_bonus_credits', models.IntegerField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('price_id', models.CharField(db_index=True, max_length=200)),
                ('contact_user_credits_per_day', models.IntegerField(db_index=True)),
                ('alert_notifications_per_month', models.IntegerField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='stripecheckoutsession',
            name='cancel_url',
        ),
        migrations.RemoveField(
            model_name='stripecheckoutsession',
            name='success_url',
        ),
        migrations.AddField(
            model_name='stripecheckoutsession',
            name='alert_notification_credits_bundle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='stripe_checkout_sessions', related_query_name='stripe_checkout_sessions', to='payments.alertnotificationcreditsbundle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripecheckoutsession',
            name='contact_user_credits_bundle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='stripe_checkout_sessions', related_query_name='stripe_checkout_sessions', to='payments.contactusercreditsbundle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripecheckoutsession',
            name='subscription_plan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='stripe_checkout_sessions', related_query_name='stripe_checkout_sessions', to='payments.subscriptionplan'),
            preserve_default=False,
        ),
    ]
