# Generated by Django 3.1.2 on 2022-09-15 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0085_alertexcludecountry_alertkeyphrase_keyphrase'),
        ('payments', '0009_auto_20220915_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('started', models.DateTimeField(db_index=True)),
                ('renewed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('contact_user_credits_refreshed', models.DateTimeField(db_index=True)),
                ('contact_user_credits_left', models.IntegerField(db_index=True)),
                ('alert_notification_credits_refreshed', models.DateTimeField(db_index=True)),
                ('expiry_days', models.IntegerField(db_index=True)),
                ('last_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plans_as_last_plan', related_query_name='subscription_plans_as_last_plan', to='payments.subscriptionplan')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plans', related_query_name='subscription_plans', to='payments.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscription_plans', related_query_name='user_subscription_plans', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserContactUserCreditsBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('started', models.DateTimeField(db_index=True)),
                ('expire', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('credits_added', models.IntegerField(db_index=True)),
                ('credits_left', models.IntegerField(db_index=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_contact_user_credits_bundles', related_query_name='user_contact_user_credits_bundles', to='payments.contactusercreditsbundle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_contact_user_credits_bundles', related_query_name='user_contact_user_credits_bundles', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAlertNotificationCreditsBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('started', models.DateTimeField(db_index=True)),
                ('expire', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('credits_added', models.IntegerField(db_index=True)),
                ('credits_left', models.IntegerField(db_index=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_notification_credits_bundles', related_query_name='alert_notification_credits_bundles', to='payments.alertnotificationcreditsbundle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_notification_credits_bundles', related_query_name='alert_notification_credits_bundles', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
