# Generated by Django 3.1.2 on 2022-09-16 12:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_useralertnotificationcreditsbundle_usercontactusercreditsbundle_usersubscriptionplan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StripeCallbackSession',
            new_name='StripeEvent',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='alert_notifications_per_month',
            new_name='alert_notification_credits_per_month',
        ),
        migrations.RenameField(
            model_name='usersubscriptionplan',
            old_name='expiry_days',
            new_name='alert_notification_credits',
        ),
        migrations.RenameField(
            model_name='usersubscriptionplan',
            old_name='contact_user_credits_left',
            new_name='contact_user_credits',
        ),
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='expire',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripeprice',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripeprice',
            name='price_id',
            field=models.CharField(db_index=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripeprice',
            name='value',
            field=models.FloatField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersubscriptionplan',
            name='last_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plans_as_last_plan', related_query_name='subscription_plans_as_last_plan', to='payments.subscriptionplan'),
        ),
    ]
