# Generated by Django 3.1.2 on 2021-06-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20210617_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentevent',
            old_name='payment_link',
            new_name='payment_hash',
        ),
    ]
