# Generated by Django 3.1.2 on 2021-06-17 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_auto_20210617_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLinkAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('accessed', models.DateTimeField(auto_now=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('is_mobile', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_tablet', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_touch_capable', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_pc', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_bot', models.BooleanField(blank=True, db_index=True, null=True)),
                ('browser', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('browser_family', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('browser_version', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('browser_version_string', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('os', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('os_family', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('os_version', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('os_version_string', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('device', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('device_family', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('hash', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesses', related_query_name='accesses', to='payments.paymenthash')),
            ],
            options={
                'verbose_name': 'Phone hash access',
                'verbose_name_plural': 'Phone hash accesses',
            },
        ),
    ]
