# Generated by Django 3.1.2 on 2021-06-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_paymentlinkaccess_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlinkaccess',
            name='outcome',
            field=models.CharField(blank=True, choices=[('PAYMENT_LINK_ACCESS_SUCCESSFUL', 'PAYMENT_LINK_ACCESS_SUCCESSFUL'), ('PAYMENT_LINK_ACCESS_FAILED', 'PAYMENT_LINK_ACCESS_FAILED')], db_index=True, max_length=200, null=True),
        ),
    ]
