# Generated by Django 3.1.2 on 2021-07-15 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_auto_20210715_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthash',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_hashes', related_query_name='payment_hashes', to='payments.price'),
        ),
    ]
