# Generated by Django 3.1.2 on 2021-07-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_paymenthash_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCallbackCheckoutSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('amount_total', models.IntegerField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('customer', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('customer_details_email', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('mode', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('payment_intent', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('payment_status', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('success_url', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('cancel_url', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
