# Generated by Django 3.1.2 on 2021-07-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_stripecallbackcheckoutsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecallbackcheckoutsession',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'paid'), ('unpaid', 'unpaid'), ('no_payment_required', 'no_payment_required')], db_index=True, max_length=200, null=True),
        ),
    ]
