# Generated by Django 3.1.2 on 2021-07-30 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_price_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prices', related_query_name='prices', to='payments.currency'),
        ),
        migrations.AddField(
            model_name='price',
            name='value',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
