# Generated by Django 3.1.2 on 2021-10-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0025_auto_20210730_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentevent',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='paymentevent',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='paymentevent',
            name='payment_hash',
        ),
        migrations.RemoveField(
            model_name='paymentevent',
            name='user',
        ),
        # migrations.AlterUniqueTogether(
        #     name='paymenthash',
        #     unique_together=None,
        # ),
        migrations.RemoveField(
            model_name='paymenthash',
            name='price',
        ),
        migrations.RemoveField(
            model_name='paymenthash',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentlinkaccess',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='price',
            name='currency',
        ),
        migrations.DeleteModel(
            name='StripeCallbackCheckoutSession',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='PaymentEvent',
        ),
        migrations.DeleteModel(
            name='PaymentEventType',
        ),
        migrations.DeleteModel(
            name='PaymentHash',
        ),
        migrations.DeleteModel(
            name='PaymentLinkAccess',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
