# Generated by Django 3.1.2 on 2021-10-29 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0144_match'),
        ('payments', '0026_auto_20211016_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthash',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payment_links', related_query_name='payment_links', to='relationships.match'),
            preserve_default=False,
        ),
    ]
