# Generated by Django 3.1.2 on 2020-10-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_auto_20201022_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='types',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='phone_numbers', related_query_name='phone_numbers', to='relationships.PhoneNumber'),
        ),
    ]
