# Generated by Django 3.1.2 on 2020-12-10 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0021_blacklistentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistentry',
            options={'verbose_name': 'Blacklist entry', 'verbose_name_plural': 'Blacklist entries'},
        ),
        migrations.AddField(
            model_name='blacklistentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='black_list_entries', related_query_name='black_list_entries', to='relationships.company'),
        ),
        migrations.AddField(
            model_name='blacklistentry',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='black_list_entries', related_query_name='black_list_entries', to='relationships.email'),
        ),
        migrations.AddField(
            model_name='blacklistentry',
            name='phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='black_list_entries', related_query_name='black_list_entries', to='relationships.phonenumber'),
        ),
    ]
