# Generated by Django 3.1.2 on 2020-12-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0022_auto_20201210_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistentry',
            name='invalidated',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
