# Generated by Django 3.1.2 on 2020-12-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0024_auto_20201210_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name_wo_postfix',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True, verbose_name='Company name without postfix'),
        ),
    ]
