# Generated by Django 3.1.2 on 2020-12-15 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0033_auto_20201215_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWeChatIDType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('details_md', models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown')),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details_md', models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown')),
            ],
            options={
                'verbose_name': 'Company-WeChatID type',
                'verbose_name_plural': 'Company-WeChatID types',
            },
        ),
        migrations.CreateModel(
            name='PersonWeChatIDType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('details_md', models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown')),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details_md', models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown')),
            ],
            options={
                'verbose_name': 'Person-WeChatID type',
                'verbose_name_plural': 'Person-WeChatID types',
            },
        ),
        migrations.CreateModel(
            name='WeChatIDType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('details_md', models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown')),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details_md', models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown')),
            ],
            options={
                'verbose_name': 'WeChat ID type',
                'verbose_name_plural': 'WeChat ID types',
            },
        ),
        migrations.CreateModel(
            name='WeChatID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('wechat_id', models.CharField(db_index=True, max_length=300, unique=True)),
                ('types', models.ManyToManyField(blank=True, db_index=True, related_name='wechat_ids', related_query_name='wechat_ids', to='relationships.WeChatIDType')),
            ],
            options={
                'verbose_name': 'WeChat ID',
                'verbose_name_plural': 'WeChat IDs',
            },
        ),
        migrations.CreateModel(
            name='PersonWeChatID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('details_md', models.TextField(blank=True, null=True, verbose_name='Details in Markdown')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_wechatid_relationships', related_query_name='person_wechatid_relationships', to='relationships.person')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_wechatid_relationships', related_query_name='person_wechatid_relationships', to='relationships.personwechatidtype', verbose_name='Person-WeChatID relationship type')),
                ('wechat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_wechatid_relationships', related_query_name='person_wechatid_relationships', to='relationships.wechatid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyWeChatID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('details_md', models.TextField(blank=True, null=True, verbose_name='Details in Markdown')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_wechatid_relationships', related_query_name='company_wechatid_relationships', to='relationships.company')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_wechatid_relationships', related_query_name='company_wechatid_relationships', to='relationships.companywechatidtype', verbose_name='Company-WeChatID relationship type')),
                ('wechat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_wechatid_relationships', related_query_name='company_wechatid_relationships', to='relationships.wechatid')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
