# Generated by Django 3.1.2 on 2021-01-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0047_auto_20210106_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='language',
        ),
    ]
