# Generated by Django 3.1.2 on 2021-11-26 06:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relationships', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('lead_type', models.CharField(choices=[('buying', 'Buying'), ('selling', 'Selling')], db_index=True, max_length=20)),
                ('author_type', models.CharField(blank=True, choices=[('direct', 'Direct'), ('broker', 'Broker')], max_length=20, null=True)),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('commission_pct', models.FloatField(blank=True, db_index=True, null=True)),
                ('commission_payable_by', models.CharField(blank=True, choices=[('me', 'Me'), ('buyer', 'Buyer'), ('seller', 'Seller')], max_length=20, null=True)),
                ('commission_payable_after', models.CharField(blank=True, choices=[('initial_deposit_received', 'Initial deposit received'), ('goods_shipped', 'Goods shipped'), ('buyer_received_goods_services', 'Buyer received goods/services'), ('full_payment_received', 'Full payment received'), ('others', 'others')], max_length=50, null=True)),
                ('commission_payable_after_others', models.TextField(blank=True, null=True)),
                ('other_commission_details', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_who_authored_this_lead', related_query_name='users_who_authored_this_lead', to='relationships.user')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_with_this_country', related_query_name='lead_with_this_country', to='common.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavedLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('saved', models.DateTimeField(db_index=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_with_this_saved_leads', related_query_name='lead_with_this_saved_leads', to='leads.lead')),
                ('saver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_with_this_saved_leads', related_query_name='user_with_this_saved_leads', to='relationships.user')),
            ],
            options={
                'unique_together': {('lead', 'saver')},
            },
        ),
        migrations.CreateModel(
            name='LeadDetailAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('access_count', models.IntegerField(db_index=True)),
                ('accessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_accesses_with_this_accessor', related_query_name='detail_accesses_with_this_accessor', to='relationships.user')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_accesses_with_this_lead', related_query_name='detail_accesses_with_this_lead', to='leads.lead')),
            ],
            options={
                'unique_together': {('lead', 'accessor')},
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('response', models.CharField(blank=True, choices=[('accept', 'Accept'), ('reject', 'Reject')], db_index=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('contactor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_requests_with_this_contactor', related_query_name='contact_requests_with_this_contactor', to='relationships.user')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_requests_with_this_lead', related_query_name='contact_requests_with_this_lead', to='leads.lead')),
            ],
            options={
                'unique_together': {('contactor', 'lead')},
            },
        ),
    ]
