# Generated by Django 3.1.2 on 2021-09-26 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relationships', '0119_userconnection_userprofile_userreview'),
        ('files', '0003_auto_20210904_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('closed', models.DateTimeField(db_index=True)),
                ('is_buying', models.BooleanField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('agent_sale_commission_pct', models.FloatField(db_index=True)),
                ('location', models.CharField(max_length=200)),
                ('owner_role', models.TextField(choices=[('broker', 'Broker'), ('direct', 'Direct')], max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', related_query_name='leads', to='relationships.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavedLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_leads', related_query_name='saved_leads', to='leads.lead')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_leads', related_query_name='saved_leads', to='relationships.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('title', models.CharField(max_length=200)),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image')], max_length=200)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_files', related_query_name='lead_files', to='files.file')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_files', related_query_name='lead_files', to='leads.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
