# Generated by Django 3.0.2 on 2020-02-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='IP Address')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('chat_app', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('wechat', 'WeChat')], max_length=20)),
                ('whatsapp_no', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='WhatsApp Phone Number')),
                ('wechat_no', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='WeChat Phone Number')),
                ('i_want_to', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('buy_sell', 'Buy and Sell')], max_length=20, verbose_name='Role')),
                ('i_am_interested_to_buy', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
