# Generated by Django 3.0.5 on 2020-10-20 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandcommission',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demand_commissions', related_query_name='demand_commissions', to='relationships.Company'),
        ),
        migrations.AlterField(
            model_name='demandcommission',
            name='demand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commissions', related_query_name='commissions', to='leads.Demand'),
        ),
        migrations.AlterField(
            model_name='demandcommission',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demand_commissions', related_query_name='demand_commissions', to='relationships.Person'),
        ),
    ]
