# Generated by Django 3.1.2 on 2021-12-07 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0005_auto_20211203_1524'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterFormPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('details', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('is_buying', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_selling', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_direct', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_agent', models.BooleanField(blank=True, db_index=True, null=True)),
                ('user_country', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('lead_country', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('is_initial_deposit', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_goods_shipped', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_payment_received', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_goods_received', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_others', models.BooleanField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filter_form_posts', related_query_name='filter_form_posts', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
