# Generated by Django 3.1.2 on 2020-10-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('common', '0004_country_cc_tld'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='files',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='demand_leads', related_query_name='demand_leads', to='files.File'),
        ),
        migrations.AlterField(
            model_name='demandcommission',
            name='quotes',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='commissions', related_query_name='commissions', to='leads.DemandQuote'),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='deposit_paymodes',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='demandquote_deposit_paymodes', related_query_name='demandquote_deposit_paymodes', to='leads.PaymentMode'),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='negative_origin_countries',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='negative_origin_of_demand_quotes', related_query_name='negative_origin_of_demand_quotes', to='common.Country'),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='positive_origin_countries',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='positive_origin_of_demand_quotes', related_query_name='positive_origin_of_demand_quotes', to='common.Country'),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='remainder_paymodes',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='demandquote_remainder_paymodes', related_query_name='demandquote_remainder_paymodes', to='leads.PaymentMode'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='files',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='supply_leads', related_query_name='supply_leads', to='files.File'),
        ),
        migrations.AlterField(
            model_name='supplycommission',
            name='quotes',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='commissions', related_query_name='commissions', to='leads.SupplyQuote'),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='deposit_paymodes',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='supplyquote_deposit_paymodes', related_query_name='supplyquote_deposit_paymodes', to='leads.PaymentMode'),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='downstreams',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='_supplyquote_downstreams_+', related_query_name='upstreams', to='leads.SupplyQuote'),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='remainder_paymodes',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='supplyquote_remainder_paymodes', related_query_name='supplyquote_remainder_paymodes', to='leads.PaymentMode'),
        ),
    ]
