# Generated by Django 3.0.4 on 2020-04-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChemicalBook',
            new_name='ChemicalBookSupplier',
        ),
    ]
