# Generated by Django 3.1.2 on 2021-10-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='savedlead',
            name='owner',
        ),
    ]
