# Generated by Django 3.0.2 on 2020-02-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='i_want_to',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('buy_sell', 'Buy and Sell')], max_length=20, verbose_name='Role'),
        ),
    ]
