# Generated by Django 3.0.5 on 2020-10-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20201007_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttype',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incoterm',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='incoterm',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='incoterm',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchmethod',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='matchmethod',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='matchmethod',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchstatus',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='matchstatus',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='matchstatus',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmode',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='paymentmode',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='paymentmode',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quotestatus',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='quotestatus',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='quotestatus',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
