# Generated by Django 3.1.2 on 2021-10-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20211016_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='leadfile',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='savedlead',
            name='lead',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.DeleteModel(
            name='LeadFile',
        ),
        migrations.DeleteModel(
            name='SavedLead',
        ),
    ]
