# Generated by Django 3.1.2 on 2021-12-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0005_auto_20211203_1524'),
        ('leads', '0002_filterformpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterformpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filter_form_posts', related_query_name='filter_form_posts', to='relationships.user'),
        ),
    ]
