# Generated by Django 3.1.2 on 2021-10-17 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relationships', '0143_friendrequest'),
        ('files', '0004_remove_file_lead'),
        ('common', '0006_delete_matchkeyword'),
        ('leads', '0003_auto_20211017_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('closed', models.DateTimeField(db_index=True)),
                ('lead_type', models.CharField(blank=True, choices=[('direct', 'Direct'), ('broker', 'Broker')], max_length=20, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_buying', models.BooleanField(db_index=True)),
                ('agent_sale_commission_pct', models.FloatField(db_index=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_with_this_country', related_query_name='lead_with_this_country', to='common.country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_who_own_this_lead', related_query_name='users_who_own_this_lead', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('tag', models.CharField(db_index=True, max_length=200)),
                ('internal_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavedLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('saved', models.DateTimeField(db_index=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_with_this_saved_leads', related_query_name='lead_with_this_saved_leads', to='leads.lead')),
                ('saver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_with_this_saved_leads', related_query_name='user_with_this_saved_leads', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('uploaded', models.DateTimeField(db_index=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads_with_this_image', related_query_name='leads_with_this_image', to='files.file')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_who_own_this_lead_image', related_query_name='users_who_own_this_lead_image', to='leads.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('uploaded', models.DateTimeField(db_index=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads_with_this_document', related_query_name='leads_with_this_document', to='files.file')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_who_own_this_lead_document', related_query_name='users_who_own_this_lead_document', to='leads.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.ManyToManyField(db_index=True, related_name='lead_with_this_tags', related_query_name='lead_with_this_tags', to='leads.LeadTag'),
        ),
    ]
