# Generated by Django 3.0.5 on 2020-04-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20200403_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldofchemicalssupplier',
            name='coy_id',
            field=models.CharField(db_index=True, default=-1, max_length=1024),
            preserve_default=False,
        ),
    ]
