# Generated by Django 3.0.5 on 2020-10-08 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20201008_1009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCapability',
            new_name='ProductionCapability',
        ),
    ]
