# Generated by Django 3.1.2 on 2021-12-07 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0005_auto_20211203_1524'),
        ('leads', '0003_auto_20211207_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLeadAuthorClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('count', models.IntegerField(db_index=True)),
                ('contactor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_lead_author_clicks', related_query_name='whatsapp_lead_author_clicks', to='relationships.user')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_lead_author_clicks', related_query_name='whatsapp_lead_author_clicks', to='leads.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
