# Generated by Django 3.1.2 on 2021-12-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0005_auto_20211203_1524'),
        ('leads', '0004_whatsappleadauthorclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappleadauthorclick',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappleadauthorclick',
            unique_together={('lead', 'contactor')},
        ),
    ]
