# Generated by Django 3.1.2 on 2021-10-28 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0143_friendrequest'),
        ('leads', '0004_auto_20211017_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='lead_type',
            new_name='author_type',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='description',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='agent_sale_commission_pct',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='tags',
        ),
        migrations.AddField(
            model_name='lead',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='users_who_authored_this_lead', related_query_name='users_who_authored_this_lead', to='relationships.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='commission_payable_after',
            field=models.CharField(blank=True, choices=[('initial_deposit_received', 'Initial deposit received'), ('goods_shipped', 'Goods shipped'), ('buyer_received_goods_services', 'Buyer received goods/services'), ('full_payment_received', 'Full payment received')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='commission_pct',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='country_string',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='other_commission_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
