# Generated by Django 3.1.2 on 2020-11-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20201106_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='display_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='demandcommission',
            name='mark_up_percentage',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Mark-up percentage'),
        ),
        migrations.AlterField(
            model_name='demandcommission',
            name='mark_up_price_per_unit',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Mark-up price per unit'),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='deposit_percent',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='incoterm_location',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='price',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='productioncapability',
            name='capacity_quantity',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='productioncapability',
            name='capacity_seconds',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='display_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='supplycommission',
            name='mark_up_percentage',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Mark-up percentage'),
        ),
        migrations.AlterField(
            model_name='supplycommission',
            name='mark_up_price_per_unit',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Mark-up price per unit'),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='deposit_percent',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='incoterm_location',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='price',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='trench',
            name='after_deposit_seconds',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Seconds after deposit'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='quantity',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='uomrelationship',
            name='multiple',
            field=models.FloatField(db_index=True),
        ),
    ]
