# Generated by Django 3.0.5 on 2020-10-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20201008_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadcategory',
            options={'verbose_name_plural': 'Lead categories'},
        ),
    ]
