# Generated by Django 3.1.2 on 2021-12-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20211208_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappleadauthorclick',
            old_name='count',
            new_name='access_count',
        ),
    ]
