# Generated by Django 3.1.2 on 2021-10-29 05:41

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20211028_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaddocument',
            name='uploaded',
        ),
        migrations.RemoveField(
            model_name='leadimage',
            name='uploaded',
        ),
        migrations.AlterField(
            model_name='leaddocument',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length='7', prefix='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leadimage',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length='7', prefix='', primary_key=True, serialize=False),
        ),
    ]
