# Generated by Django 3.1.2 on 2020-12-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20201106_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadcategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='leadcategory',
            name='parents',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='_leadcategory_parents_+', related_query_name='children', to='leads.LeadCategory'),
        ),
    ]
