# Generated by Django 3.0.5 on 2020-10-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20201008_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchstatus',
            options={'verbose_name_plural': 'Match statuses'},
        ),
    ]
