# Generated by Django 3.1.2 on 2021-10-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20211029_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadTag',
        ),
    ]
