# Generated by Django 3.1.2 on 2021-12-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20211208_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='onboarded',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='onboarding',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
