# Generated by Django 3.0.5 on 2020-10-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20201008_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotestatus',
            options={'verbose_name_plural': 'Quote statuses'},
        ),
    ]
