# Generated by Django 3.1.2 on 2021-12-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20211210_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='hide_commission_details',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
