# Generated by Django 3.1.2 on 2020-12-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20201210_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcategory',
            name='parents',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='_leadcategory_parents_+', related_query_name='children', to='leads.LeadCategory'),
        ),
    ]
