# Generated by Django 3.1.2 on 2021-10-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0143_friendrequest'),
        ('leads', '0007_delete_leadtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadDetailAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('access_count', models.IntegerField(db_index=True)),
                ('accessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_accesses_with_this_accessor', related_query_name='detail_accesses_with_this_accessor', to='relationships.user')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_accesses_with_this_lead', related_query_name='detail_accesses_with_this_lead', to='leads.lead')),
            ],
            options={
                'unique_together': {('lead', 'accessor')},
            },
        ),
    ]
