# Generated by Django 3.0.5 on 2020-10-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20201008_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uomrelationship',
            name='details_md',
            field=models.TextField(blank=True, null=True),
        ),
    ]
