# Generated by Django 3.1.2 on 2020-12-10 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20201210_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='received',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supply',
            name='received',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
