# Generated by Django 3.0.5 on 2020-10-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20201008_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name': 'Supply', 'verbose_name_plural': 'Supplies'},
        ),
        migrations.AlterModelOptions(
            name='uomrelationship',
            options={'verbose_name': 'UOM relationship', 'verbose_name_plural': 'UOM relationships'},
        ),
        migrations.AlterField(
            model_name='demand',
            name='expired',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='invalidated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='invalidated_reason_md',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='demandcommission',
            name='expired',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='demandcommission',
            name='invalidated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='demandcommission',
            name='invalidated_reason_md',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='expired',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='invalidated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='invalidated_reason_md',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='expired',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='invalidated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='invalidated_reason_md',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='supplycommission',
            name='expired',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='supplycommission',
            name='invalidated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='supplycommission',
            name='invalidated_reason_md',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='expired',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='invalidated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='invalidated_reason_md',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
