# Generated by Django 3.1.2 on 2022-01-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20220126_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappleadauthorclick',
            old_name='access_count',
            new_name='count',
        ),
    ]
