# Generated by Django 3.1.2 on 2022-01-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0012_comment'),
        ('common', '0001_initial'),
        ('leads', '0010_auto_20220128_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessageBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('body', models.TextField()),
                ('contactee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_message_bodies_with_this_contactee', related_query_name='whatsapp_message_bodies_with_this_contactee', to='relationships.user')),
                ('contactor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_message_bodies_with_this_contactor', related_query_name='whatsapp_message_bodies_with_this_contactor', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsAppClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('source', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('contactee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_clicks_with_this_contactee', related_query_name='whatsapp_clicks_with_this_contactee', to='relationships.user')),
                ('contactor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_clicks_with_this_contactor', related_query_name='whatsapp_clicks_with_this_contactor', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='INeedAgentQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('search', models.CharField(max_length=200)),
                ('wants_to', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=20)),
                ('buy_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='i_need_agent_queries_with_this_buy_country', related_query_name='i_need_agent_queries_with_this_buy_country', to='common.country')),
                ('sell_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='i_need_agent_queries_with_this_sell_country', related_query_name='i_need_agent_queries_with_this_sell_country', to='common.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='i_need_agent_query', related_query_name='i_need_agent_query', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('search', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_queries', related_query_name='agent_queries', to='common.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_query', related_query_name='agent_query', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
