# Generated by Django 3.1.2 on 2020-12-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0018_auto_20201120_1304'),
        ('leads', '0010_auto_20201210_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='links',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='demand_leads', related_query_name='demand_leads', to='relationships.Link'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='links',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='supply_leads', related_query_name='supply_leads', to='relationships.Link'),
        ),
    ]
