# Generated by Django 3.0.5 on 2020-10-08 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20201008_1255'),
        ('files', '0003_auto_20201008_1740'),
        ('leads', '0010_auto_20201008_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='base_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_leads', related_query_name='demand_leads', to='leads.UnitOfMeasure', verbose_name='Base UOM'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='contact_type_details_md',
            field=models.TextField(verbose_name='Contact type details in Markdown'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='demand_leads', related_query_name='demand_leads', to='files.File'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='invalidated_reason_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Invalidated reason in Markdown'),
        ),
        migrations.AlterField(
            model_name='demandcommission',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='demandcommission',
            name='invalidated_reason_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Invalidated reason in Markdown'),
        ),
        migrations.AlterField(
            model_name='demandcommission',
            name='quotes',
            field=models.ManyToManyField(blank=True, related_name='commissions', related_query_name='commissions', to='leads.DemandQuote'),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='deposit_paymodes',
            field=models.ManyToManyField(blank=True, related_name='demandquote_deposit_paymodes', related_query_name='demandquote_deposit_paymodes', to='leads.PaymentMode'),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='invalidated_reason_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Invalidated reason in Markdown'),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='negative_origin_countries',
            field=models.ManyToManyField(blank=True, related_name='negative_origin_of_demand_quotes', related_query_name='negative_origin_of_demand_quotes', to='common.Country'),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='positive_origin_countries',
            field=models.ManyToManyField(blank=True, related_name='positive_origin_of_demand_quotes', related_query_name='positive_origin_of_demand_quotes', to='common.Country'),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='remainder_paymodes',
            field=models.ManyToManyField(blank=True, related_name='demandquote_remainder_paymodes', related_query_name='demandquote_remainder_paymodes', to='leads.PaymentMode'),
        ),
        migrations.AlterField(
            model_name='match',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productioncapability',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='base_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_leads', related_query_name='supply_leads', to='leads.UnitOfMeasure', verbose_name='Base UOM'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='contact_type_details_md',
            field=models.TextField(verbose_name='Contact type details in Markdown'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='supply_leads', related_query_name='supply_leads', to='files.File'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='invalidated_reason_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Invalidated reason in Markdown'),
        ),
        migrations.AlterField(
            model_name='supplycommission',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='supplycommission',
            name='invalidated_reason_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Invalidated reason in Markdown'),
        ),
        migrations.AlterField(
            model_name='supplycommission',
            name='quotes',
            field=models.ManyToManyField(blank=True, related_name='commissions', related_query_name='commissions', to='leads.SupplyQuote'),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='deposit_paymodes',
            field=models.ManyToManyField(blank=True, related_name='supplyquote_deposit_paymodes', related_query_name='supplyquote_deposit_paymodes', to='leads.PaymentMode'),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='downstreams',
            field=models.ManyToManyField(blank=True, related_name='_supplyquote_downstreams_+', related_query_name='upstreams', to='leads.SupplyQuote'),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='invalidated_reason_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Invalidated reason in Markdown'),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='remainder_paymodes',
            field=models.ManyToManyField(blank=True, related_name='supplyquote_remainder_paymodes', related_query_name='supplyquote_remainder_paymodes', to='leads.PaymentMode'),
        ),
    ]
