# Generated by Django 3.0.5 on 2020-10-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_auto_20201008_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='contact_type_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Contact type details in Markdown'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='contact_type_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Contact type details in Markdown'),
        ),
    ]
