# Generated by Django 3.1.2 on 2020-12-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20201210_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyquote',
            name='demand_quotes',
        ),
        migrations.RemoveField(
            model_name='supplyquote',
            name='downstreams',
        ),
    ]
