# Generated by Django 3.1.2 on 2021-11-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20211030_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='commission_payable_after',
            field=models.CharField(blank=True, choices=[('initial_deposit_received', 'Initial deposit received'), ('goods_shipped', 'Goods shipped'), ('buyer_received_goods_services', 'Buyer received goods/services'), ('full_payment_received', 'Full payment received'), ('others', 'others')], max_length=50, null=True),
        ),
    ]
