# Generated by Django 3.0.5 on 2020-10-09 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0003_auto_20201008_1740'),
        ('leads', '0012_auto_20201008_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demand_leads', related_query_name='demand_leads', to='relationships.Company'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demand_leads', related_query_name='demand_leads', to='relationships.Person'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='contact_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demand_leads', related_query_name='demand_leads', to='leads.ContactType'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_leads', related_query_name='supply_leads', to='relationships.Company'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_leads', related_query_name='supply_leads', to='relationships.Person'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='contact_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_leads', related_query_name='supply_leads', to='leads.ContactType'),
        ),
    ]
