# Generated by Django 3.1.2 on 2022-01-28 18:19

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_manual_lead_search_vector_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='search_i_need_agents_veccol',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
