# Generated by Django 3.1.2 on 2020-12-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_auto_20201210_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncapability',
            name='capacity_seconds',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
