# Generated by Django 3.0.5 on 2020-10-09 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20201008_1255'),
        ('leads', '0013_auto_20201009_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandquote',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandquote_items', related_query_name='demandquote_items', to='leads.Currency'),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='delivery_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Delivery details in Markdown'),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='deposit_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='details_md',
            field=models.TextField(verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='incoterm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandquote_items', related_query_name='demandquote_items', to='leads.Incoterm'),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='incoterm_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandquote_items', related_query_name='demandquote_items', to='common.Country'),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='incoterm_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='payterms_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Payment terms details in Markdown'),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='price_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Price details in Markdown'),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplyquote_items', related_query_name='supplyquote_items', to='leads.Currency'),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='delivery_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Delivery details in Markdown'),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='deposit_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='details_md',
            field=models.TextField(verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='incoterm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplyquote_items', related_query_name='supplyquote_items', to='leads.Incoterm'),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='incoterm_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplyquote_items', related_query_name='supplyquote_items', to='common.Country'),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='incoterm_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='payterms_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Payment terms details in Markdown'),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='price_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Price details in Markdown'),
        ),
    ]
