# Generated by Django 3.1.2 on 2022-01-28 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('leads', '0013_lead_search_i_need_agents_veccol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ineedagentquery',
            name='buy_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='i_need_agent_queries_with_this_buy_country', related_query_name='i_need_agent_queries_with_this_buy_country', to='common.country'),
        ),
        migrations.AlterField(
            model_name='ineedagentquery',
            name='search',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ineedagentquery',
            name='sell_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='i_need_agent_queries_with_this_sell_country', related_query_name='i_need_agent_queries_with_this_sell_country', to='common.country'),
        ),
        migrations.AlterField(
            model_name='ineedagentquery',
            name='wants_to',
            field=models.CharField(choices=[('buy_or_sell', 'Buy or Sell'), ('buy', 'Buy'), ('sell', 'Sell')], max_length=20),
        ),
    ]
