# Generated by Django 3.1.2 on 2021-11-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_auto_20211107_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='commission_payable_after_others',
            field=models.TextField(blank=True, null=True),
        ),
    ]
