# Generated by Django 3.1.2 on 2021-11-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_lead_commission_payable_after_others'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='is_buying',
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('buying', 'Buying'), ('selling', 'Selling')], db_index=True, default='selling', max_length=20),
            preserve_default=False,
        ),
    ]
