# Generated by Django 3.0.5 on 2020-10-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_auto_20201009_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyquote',
            name='packing_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Packing details in Markdown'),
        ),
    ]
