# Generated by Django 3.1.2 on 2021-11-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_auto_20211107_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='commission_payable_by',
            field=models.CharField(blank=True, choices=[('me', 'Me'), ('buyer', 'Buyer'), ('seller', 'Seller')], max_length=20, null=True),
        ),
    ]
