# Generated by Django 3.0.5 on 2020-10-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_auto_20201009_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncapability',
            name='end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productioncapability',
            name='start',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
