# Generated by Django 3.1.2 on 2022-01-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_auto_20220131_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentquery',
            name='search',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
