# Generated by Django 3.0.5 on 2020-10-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_auto_20201009_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandquote',
            name='negative_details_md',
            field=models.TextField(blank=True, null=True),
        ),
    ]
