# Generated by Django 3.1.2 on 2022-02-03 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0013_auto_20220130_2324'),
        ('leads', '0017_auto_20220131_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='other_commission_details',
            new_name='other_comm_details',
        ),
        migrations.AlterField(
            model_name='lead',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads_authored_by_this_user', related_query_name='leads_authored_by_this_user', to='relationships.user'),
        ),
    ]
