# Generated by Django 3.0.5 on 2020-10-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_auto_20201009_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productioncapability',
            options={'verbose_name': 'Production capability', 'verbose_name_plural': 'Production capabilities'},
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='details_as_received_md',
            field=models.TextField(verbose_name='Details as received in Markdown'),
        ),
        migrations.AlterField(
            model_name='productioncapability',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in markdown'),
        ),
    ]
