# Generated by Django 3.0.5 on 2020-10-10 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_auto_20201009_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trench',
            options={'verbose_name': 'Trench', 'verbose_name_plural': 'Trenches'},
        ),
        migrations.AlterField(
            model_name='trench',
            name='after_deposit_seconds',
            field=models.FloatField(blank=True, null=True, verbose_name='Seconds after deposit'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='demand_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trenches', related_query_name='trenches', to='leads.DemandQuote', verbose_name='Demand Quote'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='payment_before_release',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trench',
            name='paymode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trenches', related_query_name='trenches', to='leads.PaymentMode', verbose_name='Payment Mode'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='supply_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trenches', related_query_name='trenches', to='leads.SupplyQuote', verbose_name='Supply Quote'),
        ),
    ]
