# Generated by Django 3.1.2 on 2021-11-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_auto_20211111_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='country_string',
        ),
    ]
