# Generated by Django 3.1.2 on 2022-02-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0013_auto_20220130_2324'),
        ('common', '0001_initial'),
        ('leads', '0018_auto_20220203_2338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='INeedAgentQuery',
            new_name='LeadQuery',
        ),
    ]
