# Generated by Django 3.1.2 on 2020-12-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_auto_20201212_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='public_details_url',
            field=models.URLField(blank=True, db_index=True, default=None, null=True, verbose_name='Public details URL'),
        ),
        migrations.AddField(
            model_name='supply',
            name='public_details_url',
            field=models.URLField(blank=True, db_index=True, default=None, null=True, verbose_name='Public details URL'),
        ),
    ]
