# Generated by Django 3.1.2 on 2021-11-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0161_remove_user_country_string'),
        ('leads', '0019_remove_lead_country_string'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedlead',
            unique_together={('lead', 'saver')},
        ),
    ]
