# Generated by Django 3.0.5 on 2020-10-10 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0003_auto_20201008_1740'),
        ('leads', '0019_auto_20201010_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterField(
            model_name='demandcommission',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='demandcommission',
            name='mark_up_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Mark-up percentage'),
        ),
        migrations.AlterField(
            model_name='demandcommission',
            name='mark_up_price_per_unit',
            field=models.FloatField(blank=True, null=True, verbose_name='Mark-up price per unit'),
        ),
        migrations.AlterField(
            model_name='demandcommission',
            name='mark_up_type',
            field=models.CharField(choices=[('ppu', 'Price Per Unit'), ('pct', 'Percentage')], default='ppu', max_length=3, verbose_name='Mark-up type'),
        ),
        migrations.AlterField(
            model_name='match',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='match',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches', related_query_name='matches', to='leads.MatchMethod'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches', related_query_name='matches', to='leads.MatchStatus'),
        ),
        migrations.AlterField(
            model_name='supplycommission',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_commissions', related_query_name='supply_commissions', to='relationships.Company'),
        ),
        migrations.AlterField(
            model_name='supplycommission',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='supplycommission',
            name='mark_up_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Mark-up percentage'),
        ),
        migrations.AlterField(
            model_name='supplycommission',
            name='mark_up_price_per_unit',
            field=models.FloatField(blank=True, null=True, verbose_name='Mark-up price per unit'),
        ),
        migrations.AlterField(
            model_name='supplycommission',
            name='mark_up_type',
            field=models.CharField(choices=[('ppu', 'Price Per Unit'), ('pct', 'Percentage')], default='ppu', max_length=3, verbose_name='Mark-up type'),
        ),
        migrations.AlterField(
            model_name='supplycommission',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_commissions', related_query_name='supply_commissions', to='relationships.Person'),
        ),
        migrations.AlterField(
            model_name='supplycommission',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commissions', related_query_name='commissions', to='leads.Supply'),
        ),
    ]
