# Generated by Django 3.1.2 on 2022-02-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_auto_20220204_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadquery',
            name='sort_by',
            field=models.CharField(blank=True, choices=[('relevance', 'Relevance'), ('comm_percent_hi_lo', 'Avg Comm % High to Low'), ('comm_percent_lo_hi', 'Avg Comm % Low to High'), ('comm_dollar_hi_lo', 'Avg Comm $ High to Low'), ('comm_dollar_lo_hi', 'Avg Comm $ Low to High')], max_length=20, null=True),
        ),
    ]
