# Generated by Django 3.0.5 on 2020-10-10 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_auto_20201010_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandQuoteStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField(blank=True, null=True, verbose_name='Details in Markdown')),
                ('programmatic_key', models.CharField(blank=True, max_length=100, null=True)),
                ('programmatic_details_md', models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown')),
            ],
            options={
                'verbose_name_plural': 'Demand quote statuses',
            },
        ),
        migrations.CreateModel(
            name='SupplyQuoteStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField(blank=True, null=True, verbose_name='Details in Markdown')),
                ('programmatic_key', models.CharField(blank=True, max_length=100, null=True)),
                ('programmatic_details_md', models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown')),
            ],
            options={
                'verbose_name_plural': 'Supply quote statuses',
            },
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', related_query_name='quotes', to='leads.DemandQuoteStatus'),
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', related_query_name='quotes', to='leads.SupplyQuoteStatus'),
        ),
        migrations.DeleteModel(
            name='QuoteStatus',
        ),
    ]
