# Generated by Django 3.1.2 on 2021-11-12 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0161_remove_user_country_string'),
        ('leads', '0020_auto_20211113_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='savers',
            field=models.ManyToManyField(through='leads.SavedLead', to='relationships.User'),
        ),
        migrations.AlterField(
            model_name='savedlead',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='savedlead',
            name='saver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relationships.user'),
        ),
    ]
