# Generated by Django 3.1.2 on 2022-02-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_delete_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentquery',
            name='seen_unseen',
            field=models.CharField(blank=True, choices=[('all', 'Show All Items'), ('seen_only', 'Show Seen Items Only'), ('unseen_only', 'Show Unseen Items Only')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agentquery',
            name='sort_by',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='seen_unseen',
            field=models.CharField(blank=True, choices=[('all', 'Show All Items'), ('seen_only', 'Show Seen Items Only'), ('unseen_only', 'Show Unseen Items Only')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='sort_by',
            field=models.CharField(blank=True, choices=[('relevance', 'Relevance'), ('comm_percent_hi_lo', 'Avg Comm % High to Low'), ('comm_percent_lo_hi', 'Avg Comm % Low to High'), ('comm_dollar_hi_lo', 'Avg Comm $ High to Low'), ('comm_dollar_lo_hi', 'Avg Comm $ Low to High')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='wants_to',
            field=models.CharField(choices=[('buy_or_sell', 'Buy or Sell'), ('buy', 'Buy'), ('sell', 'Sell')], db_index=True, max_length=20),
        ),
    ]
