# Generated by Django 3.1.2 on 2021-11-13 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0161_remove_user_country_string'),
        ('leads', '0021_auto_20211113_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='savers',
        ),
        migrations.AlterField(
            model_name='savedlead',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_with_this_saved_leads', related_query_name='lead_with_this_saved_leads', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='savedlead',
            name='saver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_with_this_saved_leads', related_query_name='user_with_this_saved_leads', to='relationships.user'),
        ),
    ]
