# Generated by Django 3.1.2 on 2022-02-11 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0021_user_about_me'),
        ('leads', '0022_auto_20220211_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadDetailView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('count', models.IntegerField(db_index=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_detail_views', related_query_name='lead_detail_views', to='leads.lead')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_detail_views', related_query_name='lead_detail_views', to='relationships.user')),
            ],
            options={
                'unique_together': {('lead', 'viewer')},
            },
        ),
        migrations.DeleteModel(
            name='LeadDetailAccess',
        ),
    ]
