# Generated by Django 3.1.2 on 2021-11-14 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0161_remove_user_country_string'),
        ('leads', '0022_auto_20211113_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='requestee',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='requester',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='contactor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='contact_requests_with_this_contactor', related_query_name='contact_requests_with_this_contactor', to='relationships.user'),
            preserve_default=False,
        ),
    ]
