# Generated by Django 3.1.2 on 2021-11-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0161_remove_user_country_string'),
        ('leads', '0023_auto_20211114_1655'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactrequest',
            unique_together={('lead', 'contactor')},
        ),
    ]
