# Generated by Django 3.1.2 on 2022-02-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0021_user_about_me'),
        ('leads', '0023_auto_20220211_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappclick',
            name='source',
        ),
        migrations.AlterField(
            model_name='whatsappclick',
            name='contactee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_clicks_with_this_user_as_contactee', related_query_name='whatsapp_clicks_with_this_user_as_contactee', to='relationships.user'),
        ),
        migrations.AlterField(
            model_name='whatsappclick',
            name='contactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_clicks_with_this_user_as_contactor', related_query_name='whatsapp_clicks_with_this_user_as_contactor', to='relationships.user'),
        ),
    ]
