# Generated by Django 3.0.5 on 2020-10-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_auto_20201014_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandquote',
            name='details_as_received_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details as received in Markdown'),
        ),
        migrations.AlterField(
            model_name='demandquote',
            name='negative_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Negative details in Markdown'),
        ),
    ]
