# Generated by Django 3.0.5 on 2020-10-14 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0020_auto_20201014_1454'),
        ('leads', '0024_auto_20201014_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='contact',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='demand_leads', related_query_name='demand_leads', to='relationships.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demand',
            name='contact_type',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='demand_leads', related_query_name='demand_leads', to='leads.ContactType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supply',
            name='contact',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='supply_leads', related_query_name='supply_leads', to='relationships.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supply',
            name='contact_type',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='supply_leads', related_query_name='supply_leads', to='leads.ContactType'),
            preserve_default=False,
        ),
    ]
