# Generated by Django 3.1.2 on 2021-11-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0161_remove_user_country_string'),
        ('leads', '0024_auto_20211114_1837'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactrequest',
            unique_together={('contactor', 'lead')},
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='access_count',
        ),
    ]
