# Generated by Django 3.1.2 on 2021-11-14 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0161_remove_user_country_string'),
        ('leads', '0025_auto_20211114_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('message', models.TextField()),
                ('contactor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_accesses_with_this_contactor', related_query_name='contact_accesses_with_this_contactor', to='relationships.user')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_accesses_with_this_lead', related_query_name='contact_accesses_with_this_lead', to='leads.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
