# Generated by Django 3.1.2 on 2022-02-12 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_auto_20220211_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentquery',
            name='seen_unseen',
        ),
        migrations.RemoveField(
            model_name='leadquery',
            name='seen_unseen',
        ),
        migrations.DeleteModel(
            name='LeadSeen',
        ),
    ]
