# Generated by Django 3.1.2 on 2021-11-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_contactaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='requested',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='responded',
        ),
        migrations.DeleteModel(
            name='ContactAccess',
        ),
    ]
