# Generated by Django 3.1.2 on 2022-02-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_remove_lead_avg_comm_pct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='hide_commission_details',
        ),
    ]
