# Generated by Django 3.1.2 on 2021-11-15 08:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_auto_20211115_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
