# Generated by Django 3.1.2 on 2022-02-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_remove_lead_hide_commission_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='commission_pct',
            new_name='commissions',
        ),
    ]
