# Generated by Django 3.1.2 on 2022-02-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_auto_20220216_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='need_agent',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
