# Generated by Django 3.1.2 on 2022-02-15 16:29

from django.db import migrations, models
import django.db.models.deletion
# import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_lead_need_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # ('image', sorl.thumbnail.fields.ImageField(upload_to='leads')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_images', related_query_name='lead_images', to='leads.lead')),
            ],
        ),
    ]
