# Generated by Django 3.1.2 on 2022-02-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_leadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='commission_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('other', 'Other')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='commission_type_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='author_type',
            field=models.CharField(blank=True, choices=[('direct', 'Direct'), ('broker', 'Broker')], db_index=True, default='direct', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='avg_deal_size',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='commission_payable_after',
            field=models.CharField(blank=True, choices=[('initial_deposit_received', 'Initial deposit received'), ('goods_shipped', 'Goods shipped'), ('buyer_received_goods_services', 'Buyer received goods/services'), ('full_payment_received', 'Full payment received'), ('others', 'others')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='commission_payable_by',
            field=models.CharField(blank=True, choices=[('me', 'Me'), ('buyer', 'Buyer'), ('seller', 'Seller')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
