# Generated by Django 3.1.2 on 2022-02-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0032_auto_20220216_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='need_agent',
            field=models.BooleanField(db_index=True, default=True),
            preserve_default=False,
        ),
    ]
