# Generated by Django 3.1.2 on 2022-02-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0033_auto_20220216_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='author_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('broker', 'Broker')], db_index=True, default='direct', max_length=20),
        ),
    ]
