# Generated by Django 3.1.2 on 2022-02-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0035_auto_20220216_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
