# Generated by Django 3.1.2 on 2022-02-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0036_auto_20220216_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='commission_payable_by',
            field=models.CharField(choices=[('me', 'Me'), ('buyer', 'Buyer'), ('seller', 'Seller')], db_index=True, default='me', max_length=20),
            preserve_default=False,
        ),
    ]
