# Generated by Django 3.1.2 on 2022-02-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0037_auto_20220216_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='commission_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('other', 'Other')], db_index=True, default='percentage', max_length=20),
            preserve_default=False,
        ),
    ]
