# Generated by Django 3.1.2 on 2022-02-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0041_auto_20220217_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='commission_payable_after_others',
            new_name='commission_payable_after_other',
        ),
        migrations.AlterField(
            model_name='lead',
            name='commission_payable_after',
            field=models.CharField(blank=True, choices=[('initial_deposit_received', 'Initial deposit received'), ('goods_shipped', 'Goods shipped'), ('buyer_received_goods_services', 'Buyer received goods/services'), ('full_payment_received', 'Full payment received'), ('other', 'Other')], db_index=True, max_length=50, null=True),
        ),
    ]
