# Generated by Django 3.1.2 on 2022-02-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0042_auto_20220217_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_comm_negotiable',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
