# Generated by Django 3.1.2 on 2022-02-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0043_lead_is_comm_negotiable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='commission_payable_by',
            field=models.CharField(blank=True, choices=[('me', 'Me'), ('buyer', 'Buyer'), ('seller', 'Seller')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='commission_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('other', 'Other')], db_index=True, max_length=20, null=True),
        ),
    ]
