# Generated by Django 3.1.2 on 2022-02-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0044_auto_20220218_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
