# Generated by Django 3.1.2 on 2022-02-24 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0046_auto_20220219_0455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadImage',
        ),
    ]
