# Generated by Django 3.1.2 on 2022-02-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0047_delete_leadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='need_logistics_agent',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='other_logistics_agent_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='saved_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='search_appearance_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='search_to_lead_details_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='search_to_user_details_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
