# Generated by Django 3.1.2 on 2022-02-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0025_registertoken_is_not_latest'),
        ('common', '0001_initial'),
        ('leads', '0056_auto_20220224_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads_author', related_query_name='leads_author', to='relationships.user'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='buy_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads_buy_country', related_query_name='leads_buy_country', to='common.country'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads_country', related_query_name='leads_country', to='common.country'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='sell_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads_sell_country', related_query_name='leads_sell_country', to='common.country'),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='buy_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_queries_buy_country', related_query_name='lead_queries_buy_country', to='common.country'),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='sell_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_queries_sell_country', related_query_name='lead_queries_sell_country', to='common.country'),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_query', related_query_name='lead_query', to='relationships.user'),
        ),
        migrations.AlterField(
            model_name='savedlead',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_leads_lead', related_query_name='saved_leads_lead', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='savedlead',
            name='saver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_leads_saver', related_query_name='saved_leads_saver', to='relationships.user'),
        ),
        migrations.AlterField(
            model_name='whatsappclick',
            name='contactee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_clicks_contactee', related_query_name='whatsapp_clicks_contactee', to='relationships.user'),
        ),
        migrations.AlterField(
            model_name='whatsappclick',
            name='contactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_clicks_contactor', related_query_name='whatsapp_clicks_contactor', to='relationships.user'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagebody',
            name='contactee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_message_bodies_contactee', related_query_name='whatsapp_message_bodies_contactee', to='relationships.user'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagebody',
            name='contactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_message_bodies_contactor', related_query_name='whatsapp_message_bodies_contactor', to='relationships.user'),
        ),
    ]
