# Generated by Django 3.1.2 on 2022-02-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0057_auto_20220224_1823')
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                ALTER TABLE leads_lead DROP COLUMN search_i_need_agents_veccol CASCADE;
            '''
        ),
    ]
