# Generated by Django 3.1.2 on 2022-02-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0058_drop_i_need_agent_query_veccol_20220224_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedlead',
            name='saved',
        ),
        migrations.AddField(
            model_name='savedlead',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
