# Generated by Django 3.1.2 on 2022-03-03 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0046_delete_leadcomment'),
        ('leads', '0059_auto_20220228_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('body', models.TextField()),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_comments_as_commentor', related_query_name='lead_comments_as_commentor', to='relationships.user')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_comments', related_query_name='lead_comments', to='leads.lead')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', related_query_name='replies', to='leads.leadcomment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
