# Generated by Django 3.1.2 on 2022-03-05 13:26

from django.db import migrations, models
import random

def _random_str():
    return str(random.randint(0,10000))

class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0060_leadcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='slug_link',
            field=models.CharField(db_index=True, default=_random_str, max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='slug_tokens',
            field=models.TextField(blank=True, null=True),
        ),
    ]
