# Generated by Django 3.1.2 on 2022-03-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0063_populate_uuid_fields_20220305_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='slug_link',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
