# Generated by Django 3.1.2 on 2022-03-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0064_auto_20220305_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='slug_link',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
