# Generated by Django 3.1.2 on 2022-03-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0065_auto_20220305_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadquery',
            name='search',
        ),
        migrations.RemoveField(
            model_name='leadquery',
            name='wants_to',
        ),
        migrations.AddField(
            model_name='leadquery',
            name='buy_sell',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='comm_negotiable',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='commented_only',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='commented_only_other',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='commission_payable_after',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='commission_payable_after_other',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='commission_type',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='direct_middleman',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='goods_services',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='max_avg_deal',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='max_commission',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='min_avg_deal',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='min_commision',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='need_agent',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='need_logistics_agent',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='other_agent_details',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='other_logistics_agent_details',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='saved_only',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='buy_country',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='sell_country',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='sort_by',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
