# Generated by Django 3.1.2 on 2022-03-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0066_auto_20220312_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadquery',
            name='sort_by',
        ),
    ]
