# Generated by Django 3.1.2 on 2022-03-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0067_remove_leadquery_sort_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadquery',
            old_name='other_logistics_agent_details',
            new_name='logistics_agent_details',
        ),
    ]
