# Generated by Django 3.1.2 on 2022-03-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0068_auto_20220314_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadquery',
            name='commission_type_other',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='commented_only_other',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='commission_payable_after_other',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='goods_services',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='logistics_agent_details',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='other_agent_details',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
