# Generated by Django 3.1.2 on 2022-03-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0069_auto_20220314_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadquery',
            old_name='min_commision',
            new_name='min_commission',
        ),
    ]
