# Generated by Django 3.1.2 on 2022-03-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0070_auto_20220314_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadquery',
            name='buy_country',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='buy_sell',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='comm_negotiable',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='commission_payable_after',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='commission_type',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='direct_middleman',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='max_avg_deal',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='max_commission',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='min_avg_deal',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='min_commission',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='need_agent',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='need_logistics_agent',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='sell_country',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
