# Generated by Django 3.1.2 on 2022-03-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0071_auto_20220314_1417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentQuery',
        ),
    ]
