# Generated by Django 3.1.2 on 2022-04-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0053_auto_20220408_0225'),
        ('leads', '0074_auto_20220315_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='search_to_lead_details_count',
            new_name='clicks',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='commission',
            new_name='commission_percentage',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='search_appearance_count',
            new_name='impressions',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='onboarded',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='onboarding',
        ),
        migrations.AddField(
            model_name='lead',
            name='agent_job',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='commission_earnings',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='commission_quantity_unit_string',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_promoted',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LeadQueryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('search', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('buy_sell', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('buy_country', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('sell_country', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_query_logs', related_query_name='lead_query_logs', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationQueryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('status', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_query_logs', related_query_name='application_query_logs', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_messages', related_query_name='application_messages', to='leads.lead')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_messages', related_query_name='application_messages', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('question_1', models.TextField(blank=True, null=True)),
                ('answer_1', models.TextField(blank=True, null=True)),
                ('question_2', models.TextField(blank=True, null=True)),
                ('answer_2', models.TextField(blank=True, null=True)),
                ('other_questions', models.TextField(blank=True, null=True)),
                ('other_answers', models.TextField(blank=True, null=True)),
                ('applicant_comments', models.TextField(blank=True, null=True)),
                ('response', models.CharField(blank=True, choices=[('rejected', 'Rejected'), ('started_work', 'Started Work'), ('stopped_work', 'Stopped Work')], max_length=200, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', related_query_name='applications', to='relationships.user')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', related_query_name='applications', to='leads.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
