# Generated by Django 3.1.2 on 2022-04-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0075_auto_20220408_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='commission_type',
            field=models.CharField(blank=True, choices=[('earning', 'Earning'), ('percentage', 'Percentage'), ('other', 'Other')], db_index=True, max_length=20, null=True),
        ),
    ]
