# Generated by Django 3.1.2 on 2022-04-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0076_auto_20220408_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='headline',
            field=models.CharField(db_index=True, default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='question_1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='question_2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='question_3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='agent_job',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='commission_type',
            field=models.CharField(choices=[('earning', 'Earning'), ('percentage', 'Percentage'), ('other', 'Other')], db_index=True, default='percentage', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
