# Generated by Django 3.1.2 on 2022-04-11 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20220411_1726'),
        ('leads', '0077_auto_20220411_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='leads_currency', related_query_name='leads_currency', to='payments.currency'),
            preserve_default=False,
        ),
    ]
