# Generated by Django 3.1.2 on 2022-04-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0078_lead_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='other_agent_details',
            new_name='other_comm_details',
        ),
    ]
