# Generated by Django 3.1.2 on 2022-04-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0079_auto_20220411_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='need_agent',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
