# Generated by Django 3.1.2 on 2022-04-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0080_auto_20220411_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='other_answers',
            new_name='answer_3',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='other_questions',
            new_name='question_3',
        ),
    ]
