# Generated by Django 3.1.2 on 2022-04-12 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0081_auto_20220412_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmessage',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_messages', related_query_name='application_messages', to='leads.application'),
        ),
    ]
