# Generated by Django 3.1.2 on 2022-04-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0082_auto_20220413_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadquerylog',
            old_name='search',
            new_name='goods_string',
        ),
    ]
