# Generated by Django 3.1.2 on 2022-04-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0055_auto_20220411_1806'),
        ('leads', '0084_auto_20220413_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadquerylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_query_logs', related_query_name='lead_query_logs', to='relationships.user'),
        ),
    ]
