# Generated by Django 3.1.2 on 2022-04-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0087_lead_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='leadquerylog',
            name='user_agent',
        ),
    ]
