# Generated by Django 3.1.2 on 2022-04-14 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0089_headline_details_vec_20220414_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadquerylog',
            old_name='goods_services',
            new_name='search',
        ),
    ]
