# Generated by Django 3.1.2 on 2022-04-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0055_auto_20220411_1806'),
        ('leads', '0091_auto_20220415_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadquerylog',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='leadquerylog',
            unique_together={('user', 'search', 'buy_sell', 'buy_country', 'sell_country')},
        ),
    ]
