# Generated by Django 3.1.2 on 2022-04-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0092_auto_20220415_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='question_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='question_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='question_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
