# Generated by Django 3.1.2 on 2022-05-02 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20220411_1726'),
        ('leads', '0093_auto_20220419_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='agent_job',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='author_type',
            field=models.CharField(blank=True, choices=[('direct', 'Direct'), ('broker', 'Broker')], db_index=True, default='direct', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads_currency', related_query_name='leads_currency', to='payments.currency'),
        ),
    ]
