# Generated by Django 3.1.2 on 2022-05-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0094_auto_20220502_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='has_buyers',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='has_experience',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
