# Generated by Django 3.1.2 on 2022-05-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0095_auto_20220503_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_messaged',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
