# Generated by Django 3.1.2 on 2022-05-04 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0060_auto_20220501_2045'),
        ('leads', '0096_application_last_messaged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications_as_applicant', related_query_name='applications_as_applicant', to='relationships.user'),
        ),
    ]
