# Generated by Django 3.1.2 on 2022-05-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0097_auto_20220504_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='comm_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
