# Generated by Django 3.1.2 on 2022-05-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0098_auto_20220504_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='answers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
