# Generated by Django 3.1.2 on 2022-05-05 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0099_auto_20220505_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmessage',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', related_query_name='messages', to='leads.application'),
        ),
    ]
