# Generated by Django 3.1.2 on 2022-05-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0100_auto_20220505_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='deleted_by',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('author', 'Author')], db_index=True, max_length=20, null=True),
        ),
    ]
