# Generated by Django 3.1.2 on 2022-05-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0101_application_deleted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='commission_percentage',
            new_name='max_commission_percentage',
        ),
        migrations.AddField(
            model_name='lead',
            name='min_commission_percentage',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
