# Generated by Django 3.1.2 on 2022-05-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0102_auto_20220512_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadQuery',
        ),
    ]
