# Generated by Django 3.1.2 on 2022-05-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0060_auto_20220501_2045'),
        ('leads', '0103_delete_leadquery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeadQueryLog',
            new_name='LeadQuery',
        ),
    ]
