# Generated by Django 3.1.2 on 2022-05-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0104_auto_20220516_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadquery',
            name='max_commission_percentage',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='min_commission_percentage',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
