# Generated by Django 3.1.2 on 2022-05-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0105_auto_20220516_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadquery',
            old_name='search',
            new_name='search_phrase',
        ),
        migrations.AddField(
            model_name='leadquery',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='leadquery',
            unique_together=set(),
        ),
    ]
