# Generated by Django 3.1.2 on 2022-05-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0106_auto_20220516_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadquery',
            options={'verbose_name_plural': 'Lead queries'},
        ),
        migrations.AddField(
            model_name='application',
            name='stopped_follow_up',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
