# Generated by Django 3.1.2 on 2022-05-17 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0108_applicationfollowup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationFollowUp',
        ),
    ]
