# Generated by Django 3.1.2 on 2022-05-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0109_delete_applicationfollowup'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
