# Generated by Django 3.1.2 on 2022-05-24 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0111_auto_20220524_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadcategory',
            options={'verbose_name_plural': 'Lead categories'},
        ),
    ]
