# Generated by Django 3.1.2 on 2022-05-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0113_leadquery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='has_insights',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='has_insights',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
