# Generated by Django 3.1.2 on 2022-05-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0114_auto_20220528_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='commission_usd_mt',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='commission_type',
            field=models.CharField(choices=[('earning', 'Earning'), ('percentage', 'Percentage'), ('usd_mt', 'USD per MT'), ('other', 'Other')], db_index=True, max_length=20),
        ),
    ]
