# Generated by Django 3.1.2 on 2022-05-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0115_auto_20220528_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
