# Generated by Django 3.1.2 on 2022-06-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0116_auto_20220530_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='commission_type',
            field=models.CharField(choices=[('negotiable', 'Negotiable'), ('earning', 'Earning'), ('percentage', 'Percentage'), ('usd_mt', 'USD per MT'), ('other', 'Other')], db_index=True, max_length=20),
        ),
    ]
