# Generated by Django 3.1.2 on 2022-06-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0117_auto_20220601_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('buying', 'Buying'), ('selling', 'Selling'), ('other', 'Other')], db_index=True, max_length=20),
        ),
    ]
