# Generated by Django 3.1.2 on 2022-06-20 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0066_user_has_insights'),
        ('leads', '0118_auto_20220619_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('is_whatsapp', models.BooleanField(blank=True, null=True)),
                ('is_wechat', models.BooleanField(blank=True, null=True)),
                ('wechat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_telegram', models.BooleanField(blank=True, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=50, null=True)),
                ('is_line', models.BooleanField(blank=True, null=True)),
                ('line_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_viber', models.BooleanField(blank=True, null=True)),
                ('is_other', models.BooleanField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', related_query_name='contacts', to='relationships.email')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', related_query_name='contacts', to='leads.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('body', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', related_query_name='notes', to='leads.contact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('wechat', 'WeChat'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('line', 'LINE'), ('copy_email', 'Copy Email'), ('copy_phone', 'Copy Phone')], db_index=True, max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', related_query_name='actions', to='leads.contact')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
