# Generated by Django 3.1.2 on 2022-06-22 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0068_user_avatar'),
        ('leads', '0119_contact_contactaction_contactnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads_with_author', related_query_name='leads_with_author', to='relationships.user'),
        ),
    ]
