# Generated by Django 3.1.2 on 2022-06-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0068_user_avatar'),
        ('leads', '0120_auto_20220622_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', related_query_name='contacts', to='relationships.phonenumber'),
        ),
        migrations.AddField(
            model_name='contact',
            name='purpose',
            field=models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('sell_on_comm', 'Sell on Commission'), ('buy_on_comm', 'Buy on Commission')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', related_query_name='contacts', to='relationships.email'),
        ),
    ]
