# Generated by Django 3.1.2 on 2022-06-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0123_auto_20220624_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactnote',
            name='relevance',
            field=models.CharField(blank=True, choices=[('relevant', 'Relevant'), ('maybe_later', 'Maybe Later'), ('not_relevant', 'Not Relevant')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactnote',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
