# Generated by Django 3.1.2 on 2022-07-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0125_auto_20220702_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='is_sell_comm',
            new_name='is_sales_agent',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='is_buy_comm',
            new_name='is_sourcing_agent',
        ),
        migrations.AddField(
            model_name='contact',
            name='is_logistics_agent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_looking_for_sales_agent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_looking_for_sourcing_agent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='need_logistics',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
