# Generated by Django 3.1.2 on 2022-07-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0127_auto_20220709_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_logistics_agent',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_looking_for_sales_agent',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_looking_for_sourcing_agent',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_sales_agent',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_seller',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_sourcing_agent',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='need_logistics',
        ),
    ]
