# Generated by Django 3.1.2 on 2022-07-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0129_auto_20220710_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('buying', 'Buying'), ('selling', 'Selling'), ('need_logistics', 'Need Logistics'), ('sourcing_agent', 'Sourcing Agent'), ('sales_agent', 'Sales Agent'), ('logistics_agent', 'Logistics Agent'), ('other', 'Other')], db_index=True, max_length=20),
        ),
    ]
