# Generated by Django 3.1.2 on 2022-07-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0131_auto_20220710_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='buying_help_find_buyers',
            new_name='buying_help_find_sellers',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='selling_help_find_sellers',
            new_name='selling_help_find_buyers',
        ),
    ]
