# Generated by Django 3.1.2 on 2022-07-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0132_auto_20220710_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='buying_other',
            new_name='to_buying_as_other',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='buying_promoting_goods',
            new_name='to_buying_as_promoting_goods',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='buying_help_find_sellers',
            new_name='to_buying_as_sourcing_agent',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='logistics_agent_need_logistics',
            new_name='to_logistics_agent_as_need_logistics',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='logistics_agent_other',
            new_name='to_logistics_agent_as_other',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='need_logistics_logistics_agent',
            new_name='to_need_logistics_as_logistics_agent',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='need_logistics_other',
            new_name='to_need_logistics_as_other',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='sales_agent_other',
            new_name='to_sales_agent_as_other',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='sales_agent_cooperate_as_agent',
            new_name='to_sales_agent_as_seeking_cooperation',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='sales_agent_sourcing_goods',
            new_name='to_sales_agent_as_sourcing_goods',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='selling_other',
            new_name='to_selling_as_other',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='selling_help_find_buyers',
            new_name='to_selling_as_sales_agent',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='selling_sourcing_goods',
            new_name='to_selling_as_sourcing_goods',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='sourcing_agent_other',
            new_name='to_sourcing_agent_as_other',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='sourcing_agent_promoting_goods',
            new_name='to_sourcing_agent_as_promoting_goods',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='sourcing_agent_cooperate_as_agent',
            new_name='to_sourcing_agent_as_seeking_cooperation',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sales_agent_recruiting_agents',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sourcing_agent_recruiting_agents',
        ),
    ]
