# Generated by Django 3.1.2 on 2022-07-12 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0069_auto_20220707_1824'),
        ('leads', '0134_contactaction_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='LeadFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flags', related_query_name='flags', to='leads.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flags', related_query_name='flags', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
