# Generated by Django 3.1.2 on 2022-07-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0135_auto_20220713_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='commission_type',
            field=models.CharField(blank=True, choices=[('negotiable', 'Negotiable'), ('earning', 'Earning'), ('percentage', 'Percentage'), ('usd_mt', 'USD per MT'), ('other', 'Other')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='headline',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
    ]
