# Generated by Django 3.1.2 on 2022-07-13 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0069_auto_20220707_1824'),
        ('leads', '0137_details_vec_20220224_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadflag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flags', related_query_name='flags', to='relationships.user'),
        ),
    ]
