# Generated by Django 3.1.2 on 2022-07-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0139_auto_20220713_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leadflag',
            unique_together={('lead', 'type')},
        ),
    ]
