# Generated by Django 3.1.2 on 2022-07-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0141_auto_20220713_1914'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leadflag',
            unique_together=set(),
        ),
    ]
