# Generated by Django 3.1.2 on 2022-07-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0069_auto_20220707_1824'),
        ('leads', '0144_auto_20220713_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadflag',
            old_name='session_key',
            new_name='cookie_uuid',
        ),
        migrations.AlterUniqueTogether(
            name='leadflag',
            unique_together={('lead', 'type', 'cookie_uuid', 'user')},
        ),
    ]
