# Generated by Django 3.1.2 on 2022-07-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0069_auto_20220707_1824'),
        ('leads', '0145_auto_20220714_0000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeadQuery',
            new_name='LeadQueryAction',
        ),
    ]
