# Generated by Django 3.1.2 on 2022-07-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0146_auto_20220714_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadqueryaction',
            name='cookie_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leadqueryaction',
            name='logistics_agent',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='leadqueryaction',
            name='need_logistics',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='leadqueryaction',
            name='other',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='leadqueryaction',
            name='promoting',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='leadqueryaction',
            name='sales_agent',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='leadqueryaction',
            name='sourcing',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='leadqueryaction',
            name='sourcing_agent',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='leadqueryaction',
            name='verified_country',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadqueryaction',
            name='count',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
