# Generated by Django 3.1.2 on 2022-07-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0147_auto_20220714_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadqueryaction',
            old_name='verified_country',
            new_name='verified_user_country',
        ),
        migrations.AddField(
            model_name='leadqueryaction',
            name='user_country',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
