# Generated by Django 3.1.2 on 2022-07-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0150_auto_20220715_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadqueryaction',
            old_name='verified_user_country',
            new_name='user_country_verified',
        ),
    ]
