# Generated by Django 3.1.2 on 2022-07-16 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0071_auto_20220714_2230'),
        ('common', '0001_initial'),
        ('leads', '0151_auto_20220715_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('cookie_uuid', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('via_whatsapp', models.BooleanField(blank=True, null=True)),
                ('via_wechat', models.BooleanField(blank=True, null=True)),
                ('via_wechat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='search_notifications', related_query_name='search_notifications', to='common.country')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='search_notifications', related_query_name='search_notifications', to='relationships.email')),
                ('lead_query_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='search_notifications', related_query_name='search_notifications', to='leads.leadqueryaction')),
                ('phone_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='search_notifications', related_query_name='search_notifications', to='relationships.phonenumber')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
