# Generated by Django 3.1.2 on 2022-07-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0154_magiclinkredirect_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MagicLinkRedirect',
        ),
    ]
