# Generated by Django 3.1.2 on 2022-07-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0155_delete_magiclinkredirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadqueryaction',
            name='reduce_spams_and_scams',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
