# Generated by Django 3.1.2 on 2021-11-26 06:56

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field
import relationships.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('verified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('email', common.models.LowerCaseEmailField(db_index=True, max_length=254, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emails', related_query_name='emails', to='common.importjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('country_code', models.CharField(db_index=True, default=None, max_length=50, validators=[relationships.models.validate_country_code])),
                ('national_number', models.CharField(db_index=True, default=None, max_length=100, validators=[relationships.models.validate_national_number])),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('registered', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(db_index=True, max_length=20)),
                ('last_name', models.CharField(db_index=True, max_length=20)),
                ('languages_string', models.CharField(blank=True, max_length=200, null=True)),
                ('state_string', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_w_this_country', related_query_name='users_w_this_country', to='common.country')),
                ('django_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', related_query_name='user', to=settings.AUTH_USER_MODEL)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', related_query_name='user', to='relationships.email')),
                ('languages', models.ManyToManyField(blank=True, db_index=True, related_name='users_w_this_language', related_query_name='users_w_this_language', to='common.Language')),
                ('phone_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', related_query_name='user', to='relationships.phonenumber')),
                ('profile_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_w_this_profile_picture', related_query_name='users_w_this_profile_picture', to='files.file')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_w_this_state', related_query_name='users_w_this_state', to='common.state')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('token', models.CharField(db_index=True, default=relationships.models.get_token, max_length=200, unique=True)),
                ('activated', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('refreshed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expiry_secs', models.IntegerField(db_index=True, default=900)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_tokens', related_query_name='register_tokens', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='types',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='phone_numbers', related_query_name='phone_numbers', to='relationships.PhoneNumberType'),
        ),
        migrations.CreateModel(
            name='LoginToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('activated', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('refreshed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('token', models.CharField(db_index=True, default=relationships.models.get_token, max_length=200, unique=True)),
                ('expiry_secs', models.IntegerField(db_index=True, default=900)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='login_tokens', related_query_name='login_tokens', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvalidEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('email', common.models.LowerCaseCharField(db_index=True, max_length=1000, unique=True)),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invalid_emails', related_query_name='invalid_emails', to='common.importjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='email',
            name='invalid_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clean_email', related_query_name='clean_email', to='relationships.invalidemail'),
        ),
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('is_mobile', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_tablet', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_touch_capable', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_pc', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_bot', models.BooleanField(blank=True, db_index=True, null=True)),
                ('browser', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('browser_family', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('browser_version', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('browser_version_string', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('os', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('os_family', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('os_version', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('os_version_string', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('device', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('device_family', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_agents', related_query_name='user_agents', to='relationships.user')),
            ],
            options={
                'unique_together': {('user', 'ip_address', 'is_mobile', 'is_tablet', 'is_touch_capable', 'is_pc', 'is_bot', 'browser', 'browser_family', 'browser_version', 'browser_version_string', 'os', 'os_family', 'os_version', 'os_version_string', 'device', 'device_family')},
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberHash',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length='7', prefix='', primary_key=True, serialize=False)),
                ('link_type', models.CharField(blank=True, choices=[('contact', 'Contact'), ('verification', 'Verification'), ('register', 'Register'), ('login', 'Login')], max_length=20, null=True)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phone_number_hashes', related_query_name='phone_number_hashes', to='relationships.phonenumber')),
                ('phone_number_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phone_number_hashes', related_query_name='phone_number_hashes', to='relationships.phonenumbertype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phone_number_hashes', related_query_name='phone_number_hashes', to='relationships.user')),
            ],
            options={
                'verbose_name': 'Phone number hash',
                'verbose_name_plural': 'Phone number hashes',
                'index_together': {('user', 'phone_number_type', 'phone_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together={('country_code', 'national_number')},
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('connected', models.DateTimeField(auto_now=True, db_index=True)),
                ('user_one_contact_count', models.IntegerField(default=0)),
                ('user_two_contact_count', models.IntegerField(default=0)),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_with_this_connection_as_one', related_query_name='users_with_this_connection_as_one', to='relationships.user')),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_with_this_connection_as_two', related_query_name='users_with_this_connection_as_two', to='relationships.user')),
            ],
            options={
                'unique_together': {('user_one', 'user_two')},
            },
        ),
    ]
