# Generated by Django 3.0.5 on 2020-10-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('address_3', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', related_query_name='addresses', to='common.Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', related_query_name='addresses', to='common.State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField()),
                ('programmatic_key', models.CharField(max_length=100)),
                ('programmatic_details_md', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('notes_md', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyAddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField()),
                ('programmatic_key', models.CharField(max_length=100)),
                ('programmatic_details_md', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyEmailType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField()),
                ('programmatic_key', models.CharField(max_length=100)),
                ('programmatic_details_md', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyLinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField()),
                ('programmatic_key', models.CharField(max_length=100)),
                ('programmatic_details_md', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyPhoneNumberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField()),
                ('programmatic_key', models.CharField(max_length=100)),
                ('programmatic_details_md', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('last_visited_okay', models.DateTimeField(default=None, null=True)),
                ('link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField()),
                ('programmatic_key', models.CharField(max_length=100)),
                ('programmatic_details_md', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('given_name', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('notes_md', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonAddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField()),
                ('programmatic_key', models.CharField(max_length=100)),
                ('programmatic_details_md', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonCompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField()),
                ('programmatic_key', models.CharField(max_length=100)),
                ('programmatic_details_md', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonEmailType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField()),
                ('programmatic_key', models.CharField(max_length=100)),
                ('programmatic_details_md', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonLinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField()),
                ('programmatic_key', models.CharField(max_length=100)),
                ('programmatic_details_md', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonPhoneNumberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField()),
                ('programmatic_key', models.CharField(max_length=100)),
                ('programmatic_details_md', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField()),
                ('programmatic_key', models.CharField(max_length=100)),
                ('programmatic_details_md', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('country_code', models.CharField(max_length=100)),
                ('national_number', models.CharField(max_length=100)),
                ('types', models.ManyToManyField(related_name='phone_numbers', related_query_name='phone_numbers', to='relationships.PhoneNumber')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_md', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personphonenumber_items', related_query_name='personphonenumber_items', to='relationships.Person')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personphonenumber_items', related_query_name='personphonenumber_items', to='relationships.PhoneNumber')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personphonenumber_items', related_query_name='personphonenumber_items', to='relationships.PersonPhoneNumberType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_md', models.TextField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personlink_items', related_query_name='personlink_items', to='relationships.Link')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personlink_items', related_query_name='personlink_items', to='relationships.Person')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personlink_items', related_query_name='personlink_items', to='relationships.PersonLinkType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_md', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personemail_items', related_query_name='personemail_items', to='relationships.Email')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personemail_items', related_query_name='personemail_items', to='relationships.Person')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personemail_items', related_query_name='personemail_items', to='relationships.PersonEmailType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_md', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personcompany_items', related_query_name='personcompany_items', to='relationships.Company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personcompany_items', related_query_name='personcompany_items', to='relationships.Person')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personcompany_items', related_query_name='personcompany_items', to='relationships.PersonLinkType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_md', models.TextField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personaddress_items', related_query_name='personaddress_items', to='relationships.Address')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personaddress_items', related_query_name='personaddress_items', to='relationships.Person')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personaddress_items', related_query_name='personaddress_items', to='relationships.PersonAddressType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='addresses',
            field=models.ManyToManyField(related_name='persons', related_query_name='persons', through='relationships.PersonAddress', to='relationships.Address'),
        ),
        migrations.AddField(
            model_name='person',
            name='companies',
            field=models.ManyToManyField(related_name='persons', related_query_name='persons', through='relationships.PersonCompany', to='relationships.Company'),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persons', related_query_name='persons', to='common.Country'),
        ),
        migrations.AddField(
            model_name='person',
            name='emails',
            field=models.ManyToManyField(related_name='persons', related_query_name='persons', through='relationships.PersonEmail', to='relationships.Email'),
        ),
        migrations.AddField(
            model_name='person',
            name='links',
            field=models.ManyToManyField(related_name='persons', related_query_name='persons', through='relationships.PersonLink', to='relationships.Link'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_numbers',
            field=models.ManyToManyField(related_name='persons', related_query_name='persons', through='relationships.PersonPhoneNumber', to='relationships.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persons', related_query_name='persons', to='common.State'),
        ),
        migrations.AddField(
            model_name='link',
            name='types',
            field=models.ManyToManyField(related_name='links', related_query_name='links', to='relationships.LinkType'),
        ),
        migrations.CreateModel(
            name='CompanyPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_md', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companyphonenumber_items', related_query_name='companyphonenumber_items', to='relationships.Company')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companyphonenumber_items', related_query_name='companyphonenumber_items', to='relationships.PhoneNumber')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companyphonenumber_items', related_query_name='companyphonenumber_items', to='relationships.CompanyPhoneNumberType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_md', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companylink_items', related_query_name='companylink_items', to='relationships.Company')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companylink_items', related_query_name='companylink_items', to='relationships.Link')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companylink_items', related_query_name='companylink_items', to='relationships.CompanyLinkType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_md', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companyemail_items', related_query_name='companyemail_items', to='relationships.Company')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companyemail_items', related_query_name='companyemail_items', to='relationships.Email')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companyemail_items', related_query_name='companyemail_items', to='relationships.CompanyEmailType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_md', models.TextField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companyaddress_items', related_query_name='companyaddress_items', to='relationships.Address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companyaddress_items', related_query_name='companyaddress_items', to='relationships.Company')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companyaddress_items', related_query_name='companyaddress_items', to='relationships.CompanyAddressType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='addresses',
            field=models.ManyToManyField(related_name='companies', related_query_name='companies', through='relationships.CompanyAddress', to='relationships.Address'),
        ),
        migrations.AddField(
            model_name='company',
            name='emails',
            field=models.ManyToManyField(related_name='companies', related_query_name='companies', through='relationships.CompanyEmail', to='relationships.Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='links',
            field=models.ManyToManyField(related_name='companies', related_query_name='companies', through='relationships.CompanyLink', to='relationships.Link'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone_numbers',
            field=models.ManyToManyField(related_name='companies', related_query_name='companies', through='relationships.CompanyPhoneNumber', to='relationships.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='address',
            name='types',
            field=models.ManyToManyField(related_name='addresses', related_query_name='addresses', to='relationships.AddressType'),
        ),
    ]
