# Generated by Django 3.0.5 on 2020-10-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstype',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='addresstype',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='addresstype',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyaddresstype',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='companyaddresstype',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='companyaddresstype',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyemailtype',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='companyemailtype',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='companyemailtype',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companylinktype',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='companylinktype',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='companylinktype',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyphonenumbertype',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='companyphonenumbertype',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='companyphonenumbertype',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='linktype',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='linktype',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='linktype',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaddresstype',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personaddresstype',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personaddresstype',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personcompanytype',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personcompanytype',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personcompanytype',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personemailtype',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personemailtype',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personemailtype',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personlinktype',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personlinktype',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personlinktype',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personphonenumbertype',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personphonenumbertype',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personphonenumbertype',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phonenumbertype',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='phonenumbertype',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='phonenumbertype',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
