# Generated by Django 3.0.5 on 2020-10-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0002_auto_20201021_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='types',
        ),
        migrations.DeleteModel(
            name='LinkType',
        ),
    ]
