# Generated by Django 3.1.2 on 2021-04-19 03:34

from django.db import migrations, models
import django.db.models.deletion
import relationships.models

class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.ForeignKey(default=99501, on_delete=django.db.models.deletion.PROTECT, related_name='users', related_query_name='users', to='relationships.email'),
            preserve_default=False,
        ),
        # migrations.AddField(
        #     model_name='user',
        #     name='key',
        #     field=models.CharField(db_index=True, default=relationships.models.get_user_key, max_length=16, unique=True),
        # ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(db_index=True, default='noname', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='users', related_query_name='users', to='relationships.phonenumber'),
            preserve_default=False,
        ),
    ]
