# Generated by Django 3.1.2 on 2021-11-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0002_auto_20211129_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumberhash',
            name='link_type',
        ),
    ]
