# Generated by Django 3.1.2 on 2021-04-19 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0003_auto_20210419_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessedURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('first_accessed', models.DateTimeField(db_index=True)),
                ('last_accessed', models.DateTimeField(db_index=True)),
                ('count', models.IntegerField(db_index=True)),
                ('url', models.URLField(db_index=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessed_urls', related_query_name='accessed_urls', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserIPDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('first_accessed', models.DateTimeField(db_index=True)),
                ('last_accessed', models.DateTimeField(db_index=True)),
                ('count', models.IntegerField(db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('is_mobile', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_tablet', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_touch_capable', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_pc', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_bot', models.BooleanField(blank=True, db_index=True, null=True)),
                ('browser', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('browser_family', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('browser_version', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('browser_version_string', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('os', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('os_version', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('os_version_string', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('device', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('device_family', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('accessed_urls', models.ManyToManyField(db_index=True, related_name='user_ip_devices', related_query_name='user_ip_devices', to='relationships.AccessedURL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ip_devices', related_query_name='ip_devices', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
