# Generated by Django 3.0.5 on 2020-10-12 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0003_auto_20201008_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaddress',
            name='details_md',
            field=models.TextField(verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='companyemail',
            name='details_md',
            field=models.TextField(verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='companylink',
            name='details_md',
            field=models.TextField(verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='companyphonenumber',
            name='details_md',
            field=models.TextField(verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personaddress',
            name='details_md',
            field=models.TextField(verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personcompany',
            name='details_md',
            field=models.TextField(verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personemail',
            name='details_md',
            field=models.TextField(verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personlink',
            name='details_md',
            field=models.TextField(verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personlink',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_link_relationships', related_query_name='person_link_relationships', to='relationships.Link'),
        ),
        migrations.AlterField(
            model_name='personlink',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_link_relationships', related_query_name='person_link_relationships', to='relationships.Person'),
        ),
        migrations.AlterField(
            model_name='personlink',
            name='rtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_link_relationships', related_query_name='person_link_relationships', to='relationships.PersonLinkType', verbose_name='Person-link relationship type'),
        ),
        migrations.AlterField(
            model_name='personphonenumber',
            name='details_md',
            field=models.TextField(verbose_name='Details in Markdown'),
        ),
    ]
