# Generated by Django 3.1.2 on 2021-11-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0003_remove_phonenumberhash_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_buying_agent',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_direct_buyer',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_direct_seller',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
