# Generated by Django 3.0.5 on 2020-10-22 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0003_auto_20201021_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='last_visited_okay',
            new_name='verified',
        ),
    ]
