# Generated by Django 3.0.5 on 2020-10-12 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_auto_20201012_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', related_query_name='companies', to='relationships.Company'),
        ),
        migrations.AlterField(
            model_name='personcompany',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persons', related_query_name='persons', to='relationships.Person'),
        ),
        migrations.AlterField(
            model_name='personcompany',
            name='rtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_company_relationships', related_query_name='person_company_relationships', to='relationships.PersonCompanyType', verbose_name='Person-company relationship type'),
        ),
    ]
