# Generated by Django 3.1.2 on 2021-12-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0005_auto_20211203_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_selling_agent',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
