# Generated by Django 3.0.5 on 2020-10-12 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0005_auto_20201012_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaddress',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_address_relationships', related_query_name='person_address_relationships', to='relationships.Address'),
        ),
        migrations.AlterField(
            model_name='personaddress',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_address_relationships', related_query_name='person_address_relationships', to='relationships.Person'),
        ),
        migrations.AlterField(
            model_name='personaddress',
            name='rtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_address_relationships', related_query_name='person_address_relationships', to='relationships.PersonAddressType', verbose_name='Person-address relationship type'),
        ),
    ]
