# Generated by Django 3.1.2 on 2021-04-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0005_auto_20210419_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
