# Generated by Django 3.1.2 on 2021-04-20 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0005_auto_20210419_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('display_name', models.CharField(db_index=True, max_length=200)),
                ('notes', models.TextField()),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', related_query_name='products', to='relationships.producttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('popularity', models.FloatField(db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', related_query_name='companies', to='relationships.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', related_query_name='products', to='relationships.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
