# Generated by Django 3.1.2 on 2020-11-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0006_auto_20201025_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyaddress',
            options={'verbose_name': 'Company-address relationship', 'verbose_name_plural': 'Company-addresse relationships'},
        ),
        migrations.AlterModelOptions(
            name='companyemail',
            options={'verbose_name': 'Company-email relationship', 'verbose_name_plural': 'Company-email relationships'},
        ),
        migrations.AlterModelOptions(
            name='companylink',
            options={'verbose_name': 'Company-link relationship', 'verbose_name_plural': 'Company-link relationships'},
        ),
        migrations.AlterModelOptions(
            name='companyphonenumber',
            options={'verbose_name': 'Company-phonenumber relationship', 'verbose_name_plural': 'Company-phonenumber relationships'},
        ),
        migrations.AlterModelOptions(
            name='personaddress',
            options={'verbose_name': 'Person-address relationship', 'verbose_name_plural': 'Person-address relationships'},
        ),
        migrations.AlterModelOptions(
            name='personcompany',
            options={'verbose_name': 'Person-company relationship', 'verbose_name_plural': 'Person-company relationships'},
        ),
        migrations.AlterModelOptions(
            name='personemail',
            options={'verbose_name': 'Person-email relationship', 'verbose_name_plural': 'Person-email relationships'},
        ),
        migrations.AlterModelOptions(
            name='personphonenumber',
            options={'verbose_name': 'Person-phonenumber relationship', 'verbose_name_plural': 'Person-phonenumber relationships'},
        ),
    ]
