# Generated by Django 3.1.2 on 2022-01-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0006_auto_20211212_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragent',
            name='is_routable',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
