# Generated by Django 3.1.2 on 2021-04-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0006_auto_20210420_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='notes',
            field=models.TextField(db_index=True),
        ),
    ]
