# Generated by Django 3.1.2 on 2022-01-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0007_useragent_is_routable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='useragent',
            unique_together=set(),
        ),
    ]
