# Generated by Django 3.1.2 on 2021-04-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0007_auto_20210420_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='product_types',
            field=models.ManyToManyField(db_index=True, related_name='companies', related_query_name='companies', through='relationships.CompanyProductType', to='relationships.ProductType'),
        ),
    ]
