# Generated by Django 3.0.5 on 2020-10-12 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0007_auto_20201012_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personemail',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_email_relationships', related_query_name='person_email_relationships', to='relationships.Email'),
        ),
        migrations.AlterField(
            model_name='personemail',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_email_relationships', related_query_name='person_email_relationships', to='relationships.Person'),
        ),
        migrations.AlterField(
            model_name='personemail',
            name='rtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_email_relationships', related_query_name='person_email_relationships', to='relationships.PersonEmailType', verbose_name='Person-email relationship type'),
        ),
    ]
