# Generated by Django 3.1.2 on 2021-04-20 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0008_auto_20210420_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('display_name', models.CharField(db_index=True, max_length=200)),
                ('notes', models.TextField(db_index=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_specifications', related_query_name='product_specifications', to='relationships.producttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
