# Generated by Django 3.1.2 on 2022-01-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0008_auto_20220126_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goods_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
