# Generated by Django 3.0.5 on 2020-10-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0008_auto_20201012_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personphonenumber',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_phonenumber_relationships', related_query_name='person_phonenumber_relationships', to='relationships.Person'),
        ),
        migrations.AlterField(
            model_name='personphonenumber',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_phonenumber_relationships', related_query_name='person_phonenumber_relationships', to='relationships.PhoneNumber'),
        ),
    ]
