# Generated by Django 3.1.2 on 2022-01-27 15:10

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0008_auto_20220126_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='search_agents_veccol',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_agents_veccol'], name='relationshi_search__7ed234_gin'),
        ),
    ]
