# Generated by Django 3.1.2 on 2020-11-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0009_auto_20201106_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(db_index=True),
        ),
    ]
