# Generated by Django 3.1.2 on 2022-01-28 03:20

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0010_manual_search_agents_veccol'),
    ]

    # This operation was previously faked so we can use the defined field on the ORM without actually adding a search vector field column
    # (it was added as a generated column in the last migration). It does not work because Django will attempt to write to the generated
    # column when we create a new entry. The solution is to annotate the field whenever we need it.
    operations = [
        # migrations.AddField(
        #     model_name='user',
        #     name='search_agents_veccol',
        #     field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        # ),
    ]
