# Generated by Django 3.0.5 on 2020-10-13 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0010_auto_20201012_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylink',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_link_relationships', related_query_name='company_link_relationships', to='relationships.Company'),
        ),
        migrations.AlterField(
            model_name='companylink',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_link_relationships', related_query_name='company_link_relationships', to='relationships.Link'),
        ),
        migrations.AlterField(
            model_name='companylink',
            name='rtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_link_relationships', related_query_name='company_link_relationships', to='relationships.CompanyLinkType', verbose_name='Company-link relationship type'),
        ),
    ]
