# Generated by Django 3.1.2 on 2022-01-28 03:20

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0010_manual_search_agents_veccol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='search_agents_veccol',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
