# Generated by Django 3.1.2 on 2021-04-20 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0011_auto_20210420_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('is_exists', models.BooleanField(db_index=True)),
                ('value', models.FloatField(db_index=True)),
                ('demand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_specifications', related_query_name='product_specifications', to='relationships.demand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_specifications', related_query_name='product_specifications', to='relationships.product')),
                ('product_specification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_specifications', related_query_name='product_specifications', to='relationships.productspecificationtype')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_specifications', related_query_name='product_specifications', to='relationships.supply')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
