# Generated by Django 3.1.2 on 2022-01-28 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0011_user_search_agents_veccol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('body', models.TextField()),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('commentee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments_with_this_user_as_commentee', related_query_name='comments_with_this_user_as_commentee', to='relationships.user')),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments_with_this_user_as_commentor', related_query_name='comments_with_this_user_as_commentor', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
