# Generated by Django 3.0.5 on 2020-10-13 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0012_auto_20201013_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyphonenumber',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_phonenumber_relationships', related_query_name='company_phonenumber_relationships', to='relationships.Company'),
        ),
        migrations.AlterField(
            model_name='companyphonenumber',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_phonenumber_relationships', related_query_name='company_phonenumber_relationships', to='relationships.PhoneNumber'),
        ),
        migrations.AlterField(
            model_name='companyphonenumber',
            name='rtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_phonenumber_relationships', related_query_name='company_phonenumber_relationships', to='relationships.CompanyPhoneNumberType', verbose_name='Company-phonenumber relationship type'),
        ),
    ]
