# Generated by Django 3.1.2 on 2022-01-30 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_agents', related_query_name='user_agents', to='relationships.user'),
        ),
    ]
