# Generated by Django 3.1.2 on 2021-04-21 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('payments', '0002_auto_20210421_1633'),
        ('relationships', '0013_auto_20210420_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('entered', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('price', models.FloatField(blank=True, db_index=True, null=True)),
                ('total_quantity', models.FloatField(blank=True, db_index=True, null=True)),
                ('moq_quantity', models.FloatField(blank=True, db_index=True, null=True)),
                ('delivery_interval_quantity', models.FloatField(blank=True, db_index=True, null=True)),
                ('delivery_interval_count', models.IntegerField(blank=True, db_index=True, null=True)),
                ('delivery_interval_length', models.IntegerField(blank=True, db_index=True, null=True)),
                ('delivery_interval_uom', models.CharField(blank=True, choices=[('d', 'Day'), ('w', 'Week'), ('m', 'Month'), ('y', 'Year')], db_index=True, max_length=2, null=True)),
                ('commission_percentage_sales', models.FloatField(blank=True, db_index=True, null=True)),
                ('commission_amount', models.FloatField(blank=True, db_index=True, null=True)),
                ('commission_amount_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandquote_commission_amount_currencies', related_query_name='demandquote_commission_amount_currencies', to='payments.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncotermAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
                ('plural_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_of_measures', related_query_name='unit_of_measures', to='relationships.producttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplyQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('entered', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('price', models.FloatField(blank=True, db_index=True, null=True)),
                ('total_quantity', models.FloatField(blank=True, db_index=True, null=True)),
                ('moq_quantity', models.FloatField(blank=True, db_index=True, null=True)),
                ('delivery_interval_quantity', models.FloatField(blank=True, db_index=True, null=True)),
                ('delivery_interval_count', models.IntegerField(blank=True, db_index=True, null=True)),
                ('delivery_interval_length', models.IntegerField(blank=True, db_index=True, null=True)),
                ('delivery_interval_uom', models.CharField(blank=True, choices=[('d', 'Day'), ('w', 'Week'), ('m', 'Month'), ('y', 'Year')], db_index=True, max_length=2, null=True)),
                ('commission_percentage_sales', models.FloatField(blank=True, db_index=True, null=True)),
                ('commission_amount', models.FloatField(blank=True, db_index=True, null=True)),
                ('commission_amount_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplyquote_commission_amount_currencies', related_query_name='supplyquote_commission_amount_currencies', to='payments.currency')),
                ('commission_amount_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplyquote_commission_amount_uom', related_query_name='supplyquote_commission_amount_uom', to='relationships.unitofmeasure')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplyquote_currencies', related_query_name='supplyquote_currencies', to='payments.currency')),
                ('delivery_interval_quantity_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplyquote_delivery_interval_quantity_uoms', related_query_name='supplyquote_delivery_interval_quantity_uoms', to='relationships.unitofmeasure')),
                ('incoterm_availability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplyquote_incoterm_availabilities', related_query_name='supplyquote_incoterm_availabilities', to='relationships.incotermavailability')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplyquote_locations', related_query_name='supplyquote_locations', to='relationships.location')),
                ('moq_quantity_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplyquote_moq_quantity_uoms', related_query_name='supplyquote_moq_quantity_uoms', to='relationships.unitofmeasure')),
                ('price_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplyquote_price_uoms', related_query_name='supplyquote_price_uoms', to='relationships.unitofmeasure')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_quotes', related_query_name='supply_quotes', to='relationships.unitofmeasure')),
                ('total_quantity_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplyquote_total_quantity_uoms', related_query_name='supplyquote_total_quantity_uoms', to='relationships.unitofmeasure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
                ('demand_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_terms', related_query_name='payment_terms', to='relationships.demandquote')),
                ('supply_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_terms', related_query_name='payment_terms', to='relationships.supplyquote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('base_quantity', models.FloatField(db_index=True)),
                ('base_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_base_uoms', related_query_name='packing_base_uoms', to='relationships.unitofmeasure')),
                ('demand_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packings', related_query_name='packings', to='relationships.demandquote')),
                ('pack_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_pack_uom', related_query_name='packing_pack_uom', to='relationships.unitofmeasure')),
                ('supply_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packings', related_query_name='packings', to='relationships.supplyquote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExcludedPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
                ('demand_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excluded_prices', related_query_name='excluded_prices', to='relationships.demandquote')),
                ('supply_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excluded_prices', related_query_name='excluded_prices', to='relationships.supplyquote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='demandquote',
            name='commission_amount_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandquote_commission_amount_uom', related_query_name='demandquote_commission_amount_uom', to='relationships.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='demandquote',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandquote_currencies', related_query_name='demandquote_currencies', to='payments.currency'),
        ),
        migrations.AddField(
            model_name='demandquote',
            name='delivery_interval_quantity_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandquote_delivery_interval_quantity_uoms', related_query_name='demandquote_delivery_interval_quantity_uoms', to='relationships.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='demandquote',
            name='demand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_quotes', related_query_name='demand_quotes', to='relationships.demand'),
        ),
        migrations.AddField(
            model_name='demandquote',
            name='incoterm_availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandquote_incoterm_availabilities', related_query_name='demandquote_incoterm_availabilities', to='relationships.incotermavailability'),
        ),
        migrations.AddField(
            model_name='demandquote',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandquote_locations', related_query_name='demandquote_locations', to='relationships.location'),
        ),
        migrations.AddField(
            model_name='demandquote',
            name='moq_quantity_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandquote_moq_quantity_uoms', related_query_name='demandquote_moq_quantity_uoms', to='relationships.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='demandquote',
            name='price_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandquote_price_uoms', related_query_name='demandquote_price_uoms', to='relationships.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='demandquote',
            name='total_quantity_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandquote_total_quantity_uoms', related_query_name='demandquote_total_quantity_uoms', to='relationships.unitofmeasure'),
        ),
    ]
