# Generated by Django 3.0.5 on 2020-10-13 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0013_auto_20201013_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_email_relationships', related_query_name='company_email_relationships', to='relationships.Company'),
        ),
        migrations.AlterField(
            model_name='companyemail',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_email_relationships', related_query_name='company_email_relationships', to='relationships.Email'),
        ),
        migrations.AlterField(
            model_name='companyemail',
            name='rtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_email_relationships', related_query_name='company_email_relationships', to='relationships.CompanyEmailType', verbose_name='Company-email relationship type'),
        ),
    ]
