# Generated by Django 3.0.5 on 2020-10-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0014_auto_20201013_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='notes_md',
            field=models.TextField(blank=True, null=True, verbose_name='Notes in Markdown'),
        ),
    ]
