# Generated by Django 3.1.2 on 2021-04-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0014_auto_20210421_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incotermavailability',
            options={'verbose_name': 'Incoterm/Availability', 'verbose_name_plural': 'Incoterms/Availabilities'},
        ),
    ]
