# Generated by Django 3.1.2 on 2022-02-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0014_auto_20220206_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logintoken',
            name='expiry_secs',
        ),
        migrations.RemoveField(
            model_name='logintoken',
            name='refreshed',
        ),
        migrations.AddField(
            model_name='logintoken',
            name='killed',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
