# Generated by Django 3.1.2 on 2020-11-10 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20201109_1500'),
        ('relationships', '0014_invalidemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emails', related_query_name='emails', to='common.importjob'),
        ),
        migrations.AlterField(
            model_name='invalidemail',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invalid_emails', related_query_name='invalid_emails', to='common.importjob'),
        ),
    ]
