# Generated by Django 3.0.5 on 2020-10-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0015_auto_20201013_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='notes_md',
            field=models.TextField(verbose_name='Notes in Markdown'),
        ),
    ]
