# Generated by Django 3.1.2 on 2020-11-16 07:24

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0015_auto_20201110_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=common.models.LowerCaseEmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='invalidemail',
            name='email',
            field=common.models.LowerCaseCharField(db_index=True, max_length=100, unique=True),
        ),
    ]
