# Generated by Django 3.1.2 on 2021-04-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0015_auto_20210421_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyquote',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_quotes', related_query_name='supply_quotes', to='relationships.supply'),
        ),
    ]
