# Generated by Django 3.0.5 on 2020-10-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0016_auto_20201013_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='last_visited_okay',
            field=models.DateTimeField(default=None),
        ),
    ]
