# Generated by Django 3.1.2 on 2021-04-21 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0016_auto_20210421_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='is_exists',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_specifications', related_query_name='product_specifications', to='relationships.product'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
