# Generated by Django 3.1.2 on 2020-11-20 04:56

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0016_auto_20201116_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invalidemail',
            name='email',
            field=common.models.LowerCaseCharField(db_index=True, max_length=500, unique=True),
        ),
    ]
