# Generated by Django 3.1.2 on 2022-02-11 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0016_auto_20220211_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('body', models.TextField()),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_reviews_with_this_user_as_reviewee', related_query_name='user_reviews_with_this_user_as_reviewee', to='relationships.user')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_reviewees', related_query_name='user_reviewees', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
