# Generated by Django 3.1.2 on 2020-11-20 05:04

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0017_auto_20201120_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invalidemail',
            name='email',
            field=common.models.LowerCaseCharField(db_index=True, max_length=1000, unique=True),
        ),
    ]
