# Generated by Django 3.1.2 on 2021-04-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0017_auto_20210421_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecificationtype',
            name='notes',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
