# Generated by Django 3.0.5 on 2020-10-13 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20201008_1255'),
        ('relationships', '0017_auto_20201013_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companyaddress',
            options={'verbose_name': 'Company-address', 'verbose_name_plural': 'Company-addresses'},
        ),
        migrations.AlterModelOptions(
            name='companyaddresstype',
            options={'verbose_name': 'Company-address type', 'verbose_name_plural': 'Company-address types'},
        ),
        migrations.AlterModelOptions(
            name='companyemail',
            options={'verbose_name': 'Company-email', 'verbose_name_plural': 'Company-emails'},
        ),
        migrations.AlterModelOptions(
            name='companyemailtype',
            options={'verbose_name': 'Company-email type', 'verbose_name_plural': 'Company-email types'},
        ),
        migrations.AlterModelOptions(
            name='companylink',
            options={'verbose_name': 'Company-link', 'verbose_name_plural': 'Company-links'},
        ),
        migrations.AlterModelOptions(
            name='companylinktype',
            options={'verbose_name': 'Company-link type', 'verbose_name_plural': 'Company-link types'},
        ),
        migrations.AlterModelOptions(
            name='companyphonenumber',
            options={'verbose_name': 'Company-phonenumber', 'verbose_name_plural': 'Company-phonenumbers'},
        ),
        migrations.AlterModelOptions(
            name='companyphonenumbertype',
            options={'verbose_name': 'Company-phonenumber types', 'verbose_name_plural': 'Company-phonenumber types'},
        ),
        migrations.AlterModelOptions(
            name='personaddress',
            options={'verbose_name': 'Person-address', 'verbose_name_plural': 'Person-addresses'},
        ),
        migrations.AlterModelOptions(
            name='personaddresstype',
            options={'verbose_name': 'Person-address type', 'verbose_name_plural': 'Person-address types'},
        ),
        migrations.AlterModelOptions(
            name='personcompany',
            options={'verbose_name': 'Person-company', 'verbose_name_plural': 'Person-companies'},
        ),
        migrations.AlterModelOptions(
            name='personcompanytype',
            options={'verbose_name': 'Person-company type', 'verbose_name_plural': 'Person-company types'},
        ),
        migrations.AlterModelOptions(
            name='personemail',
            options={'verbose_name': 'Person-email', 'verbose_name_plural': 'Person-emails'},
        ),
        migrations.AlterModelOptions(
            name='personemailtype',
            options={'verbose_name': 'Person-email type', 'verbose_name_plural': 'Person-email types'},
        ),
        migrations.AlterModelOptions(
            name='personlink',
            options={'verbose_name': 'Person-link', 'verbose_name_plural': 'Person-links'},
        ),
        migrations.AlterModelOptions(
            name='personlinktype',
            options={'verbose_name': 'Person-link type', 'verbose_name_plural': 'Person-link types'},
        ),
        migrations.AlterModelOptions(
            name='personphonenumber',
            options={'verbose_name': 'Person-phonenumber', 'verbose_name_plural': 'Person-phonenumbers'},
        ),
        migrations.AlterModelOptions(
            name='personphonenumbertype',
            options={'verbose_name': 'Person-phonenumber type', 'verbose_name_plural': 'Person-phonenumber types'},
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persons', related_query_name='persons', to='common.Country'),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persons', related_query_name='persons', to='common.State'),
        ),
    ]
