# Generated by Django 3.1.2 on 2022-02-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0017_auto_20220211_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='is_relevant',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
