# Generated by Django 3.1.2 on 2022-02-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0018_userreview_is_relevant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='is_relevant',
            field=models.BooleanField(db_index=True),
        ),
    ]
