# Generated by Django 3.1.2 on 2021-04-21 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0018_auto_20210421_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproduct',
            name='popularity',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demand_leads', related_query_name='demand_leads', to='relationships.company'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demand_leads', related_query_name='demand_leads', to='relationships.product'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_leads', related_query_name='supply_leads', to='relationships.company'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_leads', related_query_name='supply_leads', to='relationships.product'),
        ),
    ]
