# Generated by Django 3.0.5 on 2020-10-13 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20201008_1255'),
        ('relationships', '0018_auto_20201013_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', related_query_name='addresses', to='common.Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', related_query_name='addresses', to='common.State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='addresses', related_query_name='addresses', to='relationships.AddressType'),
        ),
        migrations.AlterField(
            model_name='company',
            name='notes_md',
            field=models.TextField(blank=True, null=True, verbose_name='Notes in Markdown'),
        ),
        migrations.AlterField(
            model_name='link',
            name='last_visited_okay',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='links', related_query_name='links', to='relationships.LinkType'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='phone_numbers', related_query_name='phone_numbers', to='relationships.PhoneNumber'),
        ),
    ]
