# Generated by Django 3.1.2 on 2022-02-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0019_auto_20220211_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_reviews', related_query_name='user_reviews', to='relationships.user'),
        ),
        migrations.CreateModel(
            name='UserDetailView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('reviews_view_count', models.IntegerField(db_index=True, default=0)),
                ('leads_view_count', models.IntegerField(db_index=True, default=0)),
                ('viewee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_detail_views', related_query_name='user_detail_views', to='relationships.user')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_detail_views_with_this_user_as_viewer', related_query_name='user_detail_views_with_this_user_as_viewer', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
