# Generated by Django 3.1.2 on 2021-04-21 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0019_auto_20210421_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandquote',
            name='entered',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplyquote',
            name='entered',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
