# Generated by Django 3.1.2 on 2020-12-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0019_auto_20201210_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
    ]
