# Generated by Django 3.1.2 on 2020-12-10 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0020_company_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('start', models.DateTimeField(db_index=True)),
                ('invalidated', models.DateTimeField(blank=True, db_index=True, default=True, null=True)),
                ('reason_md', models.TextField(blank=True, null=True, verbose_name='Reason in Markdown')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='black_list_entries', related_query_name='black_list_entries', to='relationships.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
