# Generated by Django 3.1.2 on 2021-04-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0020_auto_20210421_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
