# Generated by Django 3.1.2 on 2021-04-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0021_auto_20210421_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproducttype',
            name='popularity',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
