# Generated by Django 3.0.5 on 2020-10-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0021_auto_20201014_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
