# Generated by Django 3.1.2 on 2022-02-12 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0021_user_about_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about_me',
        ),
    ]
