# Generated by Django 3.1.2 on 2021-04-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0022_auto_20210421_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessedurl',
            name='url',
            field=models.URLField(db_index=True, verbose_name='URL'),
        ),
    ]
