# Generated by Django 3.1.2 on 2022-02-14 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_auto_20220212_1119'),
        ('relationships', '0022_remove_user_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('body', models.TextField()),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_comments_as_commentor', related_query_name='lead_comments_as_commentor', to='relationships.user')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_comments', related_query_name='lead_comments', to='leads.lead')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', related_query_name='replies', to='relationships.leadcomment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('body', models.TextField()),
                ('commentee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_comments_as_commentee', related_query_name='user_comments_as_commentee', to='relationships.user')),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_comments_as_commentor', related_query_name='user_comments_as_commentor', to='relationships.user')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', related_query_name='replies', to='relationships.usercomment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
