# Generated by Django 3.0.5 on 2020-10-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0022_auto_20201014_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_name_wo_postfix',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
