# Generated by Django 3.1.2 on 2021-04-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0023_auto_20210421_2304'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessedurl',
            unique_together={('user', 'url')},
        ),
        migrations.AlterIndexTogether(
            name='accessedurl',
            index_together={('user', 'url')},
        ),
    ]
