# Generated by Django 3.1.2 on 2020-12-10 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0023_auto_20201210_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListReasonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('details_md', models.TextField(blank=True, null=True, verbose_name='Details in Markdown')),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details_md', models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blacklistentry',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='black_list_entries', related_query_name='black_list_entries', to='relationships.blacklistreasontype'),
        ),
    ]
