# Generated by Django 3.1.2 on 2022-02-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0023_auto_20220214_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintoken',
            name='is_not_latest',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
