# Generated by Django 3.0.5 on 2020-10-14 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20201008_1255'),
        ('relationships', '0023_company_company_name_wo_postfix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', related_query_name='addresses', to='common.Country'),
            preserve_default=False,
        ),
    ]
