# Generated by Django 3.0.5 on 2020-10-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0024_auto_20201014_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='country_code',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='national_number',
            field=models.PositiveIntegerField(),
        ),
    ]
