# Generated by Django 3.1.2 on 2021-04-22 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0024_auto_20210421_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('buyer_sent', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('seller_sent', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('connected', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('demand_quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', related_query_name='matches', to='relationships.demandquote')),
                ('supply_quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', related_query_name='matches', to='relationships.supplyquote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
