# Generated by Django 3.1.2 on 2022-02-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0024_logintoken_is_not_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='registertoken',
            name='is_not_latest',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
