# Generated by Django 3.1.2 on 2022-02-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0025_registertoken_is_not_latest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_buying_agent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_direct_buyer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_direct_seller',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_selling_agent',
        ),
    ]
