# Generated by Django 3.1.2 on 2021-04-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0025_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
    ]
