# Generated by Django 3.1.2 on 2020-12-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0026_auto_20201210_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.RemoveField(
            model_name='person',
            name='state',
        ),
    ]
