# Generated by Django 3.1.2 on 2021-04-22 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0026_auto_20210422_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationProductSpecificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('purpose', models.CharField(choices=[('i', 'Import'), ('e', 'Export')], db_index=True, max_length=2)),
                ('is_exists', models.BooleanField(blank=True, db_index=True, null=True)),
                ('value', models.FloatField(blank=True, db_index=True, null=True)),
                ('operator', models.CharField(choices=[('>', 'Import'), ('<', 'Export'), ('>=', 'Export'), ('<=', 'Export'), ('==', 'Export')], db_index=True, max_length=2)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', related_query_name='matches', to='relationships.location')),
                ('product_specification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', related_query_name='matches', to='relationships.productspecificationtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
