# Generated by Django 3.1.2 on 2022-02-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0026_auto_20220224_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_agent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
