# Generated by Django 3.1.2 on 2022-02-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0027_auto_20220224_1856')
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                ALTER TABLE relationships_user DROP COLUMN search_agents_veccol CASCADE;
            '''
        ),
    ]
