# Generated by Django 3.1.2 on 2020-12-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0027_auto_20201210_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistreasontype',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='companyaddresstype',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='companyemail',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='companyemailtype',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='companylink',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='companylinktype',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='companyphonenumber',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='companyphonenumbertype',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personaddress',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personaddresstype',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personcompany',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personcompanytype',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personemail',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personemailtype',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personlink',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personlinktype',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personphonenumber',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='personphonenumbertype',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='phonenumbertype',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
    ]
