# Generated by Django 3.1.2 on 2021-04-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0027_locationproductspecificationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationproductspecificationtype',
            name='operator',
            field=models.CharField(blank=True, choices=[('>', 'Greater Than (>)'), ('<', 'Less Than (<)'), ('>=', 'Greater Than or Equal To (>=)'), ('<=', 'Less Than or Equal To (<=)'), ('==', 'Equal To (==)')], db_index=True, max_length=2, null=True),
        ),
    ]
