# Generated by Django 3.1.2 on 2022-02-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0028_drop_search_agents_veccol_20220224_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='buy_agent_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_company',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_buy_agent',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_logistics_agent',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sell_agent',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='logistics_agent_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='search_appearance_count',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='search_to_user_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='sell_agent_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
