# Generated by Django 3.1.2 on 2021-04-27 04:00

from django.db import migrations, models
import django.db.models.deletion
import relationships.models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0028_auto_20210422_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='country_code',
            field=models.CharField(db_index=True, default=None, max_length=50, validators=[relationships.models.validate_country_code]),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='national_number',
            field=models.CharField(db_index=True, default=None, max_length=100, validators=[relationships.models.validate_national_number]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user', related_query_name='user', to='relationships.email'),
        ),
    ]
