# Generated by Django 3.1.2 on 2021-04-27 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0030_auto_20210427_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_product_types',
        ),
        migrations.AlterField(
            model_name='companyproducttype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_product_types', related_query_name='company_product_types', to='relationships.company'),
        ),
        migrations.AlterField(
            model_name='companyproducttype',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_product_types', related_query_name='company_product_types', to='relationships.producttype'),
        ),
    ]
