# Generated by Django 3.1.2 on 2020-12-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0032_auto_20201215_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='types',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='phone_numbers', related_query_name='phone_numbers', to='relationships.PhoneNumberType'),
        ),
    ]
