# Generated by Django 3.1.2 on 2021-04-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0033_auto_20210428_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='url',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
    ]
