# Generated by Django 3.1.2 on 2020-12-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0034_companywechatid_companywechatidtype_personwechatid_personwechatidtype_wechatid_wechatidtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatid',
            name='wechat_id',
            field=models.CharField(db_index=True, max_length=300, unique=True, verbose_name='WeChat ID'),
        ),
    ]
