# Generated by Django 3.1.2 on 2020-12-17 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0035_auto_20201215_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechatid',
            name='types',
        ),
        migrations.DeleteModel(
            name='WeChatIDType',
        ),
    ]
