# Generated by Django 3.1.2 on 2020-12-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0038_auto_20201217_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_1_cn',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Address 1 in Chinese'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_2_cn',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Address 2 in Chinese'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_3_cn',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Address 3 in Chinese'),
        ),
    ]
