# Generated by Django 3.1.2 on 2022-02-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0039_search_to_user_ratio_20220224_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetailview',
            old_name='reviews_view_count',
            new_name='comments_view_count',
        ),
    ]
