# Generated by Django 3.1.2 on 2021-05-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0040_auto_20210505_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productspecification',
            old_name='value',
            new_name='float_value',
        ),
        migrations.AddField(
            model_name='productspecification',
            name='string_value',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
