# Generated by Django 3.1.2 on 2021-05-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0041_auto_20210505_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(db_index=True, default='https://everybase.co', verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CompanyProductType',
        ),
    ]
