# Generated by Django 3.1.2 on 2020-12-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0041_auto_20201219_0010'),
    ]

    operations = [

    ]
