# Generated by Django 3.1.2 on 2022-02-28 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0042_company_name_vec_20220228_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('saved', models.DateTimeField(db_index=True)),
                ('savee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_users_savee', related_query_name='saved_users_savee', to='relationships.user')),
                ('saver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_users_saver', related_query_name='saved_users_saver', to='relationships.user')),
            ],
            options={
                'unique_together': {('saver', 'savee')},
            },
        ),
    ]
