# Generated by Django 3.1.2 on 2021-05-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0042_auto_20210506_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('popularity', models.FloatField(blank=True, db_index=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_product_types', related_query_name='company_product_types', to='relationships.company')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_product_types', related_query_name='company_product_types', to='relationships.producttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
