# Generated by Django 3.1.2 on 2020-12-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0042_auto_20201219_0017'),
    ]

    operations = [

    ]
