# Generated by Django 3.1.2 on 2020-12-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0043_auto_20201219_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='verified',
        ),
    ]
