# Generated by Django 3.1.2 on 2021-05-12 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0043_companyproducttype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopLevelDomain',
        ),
    ]
