# Generated by Django 3.1.2 on 2022-02-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0043_saveduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveduser',
            name='saved',
        ),
        migrations.AddField(
            model_name='saveduser',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
