# Generated by Django 3.1.2 on 2021-05-12 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0044_delete_topleveldomain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
