# Generated by Django 3.1.2 on 2022-03-03 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0044_auto_20220228_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', related_query_name='replies', to='relationships.leadcomment'),
        ),
    ]
