# Generated by Django 3.1.2 on 2021-05-12 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0045_delete_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationProductSpecificationType',
        ),
    ]
