# Generated by Django 3.1.2 on 2022-03-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0045_auto_20220303_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadComment',
        ),
    ]
