# Generated by Django 3.1.2 on 2022-03-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0046_delete_leadcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug_link',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='slug_tokens',
            field=models.TextField(blank=True, null=True),
        ),
    ]
