# Generated by Django 3.1.2 on 2021-05-12 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0047_auto_20210512_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
    ]
