# Generated by Django 3.1.2 on 2021-05-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('payments', '0008_auto_20210512_1203'),
        ('relationships', '0048_auto_20210512_1158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
