# Generated by Django 3.1.2 on 2022-03-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0048_populate_uuid_fields_20220309_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug_link',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
