# Generated by Django 3.1.2 on 2021-01-14 11:16

from django.db import migrations, models
import relationships.models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0049_auto_20210114_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(db_index=True, unique=True, validators=[relationships.models.validate_link_link]),
        ),
    ]
