# Generated by Django 3.1.2 on 2021-05-12 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0049_delete_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyquote',
            name='commission_amount_currency',
        ),
        migrations.RemoveField(
            model_name='supplyquote',
            name='commission_amount_uom',
        ),
        migrations.RemoveField(
            model_name='supplyquote',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='supplyquote',
            name='delivery_interval_quantity_uom',
        ),
        migrations.RemoveField(
            model_name='supplyquote',
            name='incoterm_availability',
        ),
        migrations.RemoveField(
            model_name='supplyquote',
            name='location',
        ),
        migrations.RemoveField(
            model_name='supplyquote',
            name='moq_quantity_uom',
        ),
        migrations.RemoveField(
            model_name='supplyquote',
            name='price_uom',
        ),
        migrations.RemoveField(
            model_name='supplyquote',
            name='supply',
        ),
        migrations.RemoveField(
            model_name='supplyquote',
            name='total_quantity_uom',
        ),
        migrations.RemoveField(
            model_name='excludedprice',
            name='demand_quote',
        ),
        migrations.RemoveField(
            model_name='excludedprice',
            name='supply_quote',
        ),
        migrations.RemoveField(
            model_name='packing',
            name='demand_quote',
        ),
        migrations.RemoveField(
            model_name='packing',
            name='supply_quote',
        ),
        migrations.RemoveField(
            model_name='paymentterm',
            name='demand_quote',
        ),
        migrations.RemoveField(
            model_name='paymentterm',
            name='supply_quote',
        ),
        migrations.DeleteModel(
            name='DemandQuote',
        ),
        migrations.DeleteModel(
            name='SupplyQuote',
        ),
    ]
