# Generated by Django 3.1.2 on 2022-03-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0049_auto_20220309_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', related_query_name='replies', to='relationships.usercomment'),
        ),
    ]
