# Generated by Django 3.1.2 on 2022-03-14 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0050_auto_20220310_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('commented_only', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('saved_only', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('connected_only', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('goods_string', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('languages', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('is_buy_agent', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('buy_agent_details', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('is_sell_agent', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('sell_agent_details', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('is_logistics_agent', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('logistics_agent_details', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_queries', related_query_name='user_queries', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
