# Generated by Django 3.1.2 on 2021-05-12 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0050_auto_20210512_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='company',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='product',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='demand',
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='supply',
        ),
        migrations.DeleteModel(
            name='Demand',
        ),
        migrations.DeleteModel(
            name='Supply',
        ),
    ]
