# Generated by Django 3.1.2 on 2022-03-15 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0051_userquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='saved_count',
        ),
    ]
