# Generated by Django 3.1.2 on 2021-05-12 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0051_auto_20210512_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcludedPrice',
        ),
    ]
