# Generated by Django 3.1.2 on 2021-05-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0052_delete_excludedprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packing',
            name='base_uom',
        ),
        migrations.RemoveField(
            model_name='packing',
            name='pack_uom',
        ),
        migrations.DeleteModel(
            name='UnitOfMeasure',
        ),
    ]
