# Generated by Django 3.1.2 on 2021-03-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0052_auto_20210325_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumbertype',
            name='details_md',
        ),
        migrations.AddField(
            model_name='phonenumbertype',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
