# Generated by Django 3.1.2 on 2021-05-12 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0053_auto_20210512_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Packing',
        ),
    ]
