# Generated by Django 3.1.2 on 2022-04-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0053_auto_20220408_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_buyer',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
