# Generated by Django 3.1.2 on 2022-04-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0054_auto_20220411_1136'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useragent',
            unique_together={('user', 'ip_address', 'is_routable', 'is_mobile', 'is_tablet', 'is_touch_capable', 'is_pc', 'is_bot', 'browser', 'browser_family', 'browser_version', 'browser_version_string', 'os', 'os_family', 'os_version', 'os_version_string', 'device', 'device_family')},
        ),
    ]
