# Generated by Django 3.1.2 on 2021-05-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0054_delete_packing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentTerm',
        ),
    ]
