# Generated by Django 3.1.2 on 2022-04-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0056_auto_20220418_1555'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                ALTER TABLE relationships_user DROP COLUMN company_name_vec CASCADE;
            '''
        )
    ]
