# Generated by Django 3.1.2 on 2021-05-12 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0056_delete_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncotermAvailability',
        ),
    ]
