# Generated by Django 3.1.2 on 2021-05-12 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0058_delete_productspecification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSpecificationType',
        ),
    ]
