# Generated by Django 3.1.2 on 2022-05-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0059_company_name_vec_20220421_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
