# Generated by Django 3.1.2 on 2021-05-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0059_delete_productspecificationtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyproduct',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='companyproducttype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyproducttype',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyProduct',
        ),
        migrations.DeleteModel(
            name='CompanyProductType',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
