# Generated by Django 3.1.2 on 2022-05-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0060_auto_20220501_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fb_profile',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
    ]
