# Generated by Django 3.1.2 on 2021-05-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0061_auto_20210512_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'availabilities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'matches'},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name_plural': 'supplies'},
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
