# Generated by Django 3.1.2 on 2022-05-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0063_auto_20220517_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='do_not_email',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
