# Generated by Django 3.1.2 on 2021-05-27 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_matchkeyword'),
        ('relationships', '0064_auto_20210516_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demands', related_query_name='demands', to='common.country'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demands', related_query_name='demands', to='common.state'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplies', related_query_name='supplies', to='common.country'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplies', related_query_name='supplies', to='common.state'),
        ),
    ]
