# Generated by Django 3.1.2 on 2022-05-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0064_auto_20220524_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_login_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_login_code_generated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_email_login',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_whatsapp_login',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_login_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_login_code_generated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
