# Generated by Django 3.1.2 on 2022-05-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0065_auto_20220525_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_insights',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
