# Generated by Django 3.1.2 on 2022-06-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0066_user_has_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_whatsapp',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
