# Generated by Django 3.1.2 on 2021-05-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0066_auto_20210527_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasure',
            name='priority',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
