# Generated by Django 3.1.2 on 2022-06-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20220301_2226'),
        ('relationships', '0067_user_enable_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avatar_for_users', related_query_name='avatar_for_users', to='files.file'),
        ),
    ]
