# Generated by Django 3.1.2 on 2021-06-09 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0068_auto_20210527_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user', related_query_name='user', to='relationships.phonenumber'),
        ),
    ]
