# Generated by Django 3.1.2 on 2022-07-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0068_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_login_code',
            new_name='email_code',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email_login_code_generated',
            new_name='email_code_generated',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_email_login',
            new_name='email_code_used',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='whatsapp_login_code',
            new_name='whatsapp_code',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='whatsapp_login_code_generated',
            new_name='whatsapp_code_generated',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_whatsapp_login',
            new_name='whatsapp_code_used',
        ),
        migrations.AddField(
            model_name='user',
            name='email_code_purpose',
            field=models.CharField(blank=True, choices=[('LOGIN', 'LOGIN'), ('UPDATE_EMAIL', 'UPDATE_EMAIL')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_code_purpose',
            field=models.CharField(blank=True, choices=[('LOGIN', 'LOGIN'), ('UPDATE_PHONE_NUMBER', 'UPDATE_PHONE_NUMBER')], db_index=True, max_length=20, null=True),
        ),
    ]
