# Generated by Django 3.1.2 on 2022-07-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0069_auto_20220707_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_cookie_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='LoginAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('cookie_uuid', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, choices=[('standard', 'Standard'), ('magic', 'Magic')], db_index=True, max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='login_actions', related_query_name='login_actions', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
