# Generated by Django 3.1.2 on 2021-06-11 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0069_auto_20210609_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply',
            old_name='preorder_timeframe',
            new_name='pre_order_timeframe',
        ),
        migrations.RenameField(
            model_name='supply',
            old_name='preorder_timeframe_captured',
            new_name='pre_order_timeframe_captured',
        ),
    ]
