# Generated by Django 3.1.2 on 2021-06-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0070_auto_20210611_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useripdevice',
            name='accessed_urls',
        ),
        migrations.RemoveField(
            model_name='useripdevice',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccessedURL',
        ),
        migrations.DeleteModel(
            name='UserIPDevice',
        ),
    ]
