# Generated by Django 3.1.2 on 2022-07-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0070_auto_20220714_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginaction',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard'), ('magic', 'Magic')], db_index=True, default='standard', max_length=20),
            preserve_default=False,
        ),
    ]
