# Generated by Django 3.1.2 on 2022-07-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0071_auto_20220714_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginaction',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('magic', 'Magic')], db_index=True, max_length=20),
        ),
    ]
