# Generated by Django 3.1.2 on 2021-06-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0072_phonenumberhash_phonenumberurlaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberurlaccess',
            name='os_family',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
