# Generated by Django 3.1.2 on 2022-07-20 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0072_auto_20220719_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLinkRedirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('uuid', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('next', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='magic_link_redirects', related_query_name='magic_link_redirects', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
