# Generated by Django 3.1.2 on 2021-06-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0073_phonenumberurlaccess_os_family'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumberhash',
            options={'verbose_name': 'Phone number hash', 'verbose_name_plural': 'Phone number hashes'},
        ),
        migrations.AlterModelOptions(
            name='phonenumberurlaccess',
            options={'verbose_name': 'Phone Number URL access', 'verbose_name_plural': 'Phone Number URL accesses'},
        ),
        migrations.AlterField(
            model_name='phonenumberurlaccess',
            name='accessed',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
