# Generated by Django 3.1.2 on 2022-07-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0073_magiclinkredirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug_link',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True),
        ),
    ]
