# Generated by Django 3.1.2 on 2022-09-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0074_auto_20220722_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='buy_agent_details',
        ),
        migrations.RemoveField(
            model_name='user',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='enable_whatsapp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fb_profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='goods_string',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='impressions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_buy_agent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_logistics_agent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_sell_agent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_seller',
        ),
        migrations.RemoveField(
            model_name='user',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='user',
            name='languages_string',
        ),
        migrations.RemoveField(
            model_name='user',
            name='logistics_agent_details',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sell_agent_details',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state_string',
        ),
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.CharField(db_index=True, default='', max_length=40),
        ),
    ]
