# Generated by Django 3.1.2 on 2022-04-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0075_auto_20220915_1106'),
    ]

    operations = [
        # migrations.RunSQL(
        #     sql='''
        #         ALTER TABLE relationships_user DROP COLUMN languages_string_vec CASCADE;
        #         ALTER TABLE relationships_user DROP COLUMN state_string_vec CASCADE;
        #         ALTER TABLE relationships_user DROP COLUMN buy_agent_details_vec CASCADE;
        #         ALTER TABLE relationships_user DROP COLUMN sell_agent_details_vec CASCADE;
        #         ALTER TABLE relationships_user DROP COLUMN logistics_details_vec CASCADE;
        #         ALTER TABLE relationships_user DROP COLUMN search_to_user_ratio CASCADE;
        #     '''
        # )
    ]
