# Generated by Django 3.1.2 on 2021-06-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0075_auto_20210617_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberlinkaccess',
            name='outcome',
            field=models.CharField(blank=True, choices=[('PHONE_NUMBER_ACCESS_SUCCESSFUL', 'PHONE_NUMBER_ACCESS_SUCCESSFUL'), ('PHONE_NUMBER_ACCESS', 'PHONE_NUMBER_ACCESS')], db_index=True, max_length=200, null=True),
        ),
    ]
