# Generated by Django 3.1.2 on 2022-09-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0076_manual_drop_unused_vec_20220915_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailview',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
