# Generated by Django 3.1.2 on 2021-06-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0076_phonenumberlinkaccess_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberhash',
            name='expired',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
