# Generated by Django 3.1.2 on 2022-09-15 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0078_auto_20220915_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('requirements', models.TextField()),
                ('is_buying', models.BooleanField(db_index=True)),
                ('is_selling', models.BooleanField(db_index=True)),
                ('is_need_commmission_agents', models.BooleanField(db_index=True)),
                ('is_commission_agent', models.BooleanField(db_index=True)),
                ('is_other', models.BooleanField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_requirements', related_query_name='user_requirements', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='magiclinkredirect',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registertoken',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='saveduser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='saveduser',
            name='savee',
        ),
        migrations.RemoveField(
            model_name='saveduser',
            name='saver',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='commentee',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='commentor',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='userquery',
            name='user',
        ),
        migrations.DeleteModel(
            name='LoginToken',
        ),
        migrations.DeleteModel(
            name='MagicLinkRedirect',
        ),
        migrations.DeleteModel(
            name='RegisterToken',
        ),
        migrations.DeleteModel(
            name='SavedUser',
        ),
        migrations.DeleteModel(
            name='UserComment',
        ),
        migrations.DeleteModel(
            name='UserQuery',
        ),
    ]
