# Generated by Django 3.1.2 on 2021-06-24 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0079_auto_20210620_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswerpair',
            old_name='asker',
            new_name='questioner',
        ),
    ]
