# Generated by Django 3.1.2 on 2022-09-15 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0080_relationships_vec_20220915_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('key_phrases', models.TextField()),
                ('is_buying', models.BooleanField(db_index=True)),
                ('is_selling', models.BooleanField(db_index=True)),
                ('is_need_commmission_agents', models.BooleanField(db_index=True)),
                ('is_commission_agent', models.BooleanField(db_index=True)),
                ('is_other', models.BooleanField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_alerts', related_query_name='user_alerts', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
