# Generated by Django 3.1.2 on 2021-06-24 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_auto_20210619_2101'),
        ('chat', '0098_auto_20210623_2246'),
        ('relationships', '0082_auto_20210624_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='buyer_bought_contact',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='buyer_confirmed_details',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='buyer_confirmed_details_correct',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='buyer_confirmed_details_correct_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_w_this_buyer_confirmed_details_correct_value', related_query_name='matches_w_this_buyer_confirmed_details_correct_value', to='chat.messagedatavalue'),
        ),
        migrations.AddField(
            model_name='match',
            name='buyer_confirmed_interest',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='buyer_confirmed_interest_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_w_this_buyer_confirmed_interest_value', related_query_name='matches_w_this_buyer_confirmed_interest_value', to='chat.messagedatavalue'),
        ),
        migrations.AddField(
            model_name='match',
            name='buyer_interested',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='buyer_payment_hash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_w_this_buyer_payment_hash', related_query_name='matches_w_this_buyer_payment_hash', to='payments.paymenthash'),
        ),
        migrations.AddField(
            model_name='match',
            name='buyer_stopped_discussion',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='buyer_stopped_discussion_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_w_this_buyer_stopped_discussion_value', related_query_name='matches_w_this_buyer_stopped_discussion_value', to='chat.messagedatavalue'),
        ),
        migrations.AddField(
            model_name='match',
            name='ready',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='seller_bought_contact',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='seller_confirmed_details',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='seller_confirmed_details_correct',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='seller_confirmed_details_correct_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_w_this_seller_confirmed_details_correct_value', related_query_name='matches_w_this_seller_confirmed_details_correct_value', to='chat.messagedatavalue'),
        ),
        migrations.AddField(
            model_name='match',
            name='seller_confirmed_interest',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='seller_confirmed_interest_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_w_this_seller_confirmed_value', related_query_name='matches_w_this_seller_confirmed_value', to='chat.messagedatavalue'),
        ),
        migrations.AddField(
            model_name='match',
            name='seller_interested',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='seller_payment_hash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_w_this_seller_payment_hash', related_query_name='matches_w_this_seller_payment_hash', to='payments.paymenthash'),
        ),
        migrations.AddField(
            model_name='match',
            name='seller_stopped_discussion',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='seller_stopped_discussion_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_w_this_seller_stopped_discussion_value', related_query_name='matches_w_this_seller_stopped_discussion_value', to='chat.messagedatavalue'),
        ),
        migrations.AddField(
            model_name='match',
            name='sent_buyer_confirm_interest',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='sent_buyer_confirm_interest_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_w_this_buyer_confirm_interest_value', related_query_name='matches_w_this_buyer_confirm_interest_value', to='chat.twiliooutboundmessage'),
        ),
        migrations.AddField(
            model_name='match',
            name='sent_contact_to_buyer',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='sent_contact_to_seller',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='sent_seller_confirm_interest',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='sent_seller_confirm_interest_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_w_this_seller_confirm_interest_message', related_query_name='matches_w_this_seller_confirm_interest_message', to='chat.twiliooutboundmessage'),
        ),
    ]
