# Generated by Django 3.1.2 on 2022-09-15 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0082_key_phrases_vec_20220915_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContactAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('whatsapp_body', models.TextField(null=True)),
                ('status', models.CharField(blank=True, choices=[('success', 'Success'), ('no_credits', 'No Credits')], db_index=True, max_length=20, null=True)),
                ('contactee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_contact_action_contactees', related_query_name='user_contact_action_contactees', to='relationships.user')),
                ('contactor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_contact_action_contactors', related_query_name='user_contact_action_contactors', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
