# Generated by Django 3.1.2 on 2022-09-15 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0083_usercontactaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('status', models.CharField(blank=True, choices=[('match', 'Match'), ('not_match', 'Not Match'), ('failed', 'Failed'), ('notified', 'Notified')], db_index=True, max_length=20, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_match_alerts', related_query_name='alert_match_alerts', to='relationships.alert')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_match_requirements', related_query_name='alert_match_requirements', to='relationships.requirement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
