# Generated by Django 3.1.2 on 2021-06-28 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0083_auto_20210624_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_qna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_w_this_as_current_qna', related_query_name='users_w_this_as_current_qna', to='relationships.questionanswerpair'),
        ),
    ]
