# Generated by Django 3.1.2 on 2022-09-15 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('relationships', '0084_alertmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('key_phrase', models.CharField(db_index=True, max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlertKeyPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_key_phrases', related_query_name='alert_key_phrases', to='relationships.alert')),
                ('key_phrase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_key_phrases', related_query_name='alert_key_phrases', to='relationships.keyphrase')),
            ],
        ),
        migrations.CreateModel(
            name='AlertExcludeCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_exclude_countries', related_query_name='alert_exclude_countries', to='relationships.alert')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_exclude_countries', related_query_name='alert_exclude_countries', to='common.country')),
            ],
        ),
    ]
