# Generated by Django 3.1.2 on 2021-06-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0084_user_current_qna'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_match_to_confirm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_w_this_as_current_match_to_confirm', related_query_name='users_w_this_as_current_match_to_confirm', to='relationships.match'),
        ),
    ]
