# Generated by Django 3.1.2 on 2022-09-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0085_alertexcludecountry_alertkeyphrase_keyphrase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='is_need_commmission_agents',
            new_name='is_need_commission_agents',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='is_need_commmission_agents',
            new_name='is_need_commission_agents',
        ),
    ]
