# Generated by Django 3.1.2 on 2021-07-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0086_auto_20210630_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_match_to_confirm',
        ),
        migrations.AddField(
            model_name='user',
            name='current_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_w_this_as_current_match', related_query_name='users_w_this_as_current_match', to='relationships.match'),
        ),
    ]
