# Generated by Django 3.1.2 on 2021-07-08 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0087_auto_20210701_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='next_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_versions_of_this_demand', related_query_name='previous_versions_of_this_demand', to='relationships.demand'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_versions_of_this_demand', related_query_name='next_versions_of_this_demand', to='relationships.demand'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='next_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_versions_of_this_supply', related_query_name='previous_versions_of_this_supply', to='relationships.supply'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_versions_of_this_supply', related_query_name='next_versions_of_this_supply', to='relationships.supply'),
        ),
    ]
