# Generated by Django 3.1.2 on 2021-07-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0088_auto_20210708_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='country_method',
            field=models.CharField(blank=True, choices=[('DATA_KEY_MATCH', 'DATA_KEY_MATCH'), ('MATCH_KEYWORD_TO_MODEL_MATCH', 'MATCH_KEYWORD_TO_MODEL_MATCH'), ('FREE_TEXT', 'FREE_TEXT'), ('NUMERIC_INPUT', 'NUMERIC_INPUT')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='currency_method',
            field=models.CharField(blank=True, choices=[('DATA_KEY_MATCH', 'DATA_KEY_MATCH'), ('MATCH_KEYWORD_TO_MODEL_MATCH', 'MATCH_KEYWORD_TO_MODEL_MATCH'), ('FREE_TEXT', 'FREE_TEXT'), ('NUMERIC_INPUT', 'NUMERIC_INPUT')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='packing_method',
            field=models.CharField(blank=True, choices=[('DATA_KEY_MATCH', 'DATA_KEY_MATCH'), ('MATCH_KEYWORD_TO_MODEL_MATCH', 'MATCH_KEYWORD_TO_MODEL_MATCH'), ('FREE_TEXT', 'FREE_TEXT'), ('NUMERIC_INPUT', 'NUMERIC_INPUT')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='price_method',
            field=models.CharField(blank=True, choices=[('DATA_KEY_MATCH', 'DATA_KEY_MATCH'), ('MATCH_KEYWORD_TO_MODEL_MATCH', 'MATCH_KEYWORD_TO_MODEL_MATCH'), ('FREE_TEXT', 'FREE_TEXT'), ('NUMERIC_INPUT', 'NUMERIC_INPUT')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='product_type_method',
            field=models.CharField(blank=True, choices=[('DATA_KEY_MATCH', 'DATA_KEY_MATCH'), ('MATCH_KEYWORD_TO_MODEL_MATCH', 'MATCH_KEYWORD_TO_MODEL_MATCH'), ('FREE_TEXT', 'FREE_TEXT'), ('NUMERIC_INPUT', 'NUMERIC_INPUT')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='quantity_method',
            field=models.CharField(blank=True, choices=[('DATA_KEY_MATCH', 'DATA_KEY_MATCH'), ('MATCH_KEYWORD_TO_MODEL_MATCH', 'MATCH_KEYWORD_TO_MODEL_MATCH'), ('FREE_TEXT', 'FREE_TEXT'), ('NUMERIC_INPUT', 'NUMERIC_INPUT')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='state_method',
            field=models.CharField(blank=True, choices=[('DATA_KEY_MATCH', 'DATA_KEY_MATCH'), ('MATCH_KEYWORD_TO_MODEL_MATCH', 'MATCH_KEYWORD_TO_MODEL_MATCH'), ('FREE_TEXT', 'FREE_TEXT'), ('NUMERIC_INPUT', 'NUMERIC_INPUT')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='accept_lc_method',
            field=models.CharField(blank=True, choices=[('DATA_KEY_MATCH', 'DATA_KEY_MATCH'), ('MATCH_KEYWORD_TO_MODEL_MATCH', 'MATCH_KEYWORD_TO_MODEL_MATCH'), ('FREE_TEXT', 'FREE_TEXT'), ('NUMERIC_INPUT', 'NUMERIC_INPUT')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='availability_method',
            field=models.CharField(blank=True, choices=[('DATA_KEY_MATCH', 'DATA_KEY_MATCH'), ('MATCH_KEYWORD_TO_MODEL_MATCH', 'MATCH_KEYWORD_TO_MODEL_MATCH'), ('FREE_TEXT', 'FREE_TEXT'), ('NUMERIC_INPUT', 'NUMERIC_INPUT')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='country_method',
            field=models.CharField(blank=True, choices=[('DATA_KEY_MATCH', 'DATA_KEY_MATCH'), ('MATCH_KEYWORD_TO_MODEL_MATCH', 'MATCH_KEYWORD_TO_MODEL_MATCH'), ('FREE_TEXT', 'FREE_TEXT'), ('NUMERIC_INPUT', 'NUMERIC_INPUT')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='currency_method',
            field=models.CharField(blank=True, choices=[('DATA_KEY_MATCH', 'DATA_KEY_MATCH'), ('MATCH_KEYWORD_TO_MODEL_MATCH', 'MATCH_KEYWORD_TO_MODEL_MATCH'), ('FREE_TEXT', 'FREE_TEXT'), ('NUMERIC_INPUT', 'NUMERIC_INPUT')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='deposit_percentage_method',
            field=models.CharField(blank=True, choices=[('DATA_KEY_MATCH', 'DATA_KEY_MATCH'), ('MATCH_KEYWORD_TO_MODEL_MATCH', 'MATCH_KEYWORD_TO_MODEL_MATCH'), ('FREE_TEXT', 'FREE_TEXT'), ('NUMERIC_INPUT', 'NUMERIC_INPUT')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='packing_method',
            field=models.CharField(blank=True, choices=[('DATA_KEY_MATCH', 'DATA_KEY_MATCH'), ('MATCH_KEYWORD_TO_MODEL_MATCH', 'MATCH_KEYWORD_TO_MODEL_MATCH'), ('FREE_TEXT', 'FREE_TEXT'), ('NUMERIC_INPUT', 'NUMERIC_INPUT')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='pre_order_timeframe_method',
            field=models.CharField(blank=True, choices=[('DATA_KEY_MATCH', 'DATA_KEY_MATCH'), ('MATCH_KEYWORD_TO_MODEL_MATCH', 'MATCH_KEYWORD_TO_MODEL_MATCH'), ('FREE_TEXT', 'FREE_TEXT'), ('NUMERIC_INPUT', 'NUMERIC_INPUT')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='price_method',
            field=models.CharField(blank=True, choices=[('DATA_KEY_MATCH', 'DATA_KEY_MATCH'), ('MATCH_KEYWORD_TO_MODEL_MATCH', 'MATCH_KEYWORD_TO_MODEL_MATCH'), ('FREE_TEXT', 'FREE_TEXT'), ('NUMERIC_INPUT', 'NUMERIC_INPUT')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='product_type_method',
            field=models.CharField(blank=True, choices=[('DATA_KEY_MATCH', 'DATA_KEY_MATCH'), ('MATCH_KEYWORD_TO_MODEL_MATCH', 'MATCH_KEYWORD_TO_MODEL_MATCH'), ('FREE_TEXT', 'FREE_TEXT'), ('NUMERIC_INPUT', 'NUMERIC_INPUT')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='quantity_method',
            field=models.CharField(blank=True, choices=[('DATA_KEY_MATCH', 'DATA_KEY_MATCH'), ('MATCH_KEYWORD_TO_MODEL_MATCH', 'MATCH_KEYWORD_TO_MODEL_MATCH'), ('FREE_TEXT', 'FREE_TEXT'), ('NUMERIC_INPUT', 'NUMERIC_INPUT')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='state_method',
            field=models.CharField(blank=True, choices=[('DATA_KEY_MATCH', 'DATA_KEY_MATCH'), ('MATCH_KEYWORD_TO_MODEL_MATCH', 'MATCH_KEYWORD_TO_MODEL_MATCH'), ('FREE_TEXT', 'FREE_TEXT'), ('NUMERIC_INPUT', 'NUMERIC_INPUT')], db_index=True, max_length=200, null=True),
        ),
    ]
