# Generated by Django 3.1.2 on 2021-07-14 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0089_auto_20210708_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='description',
        ),
        migrations.RemoveField(
            model_name='match',
            name='name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='programmatic_details',
        ),
        migrations.RemoveField(
            model_name='match',
            name='programmatic_key',
        ),
        migrations.AddField(
            model_name='match',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
