# Generated by Django 3.1.2 on 2022-10-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0089_auto_20221003_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='whatsapp_code_purpose',
            field=models.CharField(blank=True, choices=[('LOGIN', 'LOGIN'), ('VERIFY_WHATSAPP', 'VERIFY_WHATSAPP')], db_index=True, max_length=20, null=True),
        ),
    ]
