# Generated by Django 3.1.2 on 2022-10-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0090_auto_20221004_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_code_purpose',
            field=models.CharField(blank=True, choices=[('LOGIN', 'LOGIN'), ('REGISTER', 'REGISTER')], db_index=True, max_length=20, null=True),
        ),
    ]
