# Generated by Django 3.1.2 on 2021-07-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0090_auto_20210714_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberlinkaccess',
            name='hash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accesses', related_query_name='accesses', to='relationships.phonenumberhash'),
        ),
    ]
