# Generated by Django 3.1.2 on 2021-08-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0091_auto_20210717_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_auto_reply',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='is_customer_service',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='is_excluded',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
