# Generated by Django 3.1.2 on 2022-10-05 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20220301_2226'),
        ('relationships', '0091_auto_20221005_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCommentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files_as_review_comment', related_query_name='files_as_review_comment', to='relationships.reviewcomment')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_response_files_as_file', related_query_name='review_response_files_as_file', to='files.file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_as_file', related_query_name='reviews_as_file', to='files.file')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', related_query_name='files', to='relationships.review')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='reviewimage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='reviewimage',
            name='review',
        ),
        migrations.DeleteModel(
            name='ReviewCommentImage',
        ),
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
