# Generated by Django 3.1.2 on 2022-10-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_remove_file_lead'),
        ('relationships', '0092_auto_20221005_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('csrf', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_files_as_file', related_query_name='status_files_as_file', to='files.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_files_as_user', related_query_name='status_files_as_user', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
