# Generated by Django 3.1.2 on 2021-08-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0092_auto_20210803_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='is_auto_reply',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_customer_service',
        ),
        migrations.AddField(
            model_name='email',
            name='is_familiar',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
