# Generated by Django 3.1.2 on 2021-08-10 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_matchkeyword_country'),
        ('relationships', '0093_auto_20210809_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_w_this_country', related_query_name='users_w_this_country', to='common.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_w_this_state', related_query_name='users_w_this_state', to='common.country'),
        ),
    ]
