# Generated by Django 3.1.2 on 2021-08-11 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_matchkeyword_country'),
        ('relationships', '0094_auto_20210810_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_w_this_state', related_query_name='users_w_this_state', to='common.state'),
        ),
    ]
