# Generated by Django 3.1.2 on 2022-10-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0094_auto_20221005_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='walked_through_status',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
