# Generated by Django 3.1.2 on 2021-08-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0095_auto_20210811_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_excluded',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_familiar',
        ),
        migrations.AddField(
            model_name='email',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='emails', related_query_name='emails', to='relationships.EmailTag'),
        ),
    ]
