# Generated by Django 3.1.2 on 2022-10-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0096_auto_20221007_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusfile',
            name='activated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
