# Generated by Django 3.1.2 on 2021-08-11 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0097_email_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='phone_number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email', related_query_name='email', to='relationships.phonenumber'),
        ),
    ]
