# Generated by Django 3.1.2 on 2022-10-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0097_statusfile_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusfile',
            name='file_identifier',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
