# Generated by Django 3.1.2 on 2021-08-11 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0098_email_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phone_numbers', related_query_name='phone_numbers', to='relationships.email'),
        ),
    ]
