# Generated by Django 3.1.2 on 2022-10-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0098_statusfile_file_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusfile',
            name='file_identifier',
        ),
        migrations.AddField(
            model_name='statusfile',
            name='file_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
