# Generated by Django 3.1.2 on 2022-10-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0099_auto_20221009_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactaction',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
