# Generated by Django 3.1.2 on 2022-10-11 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0100_contactaction_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactaction',
            name='contactee',
        ),
        migrations.AddField(
            model_name='contactaction',
            name='phone_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='contact_actions', related_query_name='contact_actions', to='relationships.phonenumber'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactaction',
            name='contactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_actions', related_query_name='contact_actions', to='relationships.user'),
        ),
    ]
