# Generated by Django 3.1.2 on 2021-08-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0101_auto_20210811_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='name',
        ),
    ]
