# Generated by Django 3.1.2 on 2022-10-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0101_auto_20221011_1736'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactaction',
            unique_together={('contactor', 'phone_number')},
        ),
    ]
