# Generated by Django 3.1.2 on 2021-08-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0102_remove_email_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_with_this_email_as_cc', related_query_name='user_with_this_email_as_cc', to='relationships.email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_with_this_email', related_query_name='user_with_this_email', to='relationships.email'),
        ),
    ]
