# Generated by Django 3.1.2 on 2022-10-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0102_auto_20221011_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginaction',
            name='cookie_uuid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='register_cookie_uuid',
        ),
        migrations.AddField(
            model_name='loginaction',
            name='type',
            field=models.CharField(choices=[('magic', 'Magic Login'), ('whatsapp', 'WhatsApp Login')], db_index=True, default='whatsapp', max_length=40),
            preserve_default=False,
        ),
    ]
