# Generated by Django 3.1.2 on 2022-10-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0103_auto_20221012_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactaction',
            old_name='count',
            new_name='action_count',
        ),
    ]
