# Generated by Django 3.1.2 on 2021-08-30 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0104_lead_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_2',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', related_query_name='user', to='relationships.email'),
        ),
    ]
