# Generated by Django 3.1.2 on 2022-10-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0104_auto_20221012_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='whatsapp_code_purpose',
            field=models.CharField(blank=True, choices=[('LOGIN', 'LOGIN'), ('VERIFY_WHATSAPP', 'VERIFY_WHATSAPP'), ('UPDATE_EMAIL', 'UPDATE_EMAIL')], db_index=True, max_length=20, null=True),
        ),
    ]
