# Generated by Django 3.1.2 on 2021-08-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0105_auto_20210830_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
