# Generated by Django 3.1.2 on 2021-09-02 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0106_user_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_w_this_as_current_recommendation', related_query_name='users_w_this_as_recommendation', to='relationships.recommendation'),
        ),
    ]
