# Generated by Django 3.1.2 on 2022-10-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0106_auto_20221013_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_code_purpose',
            field=models.CharField(blank=True, choices=[('LOGIN', 'LOGIN'), ('VERIFY_EMAIL', 'VERIFY_EMAIL'), ('UPDATE_EMAIL', 'UPDATE_EMAIL')], db_index=True, max_length=20, null=True),
        ),
    ]
