# Generated by Django 3.1.2 on 2022-10-12 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0107_auto_20221013_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_as_pending_email', related_query_name='user_as_pending_email', to='relationships.email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_code_purpose',
            field=models.CharField(blank=True, choices=[('LOGIN', 'LOGIN'), ('REGISTER', 'REGISTER'), ('UPDATE_EMAIL', 'UPDATE_EMAIL')], db_index=True, max_length=20, null=True),
        ),
    ]
