# Generated by Django 3.1.2 on 2021-09-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0107_user_current_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='lead_type',
        ),
        migrations.AddField(
            model_name='lead',
            name='is_buying',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
