# Generated by Django 3.1.2 on 2022-10-17 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_remove_file_lead'),
        ('relationships', '0108_auto_20221013_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewfile',
            name='review',
        ),
        migrations.AddField(
            model_name='reviewfile',
            name='activated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewfile',
            name='file_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewfile',
            name='form_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reviewfile',
            name='phone_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='review_file_as_phone_number', related_query_name='review_file_as_phone_number', to='relationships.phonenumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewfile',
            name='reviewer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='review_file_as_reviewer', related_query_name='review_file_as_reviewer', to='relationships.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewfile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_file_as_file', related_query_name='review_file_as_file', to='files.file'),
        ),
    ]
