# Generated by Django 3.1.2 on 2021-09-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0108_auto_20210903_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
