# Generated by Django 3.1.2 on 2021-09-04 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0109_lead_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_w_this_as_current_lead', related_query_name='users_w_this_as_current_lead', to='relationships.lead'),
        ),
    ]
