# Generated by Django 3.1.2 on 2022-10-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0109_auto_20221017_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcommentfile',
            name='activated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewcommentfile',
            name='file_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewcommentfile',
            name='form_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
