# Generated by Django 3.1.2 on 2022-10-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0110_auto_20221019_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcomment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses_as_review', related_query_name='responses_as_review', to='relationships.review'),
        ),
    ]
