# Generated by Django 3.1.2 on 2022-10-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0111_auto_20221021_0045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewCommentFile',
        ),
    ]
