# Generated by Django 3.1.2 on 2021-09-09 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0112_auto_20210907_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', related_query_name='leads', to='relationships.producttype'),
        ),
    ]
