# Generated by Django 3.1.2 on 2021-09-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0113_lead_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='recommend_product_type_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
