# Generated by Django 3.1.2 on 2021-09-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0115_auto_20210914_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='recommend_immediate_confirm_choice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommend_immediate_confirm_responded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
