# Generated by Django 3.1.2 on 2021-09-16 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0117_auto_20210915_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='invalid_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clean_email', related_query_name='clean_email', to='relationships.invalidemail'),
        ),
    ]
