# Generated by Django 3.1.2 on 2021-09-26 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relationships', '0118_email_invalid_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('family_name', models.CharField(max_length=200)),
                ('given_name', models.CharField(max_length=200)),
                ('show_family_name_first', models.BooleanField(db_index=True)),
                ('who_i_know', models.TextField()),
                ('what_have_i_sold', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', related_query_name='user_profiles', to='relationships.email')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', related_query_name='user_profiles', to='relationships.phonenumber')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('rating', models.IntegerField(db_index=True)),
                ('review', models.TextField()),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviewees', related_query_name='reviewees', to='relationships.userprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviewers', related_query_name='reviewers', to='relationships.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections_with_this_as_user_1', related_query_name='connections_with_this_as_user_1', to='relationships.userprofile')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections_with_this_as_user_2', related_query_name='connections_with_this_as_user_2', to='relationships.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
