# Generated by Django 3.1.2 on 2021-10-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0119_userconnection_userprofile_userreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
