# Generated by Django 3.1.2 on 2021-10-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20211016_1628'),
        ('relationships', '0121_delete_userconnection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
