# Generated by Django 3.1.2 on 2021-10-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0122_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadText',
        ),
    ]
