# Generated by Django 3.1.2 on 2021-10-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0123_delete_leadtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_lead',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
