# Generated by Django 3.1.2 on 2021-10-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0124_auto_20211016_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_recommendation',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
