# Generated by Django 3.1.2 on 2021-10-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0125_auto_20211016_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='tags',
        ),
        migrations.DeleteModel(
            name='EmailTag',
        ),
    ]
