# Generated by Django 3.1.2 on 2021-10-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0126_auto_20211016_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_qna',
        ),
        migrations.DeleteModel(
            name='QuestionAnswerPair',
        ),
    ]
