# Generated by Django 3.1.2 on 2021-10-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0127_auto_20211016_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='demand',
        ),
        migrations.DeleteModel(
            name='Demand',
        ),
    ]
