# Generated by Django 3.1.2 on 2021-10-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0128_auto_20211016_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='supply',
        ),
    ]
