# Generated by Django 3.1.2 on 2021-10-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0129_remove_match_supply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supply',
        ),
    ]
