# Generated by Django 3.1.2 on 2021-10-16 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0131_delete_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitofmeasure',
            name='product_type',
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connection_user_1s', related_query_name='connection_user_1s', to='relationships.user')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connection_user_2s', related_query_name='connection_user_2s', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
