# Generated by Django 3.1.2 on 2021-10-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0132_auto_20211016_2158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
