# Generated by Django 3.1.2 on 2021-10-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0133_delete_producttype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
