# Generated by Django 3.1.2 on 2021-10-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0134_delete_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitOfMeasure',
        ),
    ]
