# Generated by Django 3.1.2 on 2021-10-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0135_delete_unitofmeasure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
