# Generated by Django 3.1.2 on 2021-10-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0136_delete_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_match',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
