# Generated by Django 3.1.2 on 2021-10-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0137_auto_20211016_2215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeFrame',
        ),
    ]
