# Generated by Django 3.1.2 on 2021-10-16 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_delete_matchkeyword'),
        ('files', '0004_remove_file_lead'),
        ('relationships', '0138_delete_timeframe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_banned',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registered',
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='display_family_name_first',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_given_name',
            field=models.CharField(db_index=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='users_w_this_language', related_query_name='users_w_this_language', to='common.Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_family_name',
            field=models.CharField(db_index=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_w_this_profile_picture', related_query_name='users_w_this_profile_picture', to='files.file'),
        ),
        migrations.AddField(
            model_name='user',
            name='state_string',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
