# Generated by Django 3.1.2 on 2021-10-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0139_auto_20211016_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='verified',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
