# Generated by Django 3.1.2 on 2021-10-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0140_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('verified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', related_query_name='verifications', to='relationships.phonenumber')),
                ('phone_number_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', related_query_name='verifications', to='relationships.phonenumbertype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
