# Generated by Django 3.1.2 on 2021-10-16 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0141_phonenumberverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now=True, db_index=True)),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_with_this_connection_as_one', related_query_name='users_with_this_connection_as_one', to='relationships.user')),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_with_this_connection_as_two', related_query_name='users_with_this_connection_as_two', to='relationships.user')),
            ],
            options={
                'unique_together': {('user_one', 'user_two')},
            },
        ),
    ]
