# Generated by Django 3.1.2 on 2021-10-16 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0142_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('requested', models.DateTimeField(db_index=True)),
                ('responded', models.DateTimeField(db_index=True)),
                ('response', models.CharField(blank=True, choices=[('accept', 'Accept'), ('reject', 'Reject')], max_length=20, null=True)),
                ('requestee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_with_this_friend_requester_as_requestee', related_query_name='users_with_this_friend_requester_as_requestee', to='relationships.user')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_with_this_friend_requester_as_requester', related_query_name='users_with_this_friend_requester_as_requester', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
