# Generated by Django 3.1.2 on 2021-10-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0144_delete_phonenumberverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneNumberLinkAccess',
        ),
    ]
