# Generated by Django 3.1.2 on 2021-10-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0146_auto_20211029_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='connected',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
