# Generated by Django 3.1.2 on 2021-10-29 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0147_auto_20211029_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('is_mobile', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_tablet', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_touch_capable', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_pc', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_bot', models.BooleanField(blank=True, db_index=True, null=True)),
                ('browser', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('browser_family', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('browser_version', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('browser_version_string', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('os', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('os_family', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('os_version', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('os_version_string', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('device', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('device_family', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_given_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_family_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_picture',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='display_family_name_first',
        ),
        migrations.AddField(
            model_name='user',
            name='country_string',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='languages_string',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='register_user_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='register_user_agents_with_this_user', related_query_name='register_user_agents_with_this_user', to='relationships.useragent'),
        ),
    ]
