# Generated by Django 3.1.2 on 2021-11-01 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import relationships.models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0148_auto_20211029_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile',
            new_name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='register_user_agent',
        ),
        migrations.AddField(
            model_name='user',
            name='registered',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LoginRegisterToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('accessed', models.DateTimeField(auto_now=True, db_index=True)),
                ('token', models.CharField(db_index=True, default=relationships.models.get_token, max_length=200)),
                ('expiry_secs', models.IntegerField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='login_register_tokens', related_query_name='login_register_tokens', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
