# Generated by Django 3.1.2 on 2021-11-02 04:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0149_auto_20211101_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
