# Generated by Django 3.1.2 on 2021-11-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0151_auto_20211102_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='phone_number',
        ),
    ]
