# Generated by Django 3.1.2 on 2021-11-03 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0153_auto_20211102_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registertoken',
            name='user',
        ),
    ]
