# Generated by Django 3.1.2 on 2021-11-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0154_remove_registertoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logintoken',
            name='accessed',
        ),
        migrations.RemoveField(
            model_name='registertoken',
            name='accessed',
        ),
        migrations.AddField(
            model_name='logintoken',
            name='activated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='registertoken',
            name='activated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='registertoken',
            name='refreshed',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
