# Generated by Django 3.1.2 on 2021-11-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0155_auto_20211103_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintoken',
            name='expiry_secs',
            field=models.IntegerField(db_index=True, default=900),
        ),
        migrations.AlterField(
            model_name='registertoken',
            name='expiry_secs',
            field=models.IntegerField(db_index=True, default=900),
        ),
    ]
