# Generated by Django 3.1.2 on 2021-11-03 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relationships', '0156_auto_20211103_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registertoken',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registertoken',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registertoken',
            name='languages_string',
        ),
        migrations.RemoveField(
            model_name='registertoken',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='registertoken',
            name='whatsapp_phone_number',
        ),
        migrations.AddField(
            model_name='registertoken',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='register_tokens', related_query_name='register_tokens', to='relationships.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='django_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', related_query_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', related_query_name='user', to='relationships.email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', related_query_name='user', to='relationships.phonenumber'),
        ),
    ]
