# Generated by Django 3.1.2 on 2021-11-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0157_auto_20211103_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registered',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
