# Generated by Django 3.1.2 on 2021-11-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0158_auto_20211103_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='key',
        ),
    ]
