# Generated by Django 3.1.2 on 2021-11-03 13:26

from django.db import migrations, models
import relationships.models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0159_remove_user_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintoken',
            name='token',
            field=models.CharField(db_index=True, default=relationships.models.get_token, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registertoken',
            name='token',
            field=models.CharField(db_index=True, default=relationships.models.get_token, max_length=200, unique=True),
        ),
    ]
