# Generated by Django 3.1.2 on 2021-11-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0160_auto_20211103_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country_string',
        ),
    ]
