# Generated by Django 3.1.2 on 2021-11-23 02:44

from django.db import migrations, models
import uuid

def create_uuid(apps, schema_editor):
    User = apps.get_model('relationships', 'User')
    for user in User.objects.all():
        user.uuid = uuid.uuid4()
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0161_remove_user_country_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(unique=True)
        )
    ]
