# Generated by Django 3.1.2 on 2021-11-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0163_auto_20211123_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='user_one_contact_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='connection',
            name='user_two_contact_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logintoken',
            name='refreshed',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='useragent',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='user_agents', related_query_name='user_agents', to='relationships.user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='useragent',
            unique_together={('user', 'ip_address', 'is_mobile', 'is_tablet', 'is_touch_capable', 'is_pc', 'is_bot', 'browser', 'browser_family', 'browser_version', 'browser_version_string', 'os', 'os_family', 'os_version', 'os_version_string', 'device', 'device_family')},
        ),
    ]
