# Generated by Django 3.1.2 on 2021-04-28 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20210428_0957'),
        ('relationships', '0032_auto_20210427_1321'),
        ('processor', '0002_remove_basetruth_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMessageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('is_disabled', models.BooleanField(db_index=True)),
                ('grouped', models.DateTimeField(db_index=True)),
                ('initial_body', models.TextField(db_index=True)),
                ('twilio_inbound_messages', models.ManyToManyField(db_index=True, related_name='inbound_message_groups', related_query_name='inbound_message_groups', to='chat.TwilioInboundMessage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InboundMessageGroupRelationshipTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
                ('is_function', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('version', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MethodTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperationMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
                ('applied', models.DateTimeField(db_index=True)),
                ('order', models.IntegerField(db_index=True)),
                ('output_body', models.TextField(blank=True, db_index=True, null=True)),
                ('inbound_message_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_methods', related_query_name='operation_methods', to='processor.inboundmessagegroup')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_methods', related_query_name='operation_methods', to='processor.method')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='method',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='methods', related_query_name='methods', to='processor.MethodTag'),
        ),
        migrations.CreateModel(
            name='InboundMessageGroupRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('associated', models.DateTimeField(db_index=True)),
                ('demand_quotes', models.ManyToManyField(db_index=True, related_name='inbound_message_group_relationships', related_query_name='inbound_message_group_relationships', to='relationships.DemandQuote')),
                ('demands', models.ManyToManyField(db_index=True, related_name='inbound_message_group_relationships', related_query_name='inbound_message_group_relationships', to='relationships.Demand')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_message_group_relationships', related_query_name='inbound_message_group_relationships', to='processor.inboundmessagegroup')),
                ('supplies', models.ManyToManyField(db_index=True, related_name='inbound_message_group_relationships', related_query_name='inbound_message_group_relationships', to='relationships.Supply')),
                ('supply_quotes', models.ManyToManyField(db_index=True, related_name='inbound_message_group_relationships', related_query_name='inbound_message_group_relationships', to='relationships.SupplyQuote')),
                ('tags', models.ManyToManyField(db_index=True, related_name='inbound_message_group_relationships', related_query_name='inbound_message_group_relationships', to='processor.InboundMessageGroupRelationshipTag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
                ('applied', models.DateTimeField(db_index=True)),
                ('order', models.IntegerField(db_index=True)),
                ('inbound_message_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grouping_methods', related_query_name='grouping_methods', to='processor.inboundmessagegroup')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grouping_methods', related_query_name='grouping_methods', to='processor.method')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
