# Generated by Django 3.1.2 on 2021-04-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0005_auto_20210428_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testruntype',
            old_name='settings',
            new_name='setting',
        ),
    ]
