# Generated by Django 3.1.2 on 2021-04-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0006_auto_20210428_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmessagegroup',
            name='body',
            field=models.TextField(),
        ),
    ]
