# Generated by Django 3.1.2 on 2021-05-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20210428_1534'),
        ('processor', '0010_auto_20210504_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBodyMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('group', models.CharField(db_index=True, max_length=200)),
                ('ran', models.DateField(db_index=True)),
                ('is_base_truth', models.BooleanField(db_index=True)),
                ('is_enabled', models.BooleanField(db_index=True)),
                ('version', models.CharField(db_index=True, max_length=200)),
                ('body_copy', models.TextField()),
                ('test_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_body_meta_datas', related_query_name='message_body_meta_datas', to='processor.testmessage')),
                ('twilio_inbound_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_body_meta_datas', related_query_name='message_body_meta_datas', to='chat.twilioinboundmessage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
