# Generated by Django 3.1.2 on 2021-05-04 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0011_messagebodymetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBodyMetaDataEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('entity_type', models.CharField(choices=[('newline', 'Newline'), ('domain_dot', 'Domain Dot'), ('tld', 'TLD'), ('url', 'URL'), ('decimal_point', 'Decimal Point'), ('number_separator', 'Number Separator'), ('number_uom', 'Number UOM'), ('number', 'Number'), ('fullstop', 'Fullstop'), ('exclamation_mark', 'Exclamation Mark'), ('email', 'Email'), ('currency', 'Currency'), ('price', 'Price'), ('excluded_pricing', 'Excluded Pricing'), ('location', 'Location'), ('incoterm_availability', 'Incoterm/Availability'), ('application', 'Application'), ('phone_number', 'Phone Number'), ('company', 'Company'), ('product_type', 'Product Type'), ('product', 'Product'), ('product_specification_type', 'Product Specification Type'), ('uom', 'UOM'), ('moq', 'MOQ'), ('quantity', 'Quantity'), ('packing', 'Packing')], db_index=True, max_length=30)),
                ('start_position', models.IntegerField(db_index=True)),
                ('end_position', models.IntegerField(db_index=True)),
                ('boolean_value', models.BooleanField(blank=True, db_index=True, null=True)),
                ('numeric_value', models.FloatField(blank=True, db_index=True, null=True)),
                ('string_value', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('substring', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('programmatic_key_1', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('programmatic_key_2', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('meta_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_body_meta_datas', related_query_name='message_body_meta_datas', to='processor.messagebodymetadata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
