# Generated by Django 3.1.2 on 2021-05-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0012_messagebodymetadataentity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagebodymetadataentity',
            options={'verbose_name': 'Message body meta data entity', 'verbose_name_plural': 'Message body meta data entities'},
        ),
    ]
