# Generated by Django 3.1.2 on 2021-05-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0015_auto_20210506_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingkeyword',
            name='edit_distance_tolerance',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
