# Generated by Django 3.0.5 on 2020-10-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='country',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='country',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parentchildrenchoice',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='parentchildrenchoice',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='parentchildrenchoice',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='state',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='state',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
