# Generated by Django 3.0.5 on 2020-10-08 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20201008_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentchildrenchoice',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', related_query_name='children', to='common.ParentChildrenChoice'),
        ),
    ]
