# Generated by Django 3.1.2 on 2021-10-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_matchkeyword_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchkeyword',
            name='product_type',
        ),
    ]
