# Generated by Django 3.1.2 on 2020-11-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20201106_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('started', models.DateTimeField(db_index=True)),
                ('ended', models.DateTimeField(db_index=True, null=True)),
                ('status', models.CharField(choices=[('Started', 'started'), ('Succeeded', 'succeeded'), ('Failed', 'failed')], db_index=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
