# Generated by Django 3.1.2 on 2021-10-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_matchkeyword_product_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchKeyword',
        ),
    ]
