# Generated by Django 3.1.2 on 2020-11-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20201108_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
