# Generated by Django 3.1.2 on 2020-11-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_importjob_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
