# Generated by Django 3.1.2 on 2020-11-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_systemtimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemtimestamp',
            name='key',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
