# Generated by Django 3.1.2 on 2020-12-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20201123_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='state',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
    ]
