# Generated by Django 3.1.2 on 2020-12-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='china_province_name_cn',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
