# Generated by Django 3.1.2 on 2021-03-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20210326_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='programmatic_details_md',
        ),
        migrations.RemoveField(
            model_name='language',
            name='programmatic_details_md',
        ),
        migrations.RemoveField(
            model_name='state',
            name='programmatic_details_md',
        ),
        migrations.AddField(
            model_name='country',
            name='programmatic_details',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details'),
        ),
        migrations.AddField(
            model_name='language',
            name='programmatic_details',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details'),
        ),
        migrations.AddField(
            model_name='state',
            name='programmatic_details',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details'),
        ),
    ]
