# Event and event properties

CHATBOT__READ_WHATSAPP_MESSAGE = 'chatbot - read whatsapp message'
CHATBOT__READ_WHATSAPP_MESSAGE__INTENT = 'intent'
CHATBOT__READ_WHATSAPP_MESSAGE__MESSAGE = 'message'

CONNECT__CONTACTED_USER = 'connect - contacted user'
CONNECT__CONTACTED_USER__SOURCE = 'source'
CONNECT__CONTACTED_USER__LEAD_DETAIL = 'lead detail'
CONNECT__CONTACTED_USER__WHATSAPP_MESSAGE = 'whatsapp message'
CONNECT__ACCEPTED_CONTACT = 'connect - accepted contact'

BROWSE__CLICKED_LEAD_DETAIL = 'connect - clicked lead detail'
BROWSE__CLICKED_LEAD_DETAIL__SOURCE = 'source'
BROWSE__CLICKED_LEAD_DETAIL__SOURCE__LEAD_LIST = 'lead list'
BROWSE__CLICKED_LEAD_DETAIL__SOURCE__WHATSAPP_MESSAGE = 'whatsapp message'
BROWSE__CLICKED_LEAD_DETAIL__SOURCE__WHATSAPP_MESSAGE__JSKEY = 'ld'
BROWSE__CLICKED_LEAD_DETAIL__SOURCE__WHATSAPP_MESSAGE__JSVAL = 'w'

BROWSE__FILTERED_LEAD_LIST = 'browse - filtered lead list'
REGISTRATION__REGISTERED = 'registration - registered'

POST_NEW_LEAD__CLICKED_POST_NEW_LEAD = 'post new lead - clicked post-new-lead'
POST_NEW_LEAD__CLICKED_POST_NEW_LEAD__SOURCE = 'source'
POST_NEW_LEAD__CLICKED_POST_NEW_LEAD__SOURCE__LEAD_LIST_TOOLBAR = 'lead list toolbar'
POST_NEW_LEAD__CLICKED_POST_NEW_LEAD__SOURCE__LEAD_LIST_BANNER = 'lead list banner'
POST_NEW_LEAD__CLICKED_POST_NEW_LEAD__SOURCE__WHATSAPP_MESSAGE = 'whatsapp message'
POST_NEW_LEAD__CLICKED_POST_NEW_LEAD__SOURCE__WHATSAPP_MESSAGE__JSKEY = 'cl'
POST_NEW_LEAD__CLICKED_POST_NEW_LEAD__SOURCE__WHATSAPP_MESSAGE__JSVAL = 'w'
POST_NEW_LEAD__POSTED_NEW_LEAD = 'post new lead - posted new lead'