# Events

##### Active 1 Sep 2021 #####

# Generic
ENTERED_STRAY_TEXT = 'ENTERED_STRAY_TEXT'
ENTERED_FREE_TEXT = 'ENTERED_FREE_TEXT'
ENTERED_NUMBER = 'ENTERED_NUMBER'
INVALID_NUMBER = 'INVALID_NUMBER'
DO_NOT_UNDERSTAND_OPTION = 'DO_NOT_UNDERSTAND_OPTION'

# Menu
MENU__FIND_BUYERS = 'MENU__FIND_BUYERS'
MENU__FIND_SELLERS = 'MENU__FIND_SELLERS'
MENU__TALK_TO_AN_EVERYBASE_AGENT = 'MENU__TALK_TO_AN_EVERYBASE_AGENT'
MENU__REGISTER_ME = 'MENU__REGISTER_ME'

# Payment
CLICKED_WHATSAPP_LINK = 'CLICKED_WHATSAPP_LINK'
CLICKED_PAYMENT_LINK = 'CLICKED_PAYMENT_LINK'
PAID = 'PAID'

# Recommend details
RECOMMEND__DETAILS__DIRECT = 'RECOMMEND__DETAILS__DIRECT'
RECOMMEND__DETAILS__CAN_FIND = 'RECOMMEND__DETAILS__CAN_FIND'
RECOMMEND__DETAILS__NOT_INTERESTED = 'RECOMMEND__DETAILS__NOT_INTERESTED'

##### Deprecated 1 Sep 2021 #####

# CHOSE_FIND_BUYERS_WITH_REPLY = 'Chose find-buyers with reply'
# CHOSE_FIND_SELLERS_WITH_REPLY = 'Chose find-sellers with reply'
# CHOSE_LEARN_MORE_WITH_REPLY = 'Chose learn-more with reply'
# CHOSE_READY_STOCK_OTG_WITH_REPLY = 'Chose ready-stock-otg with reply'
# CHOSE_PRE_ORDER_WITH_REPLY = 'Chose pre-order with reply'
# CHOSE_YES_WITH_REPLY = 'Chose yes with reply'
# CHOSE_NO_WITH_REPLY = 'Chose no with reply'
# CHOSE_ANSWER_QUESTION_WITH_REPLY = 'Chose answer-question with reply'
# CHOSE_BUY_CONTACT_WITH_REPLY = 'Chose buy-contact with reply'
# CHOSE_STOP_DISCUSSION_WITH_REPLY = 'Chose stop-discussion with reply'
# CHOSE_ASK_QUESTION_WITH_REPLY = 'Chose ask-question with reply'