# Generated by Django 3.0 on 2020-01-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
