# Generated by Django 3.0.2 on 2020-01-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20200123_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='deleted',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='deleted',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
