# Generated by Django 3.0.5 on 2020-10-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_auto_20201021_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuestatus',
            name='parent',
        ),
    ]
