# Generated by Django 3.1.2 on 2020-12-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_auto_20201106_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationchannel',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='conversationchatstatus',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='conversationemailstatus',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='conversationvideostatus',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='conversationvoicestatus',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='issuestatus',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='issuetag',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
    ]
