# Generated by Django 3.1.2 on 2020-11-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20201025_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='files',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='files',
        ),
    ]
