# Generated by Django 3.1.2 on 2020-12-18 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0044_remove_link_verified'),
        ('leads', '0020_auto_20201218_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandLinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('details_md', models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown')),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details_md', models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown')),
            ],
            options={
                'verbose_name': 'Demand-link type',
                'verbose_name_plural': 'Demand-link types',
            },
        ),
        migrations.CreateModel(
            name='SupplyLinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('details_md', models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown')),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details_md', models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown')),
            ],
            options={
                'verbose_name': 'Supply-link type',
                'verbose_name_plural': 'Supply-link types',
            },
        ),
        migrations.CreateModel(
            name='SupplyLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('details_md', models.TextField(blank=True, null=True, verbose_name='Details in Markdown')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_link_relationships', related_query_name='supply_link_relationships', to='relationships.link')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_link_relationships', related_query_name='supply_link_relationships', to='leads.supplylinktype', verbose_name='Supply-link relationship type')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_link_relationships', related_query_name='supply_link_relationships', to='leads.supply')),
            ],
            options={
                'verbose_name': 'Supply-link',
                'verbose_name_plural': 'Supply-links',
            },
        ),
        migrations.CreateModel(
            name='DemandLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('details_md', models.TextField(blank=True, null=True, verbose_name='Details in Markdown')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_link_relationships', related_query_name='demand_link_relationships', to='leads.demand')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_link_relationships', related_query_name='demand_link_relationships', to='relationships.link')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_link_relationships', related_query_name='demand_link_relationships', to='leads.demandlinktype', verbose_name='Demand-link relationship type')),
            ],
            options={
                'verbose_name': 'Demand-link',
                'verbose_name_plural': 'Demand-links',
            },
        ),
        migrations.AlterField(
            model_name='demand',
            name='links',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='demands', related_query_name='demands', to='leads.DemandLink'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='links',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='supplies', related_query_name='supplies', to='leads.SupplyLink'),
        ),
    ]
