# Generated by Django 3.1.2 on 2021-11-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioInboundMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('api_version', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('message_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('sms_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('sms_message_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('sms_status', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('account_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('message_service_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('from_str', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('to_str', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('num_media', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('num_segments', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('from_city', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('from_state', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('from_zip', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('from_country', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('to_city', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('to_state', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('to_zip', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('to_country', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('profile_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('wa_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('forwarded', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('frequently_forwarded', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('latitude', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('label', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwilioInboundMessageLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('payload', models.TextField(db_index=True)),
            ],
            options={
                'verbose_name': 'Twilio Inbound Message Log Entry',
                'verbose_name_plural': 'Twilio Inbound Message Log Entries',
            },
        ),
        migrations.CreateModel(
            name='TwilioInboundMessageMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('content_type', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwilioOutboundMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('intent_key', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('message_key', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date_sent', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('direction', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('account_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('message_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('from_str', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('to_str', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('uri', models.URLField(blank=True, db_index=True, null=True)),
                ('error_message', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('error_code', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('api_version', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwilioStatusCallback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('from_str', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('to_str', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('account_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('api_version', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('channel_install_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('channel_prefix', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('channel_status_code', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('channel_status_message', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('channel_to_address', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('message_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('message_status', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('sms_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('sms_status', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('error_code', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('error_message', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwilioStatusCallbackLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('payload', models.TextField(db_index=True)),
            ],
            options={
                'verbose_name': 'Twilio Status Callback Log Entry',
                'verbose_name_plural': 'Twilio Status Callback Log Entries',
            },
        ),
        migrations.CreateModel(
            name='UserContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('started', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('done', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('paused', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expired', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('intent_key', models.CharField(choices=[('NO_INTENT', 'NO_INTENT'), ('REGISTER', 'REGISTER'), ('LOGIN', 'LOGIN'), ('CONTACT_REQUEST', 'CONTACT_REQUEST')], db_index=True, max_length=200)),
                ('message_key', models.CharField(choices=[('NO_MESSAGE', 'NO_MESSAGE'), ('DO_NOT_UNDERSTAND_OPTION', 'DO_NOT_UNDERSTAND_OPTION'), ('DO_NOT_UNDERSTAND_NUMBER', 'DO_NOT_UNDERSTAND_NUMBER'), ('DO_NOT_UNDERSTAND_EMAIL', 'DO_NOT_UNDERSTAND_EMAIL'), ('CONTACT_REQUEST__CONFIRM', 'CONTACT_REQUEST__CONFIRM'), ('CONTACT_REQUEST__CONTEXT_EXPIRED', 'CONTACT_REQUEST__CONTEXT_EXPIRED'), ('CONTACT_REQUEST__EXCHANGED_AUTHOR', 'CONTACT_REQUEST__EXCHANGED_AUTHOR'), ('CONTACT_REQUEST__EXCHANGED_CONTACTOR', 'CONTACT_REQUEST__EXCHANGED_CONTACTOR'), ('CONTACT_REQUEST__REASON_THANK_YOU', 'CONTACT_REQUEST__REASON_THANK_YOU'), ('CONTACT_REQUEST__REASON', 'CONTACT_REQUEST__REASON'), ('GENERIC', 'GENERIC'), ('LOGIN__CONFIRM', 'LOGIN__CONFIRM'), ('LOGIN__DO_NOT_UNDERSTAND', 'LOGIN__DO_NOT_UNDERSTAND'), ('REGISTER__CONFIRM', 'REGISTER__CONFIRM'), ('REGISTER__CONFIRMED', 'REGISTER__CONFIRMED'), ('REGISTER__DO_NOT_UNDERSTAND', 'REGISTER__DO_NOT_UNDERSTAND')], db_index=True, max_length=200)),
            ],
        ),
    ]
