# Generated by Django 3.1.2 on 2021-04-23 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relationships', '0028_auto_20210422_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('programmatic_key', models.CharField(db_index=True, max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('internal_title', models.CharField(db_index=True, max_length=200)),
                ('notes', models.TextField(blank=True, db_index=True, null=True)),
                ('body', models.TextField(blank=True, db_index=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwilioInboundMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('api_version', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('message_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('sms_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('sms_message_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('account_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('message_service_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('from_str', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('to_str', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, db_index=True, null=True)),
                ('num_media', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('num_segments', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('from_city', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('from_state', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('from_zip', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('from_country', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('to_city', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('to_state', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('to_zip', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('to_country', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('profile_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('wa_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('forwarded', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('frequently_forwarded', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('latitude', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('label', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwilioOutboundMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('date_created', models.DateField(blank=True, db_index=True, null=True)),
                ('date_sent', models.DateField(blank=True, db_index=True, null=True)),
                ('direction', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('account_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('message_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('from_str', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('to_str', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, db_index=True, null=True)),
                ('uri', models.URLField(blank=True, db_index=True, null=True)),
                ('error_message', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('error_code', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('api_version', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='twilio_outbound_message_from_users', related_query_name='twilio_outbound_from_users', to='relationships.user')),
                ('message_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='twilio_outbound_messages', related_query_name='twilio_outbound_messages', to='chat.messagetemplate')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='twilio_outbound_message_to_users', related_query_name='twilio_outbound_to_users', to='relationships.user')),
                ('twilml_response_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='twilio_outbound_message_responses', related_query_name='twilio_outbound_message_responses', to='chat.twilioinboundmessage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwilioStatusCallbackLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('payload', models.TextField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwilioStatusCallback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('from_str', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('to_str', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('account_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('api_version', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('channel_to_address', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('channel_install_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('channel_status_message', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('channel_prefix', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('message_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('message_status', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('sms_sid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('sms_status', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('error_code', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('log_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.twiliostatuscallbacklogentry')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.twiliooutboundmessage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
