# Generated by Django 3.1.2 on 2021-04-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210423_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twiliostatuscallbacklogentry',
            options={'verbose_name': 'Twilio Status Callback Log Entry', 'verbose_name_plural': 'Twilio Status Callback Log Entries'},
        ),
    ]
