# Generated by Django 3.1.2 on 2021-04-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210425_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='method',
            name='category',
        ),
        migrations.DeleteModel(
            name='MethodCategory',
        ),
        migrations.AddField(
            model_name='method',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='methods', related_query_name='methods', to='chat.MethodTag'),
        ),
    ]
