# Generated by Django 3.1.2 on 2021-04-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210427_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twilioinboundmessagelogentry',
            options={'verbose_name': 'Twilio Inbound Message Log Entry', 'verbose_name_plural': 'Twilio Inbound Message Log Entries'},
        ),
    ]
