# Generated by Django 3.1.2 on 2021-05-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0043_companyproducttype'),
        ('chat', '0010_auto_20210428_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatContextType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='body',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='internal_title',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='notes',
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='name',
            field=models.CharField(db_index=True, default='(Unnamed)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='programmatic_details',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='programmatic_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UserChatContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('started', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('stopped', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('chat_context_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_chat_contexts', related_query_name='user_chat_contexts', to='chat.chatcontexttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_chat_contexts', related_query_name='user_chat_contexts', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='chat_context_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_templates', related_query_name='message_templates', to='chat.chatcontexttype'),
        ),
    ]
