# Generated by Django 3.1.2 on 2022-07-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20220705_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontext',
            name='intent_key',
            field=models.CharField(choices=[('NO_INTENT', 'NO_INTENT'), ('REGISTER', 'REGISTER'), ('LOGIN', 'LOGIN'), ('LEAD', 'LEAD'), ('WELCOME', 'WELCOME'), ('CONFIRM_LOGIN', 'CONFIRM_LOGIN'), ('NEW_APPLICATION', 'NEW_APPLICATION'), ('NEW_MESSAGE', 'NEW_MESSAGE'), ('CONFIRM_PHONE_NUMBER_UPDATE', 'CONFIRM_PHONE_NUMBER_UPDATE')], db_index=True, max_length=200),
        ),
    ]
