# Generated by Django 3.1.2 on 2021-05-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20210515_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcontexttype',
            name='programmatic_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='programmatic_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
