# Generated by Django 3.1.2 on 2022-10-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20220707_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontext',
            name='intent_key',
            field=models.CharField(choices=[('NO_INTENT', 'NO_INTENT'), ('VERIFY_WHATSAPP', 'VERIFY_WHATSAPP'), ('CONFIRM_LOGIN', 'CONFIRM_LOGIN')], db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='message_key',
            field=models.CharField(choices=[('NO_MESSAGE', 'NO_MESSAGE'), ('DO_NOT_UNDERSTAND_OPTION', 'DO_NOT_UNDERSTAND_OPTION'), ('DO_NOT_UNDERSTAND_NUMBER', 'DO_NOT_UNDERSTAND_NUMBER'), ('DO_NOT_UNDERSTAND_EMAIL', 'DO_NOT_UNDERSTAND_EMAIL'), ('CONFIRM_LOGIN', 'CONFIRM_LOGIN'), ('VERIFY_WHATSAPP', 'VERIFY_WHATSAPP')], db_index=True, max_length=200),
        ),
    ]
