# Generated by Django 3.1.2 on 2021-06-07 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20210607_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedatavalue',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', related_query_name='values', to='chat.messagedataset'),
        ),
    ]
