# Generated by Django 3.1.2 on 2022-10-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_auto_20221004_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontext',
            name='intent_key',
            field=models.CharField(choices=[('NO_INTENT', 'NO_INTENT'), ('CONFIRM_LOGIN', 'CONFIRM_LOGIN'), ('LOOK_UP', 'LOOK_UP'), ('MENU', 'MENU'), ('REGISTER', 'REGISTER'), ('SUPPORT', 'SUPPORT'), ('VERIFY_WHATSAPP', 'VERIFY_WHATSAPP')], db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='message_key',
            field=models.CharField(choices=[('NO_MESSAGE', 'NO_MESSAGE'), ('DO_NOT_UNDERSTAND_OPTION', 'DO_NOT_UNDERSTAND_OPTION'), ('DO_NOT_UNDERSTAND_NUMBER', 'DO_NOT_UNDERSTAND_NUMBER'), ('DO_NOT_UNDERSTAND_EMAIL', 'DO_NOT_UNDERSTAND_EMAIL'), ('CONFIRM_LOGIN', 'CONFIRM_LOGIN'), ('LOOK_UP__DO_NOT_UNDERSTAND', 'LOOK_UP__DO_NOT_UNDERSTAND'), ('LOOK_UP__GET_CONTACT', 'LOOK_UP__GET_CONTACT'), ('LOOK_UP__LINK', 'LOOK_UP__LINK'), ('MENU', 'MENU'), ('REGISTER__LINK', 'REGISTER__LINK'), ('SUPPORT', 'SUPPORT'), ('VERIFY_WHATSAPP', 'VERIFY_WHATSAPP')], db_index=True, max_length=200),
        ),
    ]
