# Generated by Django 3.1.2 on 2021-06-07 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0068_auto_20210527_2218'),
        ('chat', '0016_auto_20210607_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedataset',
            name='in_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_datasets', related_query_name='message_datasets', to='chat.twilioinboundmessage'),
        ),
        migrations.AddField(
            model_name='messagedataset',
            name='out_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_datasets', related_query_name='message_datasets', to='chat.twiliooutboundmessage'),
        ),
        migrations.AddField(
            model_name='messagedataset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_datasets', related_query_name='message_datasets', to='relationships.user'),
        ),
        migrations.AddField(
            model_name='messagedatavalue',
            name='value_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='messagedataset',
            unique_together={('intent_key', 'message_key', 'in_message', 'out_message')},
        ),
        migrations.RemoveField(
            model_name='messagedataset',
            name='message',
        ),
    ]
