# Generated by Django 3.1.2 on 2021-05-17 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0064_auto_20210516_0155'),
        ('chat', '0017_auto_20210517_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliooutboundmessage',
            name='from_phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='twilio_outbound_message_from_phone_numbers', related_query_name='twilio_outbound_message_from_phone_numbers', to='relationships.phonenumber'),
        ),
        migrations.AddField(
            model_name='twiliooutboundmessage',
            name='to_phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='twilio_outbound_message_to_phone_numbers', related_query_name='twilio_outbound_message_to_phone_numbers', to='relationships.phonenumber'),
        ),
        migrations.AlterField(
            model_name='twiliooutboundmessage',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='twilio_outbound_message_from_users', related_query_name='twilio_outbound_message_from_users', to='relationships.user'),
        ),
        migrations.AlterField(
            model_name='twiliooutboundmessage',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='twilio_outbound_message_to_users', related_query_name='twilio_outbound_message_to_users', to='relationships.user'),
        ),
        migrations.AlterField(
            model_name='userchatcontext',
            name='context',
            field=models.CharField(choices=[('ur', 'User Registration'), ('mn', 'Menu')], db_index=True, max_length=2),
        ),
    ]
