# Generated by Django 3.1.2 on 2021-05-17 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0064_auto_20210516_0155'),
        ('chat', '0018_auto_20210517_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='twilioinboundmessage',
            name='from_phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='twilio_inbound_message_from_phone_numbers', related_query_name='twilio_inbound_message_from_phone_numbers', to='relationships.phonenumber'),
        ),
        migrations.AddField(
            model_name='twilioinboundmessage',
            name='to_phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='twilio_inbound_message_to_phone_numbers', related_query_name='twilio_inbound_message_to_phone_numbers', to='relationships.phonenumber'),
        ),
    ]
