# Generated by Django 3.1.2 on 2021-05-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_auto_20210517_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatcontext',
            name='context',
            field=models.CharField(choices=[('ur', 'User Registration'), ('mn', 'Menu')], db_index=True, max_length=200),
        ),
    ]
