# Generated by Django 3.1.2 on 2021-06-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0068_auto_20210527_2218'),
        ('chat', '0021_auto_20210607_1719'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagedataset',
            unique_together={('intent_key', 'message_key', 'in_message', 'out_message', 'user')},
        ),
    ]
