# Generated by Django 3.1.2 on 2021-05-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_auto_20210518_1351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserChatContext',
        ),
    ]
