# Generated by Django 3.1.2 on 2021-06-09 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0068_auto_20210527_2218'),
        ('chat', '0024_auto_20210609_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontext',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_contexts', related_query_name='user_contexts', to='relationships.user'),
            preserve_default=False,
        ),
    ]
