# Generated by Django 3.1.2 on 2021-05-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_auto_20210523_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twiliooutboundmessage',
            name='message_type',
        ),
        migrations.AddField(
            model_name='twiliooutboundmessage',
            name='intent_key',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='twiliooutboundmessage',
            name='message_key',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
