# Generated by Django 3.1.2 on 2021-06-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_auto_20210609_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twiliooutboundmessage',
            name='context',
        ),
        migrations.AddField(
            model_name='twiliooutboundmessage',
            name='intent_key',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='twiliooutboundmessage',
            name='message_key',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
