# Generated by Django 3.1.2 on 2021-05-25 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0064_auto_20210516_0155'),
        ('chat', '0027_auto_20210524_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twiliooutboundmessage',
            name='intent_key',
        ),
        migrations.RemoveField(
            model_name='twiliooutboundmessage',
            name='message_key',
        ),
        migrations.AlterField(
            model_name='messagedataset',
            name='intent_key',
            field=models.CharField(choices=[('NO_INTENT', 'NO_INTENT'), ('SPEAK_HUMAN', 'SPEAK_HUMAN'), ('EXPLAIN_SERVICE', 'EXPLAIN_SERVICE'), ('REGISTER', 'REGISTER'), ('NEW_SUPPLY', 'NEW_SUPPLY'), ('NEW_DEMAND', 'NEW_DEMAND'), ('DISCUSS_W_BUYER', 'DISCUSS_W_BUYER'), ('DISCUSS_W_SELLER', 'DISCUSS_W_SELLER'), ('STOP_DISCUSSION', 'STOP_DISCUSSION'), ('CONNECT', 'CONNECT')], db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='messagedataset',
            name='message_key',
            field=models.CharField(choices=[('NO_MESSAGE', 'NO_MESSAGE'), ('MENU', 'MENU'), ('CONFIRM_HUMAN', 'CONFIRM_HUMAN'), ('EXPLAIN_SERVICE', 'EXPLAIN_SERVICE'), ('DO_NOT_UNDERSTAND', 'DO_NOT_UNDERSTAND'), ('REGISTER__GET_NAME', 'REGISTER__GET_NAME'), ('SUPPLY__GET_PRODUCT', 'SUPPLY__GET_PRODUCT'), ('SUPPLY__GET_AVAILABILITY', 'SUPPLY__GET_AVAILABILITY'), ('SUPPLY__GET_COUNTRY_STATE', 'SUPPLY__GET_COUNTRY_STATE'), ('SUPPLY__CONFIRM_PACKING', 'SUPPLY__CONFIRM_PACKING'), ('SUPPLY__GET_PACKING', 'SUPPLY__GET_PACKING'), ('SUPPLY__GET_QUANTITY', 'SUPPLY__GET_QUANTITY'), ('SUPPLY__GET_TIMEFRAME', 'SUPPLY__GET_TIMEFRAME'), ('SUPPLY__GET_PRICE', 'SUPPLY__GET_PRICE'), ('SUPPLY__GET_DEPOSIT', 'SUPPLY__GET_DEPOSIT'), ('SUPPLY__GET_ACCEPT_LC', 'SUPPLY__GET_ACCEPT_LC'), ('SUPPLY__THANK_YOU', 'SUPPLY__THANK_YOU'), ('DEMAND__GET_PRODUCT', 'DEMAND__GET_PRODUCT'), ('DEMAND__GET_COUNTRY_STATE', 'DEMAND__GET_COUNTRY_STATE'), ('DEMAND__GET_QUANTITY', 'DEMAND__GET_QUANTITY'), ('DEMAND__GET_PRICE', 'DEMAND__GET_PRICE'), ('DEMAND__THANK_YOU', 'DEMAND__THANK_YOU'), ('DISCUSS__CONFIRM_INTERESTED', 'DISCUSS__CONFIRM_INTERESTED'), ('STILL_INTERESTED__CONFIRM', 'STILL_INTERESTED__CONFIRM'), ('STILL_INTERESTED__THANK_YOU', 'STILL_INTERESTED__THANK_YOU'), ('DISCUSS__CONFIRM_UPDATED', 'DISCUSS__CONFIRM_UPDATED'), ('DISCUSS__ASK', 'DISCUSS__ASK'), ('DISCUSS__THANK_YOU', 'DISCUSS__THANK_YOU'), ('ALREADY_CONNECTED', 'ALREADY_CONNECTED'), ('YOUR_QUESTION', 'YOUR_QUESTION'), ('YOUR_ANSWER', 'YOUR_ANSWER'), ('STOP_DISCUSSION__REASON', 'STOP_DISCUSSION__REASON'), ('STOP_DISCUSSION__THANK_YOU', 'STOP_DISCUSSION__THANK_YOU'), ('PLEASE_PAY', 'PLEASE_PAY'), ('PAYEE_CONNECTED', 'PAYEE_CONNECTED'), ('NON_PAYEE_CONNECTED', 'NON_PAYEE_CONNECTED')], db_index=True, max_length=200),
        ),
        migrations.CreateModel(
            name='UserContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('started', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('done', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('paused', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expired', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('intent_key', models.CharField(db_index=True, max_length=200)),
                ('message_key', models.CharField(db_index=True, max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_contexts', related_query_name='user_contexts', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='twiliooutboundmessage',
            name='context',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='twilio_outbound_messages', related_query_name='twilio_outbound_messages', to='chat.usercontext'),
            preserve_default=False,
        ),
    ]
