# Generated by Django 3.1.2 on 2021-06-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0106_auto_20210628_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedatavalue',
            name='data_key',
            field=models.CharField(choices=[], db_index=True, max_length=200),
        ),
    ]
