# Generated by Django 3.1.2 on 2021-07-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0110_auto_20210709_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliostatuscallback',
            name='channel_status_code',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
