# Generated by Django 3.1.2 on 2021-07-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0111_twiliostatuscallback_channel_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliostatuscallback',
            name='error_message',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
