# Generated by Django 3.1.2 on 2021-07-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0112_twiliostatuscallback_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliooutboundmessage',
            name='error_message',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
