# Generated by Django 3.1.2 on 2021-07-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0113_auto_20210715_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliostatuscallback',
            name='error_message',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
