# Generated by Django 3.1.2 on 2021-08-29 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('relationships', '0104_lead_recommendation'),
        ('chat', '0115_auto_20210727_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedataset',
            name='leads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='datasets', related_query_name='datasets', to='relationships.lead'),
        ),
        migrations.AddField(
            model_name='messagedatavalue',
            name='value_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='files.file'),
        ),
    ]
