# Generated by Django 3.1.2 on 2021-08-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0116_auto_20210829_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagedataset',
            old_name='leads',
            new_name='lead',
        ),
    ]
