# Generated by Django 3.1.2 on 2021-08-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0121_auto_20210831_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedataset',
            name='intent_key',
            field=models.CharField(choices=[('NO_INTENT', 'NO_INTENT'), ('MENU', 'MENU'), ('SPEAK_HUMAN', 'SPEAK_HUMAN'), ('EXPLAIN_SERVICE', 'EXPLAIN_SERVICE'), ('REGISTER', 'REGISTER'), ('NEW_SUPPLY', 'NEW_SUPPLY'), ('NEW_DEMAND', 'NEW_DEMAND'), ('DISCUSS_W_BUYER', 'DISCUSS_W_BUYER'), ('DISCUSS_W_SELLER', 'DISCUSS_W_SELLER'), ('QNA', 'QNA'), ('FIND_ME_BUYERS', 'FIND_ME_BUYERS'), ('FIND_ME_SELLERS', 'FIND_ME_SELLERS'), ('TALK_TO_HUMAN', 'TALK_TO_HUMAN'), ('PAY', 'PAY'), ('RECOMMEND', 'RECOMMEND')], db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='intent_key',
            field=models.CharField(choices=[('NO_INTENT', 'NO_INTENT'), ('MENU', 'MENU'), ('SPEAK_HUMAN', 'SPEAK_HUMAN'), ('EXPLAIN_SERVICE', 'EXPLAIN_SERVICE'), ('REGISTER', 'REGISTER'), ('NEW_SUPPLY', 'NEW_SUPPLY'), ('NEW_DEMAND', 'NEW_DEMAND'), ('DISCUSS_W_BUYER', 'DISCUSS_W_BUYER'), ('DISCUSS_W_SELLER', 'DISCUSS_W_SELLER'), ('QNA', 'QNA'), ('FIND_ME_BUYERS', 'FIND_ME_BUYERS'), ('FIND_ME_SELLERS', 'FIND_ME_SELLERS'), ('TALK_TO_HUMAN', 'TALK_TO_HUMAN'), ('PAY', 'PAY'), ('RECOMMEND', 'RECOMMEND')], db_index=True, max_length=200),
        ),
    ]
