# Generated by Django 3.1.2 on 2021-09-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0127_auto_20210901_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedatavalue',
            name='data_key',
            field=models.CharField(choices=[('NO_DATA', 'NO_DATA'), ('STRAY_INPUT', 'STRAY_INPUT'), ('INVALID_CHOICE', 'INVALID_CHOICE'), ('MENU__FIND_BUYERS', 'MENU__FIND_BUYERS'), ('MENU__FIND_SELLERS', 'MENU__FIND_SELLERS'), ('MENU__TALK_TO_AN_EVERYBASE_AGENT', 'MENU__TALK_TO_AN_EVERYBASE_AGENT'), ('MENU__REGISTER_ME', 'MENU__REGISTER_ME')], db_index=True, max_length=200),
        ),
    ]
