# Generated by Django 3.1.2 on 2021-09-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0133_auto_20210904_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagedataset',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='messagedatavalue',
            name='value_file',
        ),
    ]
