# Generated by Django 3.1.2 on 2021-11-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0144_auto_20211105_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedataset',
            name='intent_key',
            field=models.CharField(choices=[('REGISTER', 'REGISTER'), ('LOGIN', 'LOGIN')], db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='intent_key',
            field=models.CharField(choices=[('REGISTER', 'REGISTER'), ('LOGIN', 'LOGIN')], db_index=True, max_length=200),
        ),
    ]
