# Generated by Django 3.1.2 on 2021-11-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0146_auto_20211106_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedataset',
            name='intent_key',
            field=models.CharField(choices=[('NO_INTENT', 'NO_INTENT'), ('REGISTER', 'REGISTER'), ('LOGIN', 'LOGIN'), ('CONTACT_REQUEST', 'CONTACT_REQUEST')], db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='messagedataset',
            name='message_key',
            field=models.CharField(choices=[('NO_MESSAGE', 'NO_MESSAGE'), ('DO_NOT_UNDERSTAND_OPTION', 'DO_NOT_UNDERSTAND_OPTION'), ('DO_NOT_UNDERSTAND_NUMBER', 'DO_NOT_UNDERSTAND_NUMBER'), ('DO_NOT_UNDERSTAND_EMAIL', 'DO_NOT_UNDERSTAND_EMAIL'), ('REGISTER__CONFIRM', 'REGISTER__CONFIRM'), ('LOGIN__CONFIRM', 'LOGIN__CONFIRM'), ('CONTACT_REQUEST__CONFIRM', 'CONTACT_REQUEST__CONFIRM'), ('CONTACT_REQUEST__THANK_YOU', 'CONTACT_REQUEST__THANK_YOU')], db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='intent_key',
            field=models.CharField(choices=[('NO_INTENT', 'NO_INTENT'), ('REGISTER', 'REGISTER'), ('LOGIN', 'LOGIN'), ('CONTACT_REQUEST', 'CONTACT_REQUEST')], db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='message_key',
            field=models.CharField(choices=[('NO_MESSAGE', 'NO_MESSAGE'), ('DO_NOT_UNDERSTAND_OPTION', 'DO_NOT_UNDERSTAND_OPTION'), ('DO_NOT_UNDERSTAND_NUMBER', 'DO_NOT_UNDERSTAND_NUMBER'), ('DO_NOT_UNDERSTAND_EMAIL', 'DO_NOT_UNDERSTAND_EMAIL'), ('REGISTER__CONFIRM', 'REGISTER__CONFIRM'), ('LOGIN__CONFIRM', 'LOGIN__CONFIRM'), ('CONTACT_REQUEST__CONFIRM', 'CONTACT_REQUEST__CONFIRM'), ('CONTACT_REQUEST__THANK_YOU', 'CONTACT_REQUEST__THANK_YOU')], db_index=True, max_length=200),
        ),
    ]
