# Generated by Django 3.1.2 on 2021-11-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0148_auto_20211115_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedataset',
            name='intent_key',
            field=models.CharField(choices=[('NO_INTENT', 'NO_INTENT'), ('REGISTER', 'REGISTER'), ('LOGIN', 'LOGIN'), ('CONTACT_REQUEST', 'CONTACT_REQUEST')], db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='intent_key',
            field=models.CharField(choices=[('NO_INTENT', 'NO_INTENT'), ('REGISTER', 'REGISTER'), ('LOGIN', 'LOGIN'), ('CONTACT_REQUEST', 'CONTACT_REQUEST')], db_index=True, max_length=200),
        ),
    ]
