# Generated by Django 3.1.2 on 2021-11-23 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0150_auto_20211116_1238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageDataValue',
        ),
    ]
