# Generated by Django 3.1.2 on 2021-11-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0151_delete_messagedatavalue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageDataset',
        ),
    ]
