# Generated by Django 3.1.2 on 2020-11-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0010_auto_20201106_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyaddress',
            options={'verbose_name': 'Company-address relationship', 'verbose_name_plural': 'Company-address relationships'},
        ),
    ]
