# Generated by Django 3.1.2 on 2020-11-07 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_importjob'),
        ('relationships', '0012_auto_20201107_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='import_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emails', related_query_name='emails', to='common.importjob'),
        ),
    ]
