# Generated by Django 3.1.2 on 2020-12-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0018_auto_20201120_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name_wo_postfix',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Company name without postfix'),
        ),
    ]
