# Generated by Django 3.1.2 on 2020-12-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0025_auto_20201210_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_1',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
