# Generated by Django 3.1.2 on 2020-12-14 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0028_auto_20201210_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='en_canonical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lang_versions', related_query_name='lang_versions', to='relationships.address'),
        ),
        migrations.AddField(
            model_name='address',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('CH', 'Chinese')], db_index=True, default='EN', max_length=20),
        ),
    ]
