# Generated by Django 3.1.2 on 2020-12-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0031_auto_20201215_1454'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together={('country_code', 'national_number')},
        ),
    ]
