# Generated by Django 3.1.2 on 2020-12-17 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0036_auto_20201217_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companywechatid',
            options={'verbose_name': 'Company-WeChatID', 'verbose_name_plural': 'Company-WeChatIDs'},
        ),
        migrations.AlterModelOptions(
            name='personwechatid',
            options={'verbose_name': 'Person-WeChatID type', 'verbose_name_plural': 'Person-WeChatID types'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='en_canonical',
        ),
        migrations.RemoveField(
            model_name='address',
            name='language',
        ),
    ]
