# Generated by Django 3.1.2 on 2020-12-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0037_auto_20201217_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_1_cn',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='address_2_cn',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='address_3_cn',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
