# Generated by Django 3.1.2 on 2020-12-18 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0040_auto_20201219_0008'),
    ]

    operations = [

    ]
