# Generated by Django 3.1.2 on 2021-01-14 11:08

from django.db import migrations, models
import relationships.models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0048_remove_link_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, validators=[relationships.models.validate_company_domain]),
        ),
    ]
