# Generated by Django 3.0 on 2019-12-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetcode',
            options={'ordering': ['created']},
        ),
    ]
