# Generated by Django 3.0.2 on 2020-01-23 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='active_organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_accounts', to='accounts.Organization'),
        ),
        migrations.AlterField(
            model_name='account',
            name='deleted',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='accountorganization',
            name='deleted',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='ip_address',
            field=models.GenericIPAddressField(default=None, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='verified',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='deleted',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organizationinvitationcode',
            name='recipient',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_organization_invitation_codes', to='accounts.Account'),
        ),
    ]
