# Generated by Django 3.0 on 2019-12-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191210_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
