# Generated by Django 3.0 on 2020-01-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_emailverificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationcode',
            name='user',
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='email',
            field=models.CharField(default='kevin@everybase.co', max_length=254),
            preserve_default=False,
        ),
    ]
