# Generated by Django 3.0 on 2020-01-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200113_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(default='Supply Chain Executive', max_length=100),
            preserve_default=False,
        ),
    ]
