# Generated by Django 3.0 on 2020-01-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
