# Generated by Django 3.0 on 2020-01-14 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200113_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='accepted_terms',
        ),
        migrations.RemoveField(
            model_name='account',
            name='active',
        ),
        migrations.RemoveField(
            model_name='account',
            name='role',
        ),
        migrations.RemoveField(
            model_name='account',
            name='verified_email',
        ),
    ]
