# Generated by Django 3.0 on 2020-01-15 11:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200114_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailverificationcode',
            name='used',
        ),
        migrations.RemoveField(
            model_name='passwordresetcode',
            name='user',
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='verified',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_password_reset_codes', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='OrganizationInvitationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('used', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_codes', to='accounts.Account')),
                ('recipient', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_organization_invitation_codes', to='accounts.Account')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_organization_invitation_codes', to='accounts.Account')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='AccountOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='active_organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_accounts', to='accounts.Organization'),
        ),
        migrations.AddField(
            model_name='account',
            name='organizations',
            field=models.ManyToManyField(related_name='accounts', through='accounts.AccountOrganization', to='accounts.Organization'),
        ),
    ]
