# Generated by Django 3.0 on 2020-01-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200115_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountorganization',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
