# Generated by Django 3.0 on 2020-01-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200116_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountorganization',
            options={'verbose_name': 'Account-Organization', 'verbose_name_plural': 'Account-Organizations'},
        ),
        migrations.AlterModelOptions(
            name='emailverificationcode',
            options={'verbose_name': 'Email Verification Code', 'verbose_name_plural': 'Email Verification Codes'},
        ),
        migrations.AlterModelOptions(
            name='organizationinvitationcode',
            options={'ordering': ['created'], 'verbose_name': 'Organization Invitation Code', 'verbose_name_plural': 'Organization Invitation Codes'},
        ),
        migrations.AlterModelOptions(
            name='passwordresetcode',
            options={'ordering': ['created'], 'verbose_name': 'Password Reset Code', 'verbose_name_plural': 'Password Reset Codes'},
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, default=None, null=True, verbose_name='IP Address'),
        ),
    ]
