from django.db import models

class ZeroBounceResult(models.Model):
    entry_date = models.DateField()
    email_address = models.CharField(max_length=1024, db_index=True)
    zb_status = models.CharField(max_length=1024, db_index=True)
    zb_sub_status = models.CharField(max_length=1024, db_index=True)
    zb_account = models.CharField(max_length=1024, db_index=True)
    zb_domain = models.CharField(max_length=1024, db_index=True)
    zb_first_name = models.CharField(max_length=1024)
    zb_last_name = models.CharField(max_length=1024)
    zb_gender = models.CharField(max_length=1024, db_index=True)
    zb_free_email = models.CharField(max_length=1024, db_index=True)
    zb_mx_found = models.CharField(max_length=1024, db_index=True)
    zb_mx_record = models.CharField(max_length=1024, db_index=True)
    zb_smtp_provider = models.CharField(max_length=1024, db_index=True)
    zb_did_you_mean = models.CharField(max_length=1024, db_index=True)

class WorldOfChemicalsSupplier(models.Model):
    entry_date = models.DateField()
    coy_id = models.CharField(max_length=1024, db_index=True, null=True)
    coy_name = models.CharField(max_length=1024, db_index=True, null=True)
    coy_about_html = models.TextField(blank=True, null=True)
    coy_primary_contact = models.CharField(max_length=1024, db_index=True, null=True)
    coy_addr_1 = models.CharField(max_length=1024, null=True)
    coy_addr_2 = models.CharField(max_length=1024, null=True)
    coy_city = models.CharField(max_length=1024, db_index=True, null=True)
    coy_state = models.CharField(max_length=1024, db_index=True, null=True)
    coy_country = models.CharField(max_length=1024, db_index=True, null=True)
    coy_postal = models.CharField(max_length=1024, db_index=True, null=True)
    coy_phone = models.CharField(max_length=1024, db_index=True, null=True)
    coy_phone_2 = models.CharField(max_length=1024, db_index=True, null=True)
    coy_email = models.CharField(max_length=1024, db_index=True, null=True)
    coy_owner_email = models.CharField(max_length=1024, db_index=True, null=True)
    coy_alt_email = models.CharField(max_length=1024, db_index=True, null=True)
    coy_alt_email_2 = models.CharField(max_length=1024, db_index=True, null=True)
    coy_alt_email_3 = models.CharField(max_length=1024, db_index=True, null=True)
    coy_website = models.CharField(max_length=1024, db_index=True, null=True)

class LookChemSupplier(models.Model):
    entry_date = models.DateField()
    coy_name = models.CharField(max_length=1024, db_index=True, null=True)
    contact_person = models.CharField(max_length=1024, db_index=True, null=True)
    street_person = models.CharField(max_length=1024, db_index=True, null=True)
    city = models.CharField(max_length=1024, db_index=True, null=True)
    province_state = models.CharField(max_length=1024, db_index=True, null=True)
    country_region = models.CharField(max_length=1024, db_index=True, null=True)
    zip_code = models.CharField(max_length=1024, db_index=True, null=True)
    business_type = models.CharField(max_length=1024, db_index=True, null=True)
    tel = models.CharField(max_length=1024, db_index=True, null=True)
    mobile = models.CharField(max_length=1024, db_index=True, null=True)
    email = models.CharField(max_length=1024, db_index=True, null=True)
    website = models.CharField(max_length=1024, db_index=True, null=True)
    qq = models.CharField(max_length=1024, db_index=True, null=True)

class ChemicalBookSupplier(models.Model):
    entry_date = models.DateField()
    coy_email = models.CharField(max_length=1024, db_index=True, null=True)
    source_url = models.CharField(max_length=200, db_index=True, null=True)
    coy_name = models.CharField(max_length=1024, db_index=True, null=True)
    coy_internal_href = models.CharField(max_length=1024, db_index=True, null=True)
    coy_tel = models.CharField(max_length=1024, db_index=True, null=True)
    coy_email = models.CharField(max_length=1024, db_index=True, null=True)
    coy_href = models.CharField(max_length=1024, db_index=True, null=True)
    coy_nat = models.CharField(max_length=1024, db_index=True, null=True)

class Fibre2FashionLead(models.Model):
    entry_date = models.DateField()
    url = models.CharField(max_length=1024, db_index=True, null=True)
    cat = models.CharField(max_length=1024, db_index=True, null=True)
    subcat = models.CharField(max_length=1024, db_index=True, null=True)
    title = models.CharField(max_length=1024, db_index=True, null=True)
    ref_no = models.CharField(max_length=1024, db_index=True, null=True)
    biz_lead = models.CharField(max_length=1024, db_index=True, null=True)
    coy_name = models.CharField(max_length=1024, db_index=True, null=True)
    coy_addr = models.CharField(max_length=1024, db_index=True, null=True)
    coy_desc = models.TextField(null=True)
    coy_email = models.CharField(max_length=1024, db_index=True, null=True)
    prod_info_html = models.TextField(null=True)