# Generated by Django 3.1.2 on 2020-12-07 07:19

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcategorypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategorypage',
            name='introduction',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
