# Generated by Django 3.1.2 on 2020-10-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_auto_20201022_1003'),
        ('growth', '0026_worldofchemicalresultcompany'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorldOfChemicalResultCompany',
            new_name='WorldOfChemicalsResultCompany',
        ),
    ]
