# Generated by Django 3.1.2 on 2020-11-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0046_auto_20201104_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalbookresult',
            name='harvested',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='coy_email',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='coy_href',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='coy_internal_href',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='coy_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='coy_nat',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='coy_tel',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='source_url',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
