# Generated by Django 3.1.2 on 2020-11-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0049_auto_20201104_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='OKChemResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('harvested', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('request', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'OKChem result',
                'verbose_name_plural': 'OKChem results',
            },
        ),
    ]
