# Generated by Django 3.1.2 on 2020-11-07 09:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0011_auto_20201107_1511'),
        ('growth', '0054_auto_20201106_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerobounceresult',
            name='batch_uuid',
            field=models.UUIDField(db_index=True, default='123e4567-e89b-12d3-a456-426614174000', editable=False, unique=True, verbose_name='Batch UUID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zerobounceresult',
            name='did_you_mean_email',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='zero_bounce_result_did_you_mean_emails', related_query_name='zero_bounce_result_did_you_mean_emails', to='relationships.email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='account',
            field=models.CharField(db_index=True, default='No account', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='did_you_mean',
            field=models.EmailField(db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='domain',
            field=models.CharField(db_index=True, default='No domain', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='email',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='zero_bounce_result_emails', related_query_name='zero_bounce_result_emails', to='relationships.email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='email_address',
            field=models.EmailField(db_index=True, default='no@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='free_email',
            field=models.BooleanField(db_index=True, default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='gender',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='generated',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='mx_found',
            field=models.BooleanField(db_index=True, default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='mx_record',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='smtp_provider',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='status',
            field=models.CharField(choices=[('Valid', 'valid'), ('Invalid', 'invalid'), ('Catch-All', 'catch-all'), ('Spamtrap', 'spamtrap'), ('Abuse', 'abuse'), ('Do Not Mail', 'do_not_mail'), ('Unknown', 'unknown')], db_index=True, default='No status', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='sub_status',
            field=models.CharField(choices=[('Anti-Spam System', 'antispam_system'), ('Does Not Accept Mail', 'does_not_accept_mail'), ('Exception Occurred', 'exception_occurred'), ('Failed SMTP Connection', 'failed_smtp_connection'), ('Failed Syntax Check', 'failed_syntax_check'), ('Forcible Disconnect', 'forcible_disconnect'), ('Global Suppression', 'global_suppression'), ('Greylisted', 'greylisted'), ('Leading Period Removed', 'leading_period_removed'), ('Mail Server Did Not Respond', 'mail_server_did_not_respond'), ('Mail Server Temporary Error', 'mail_server_temporary_error'), ('Mailbox Quota Exceeded', 'mailbox_quota_exceeded'), ('Mailbox Not Found', 'mailbox_not_found'), ('No DNS Entries', 'no_dns_entries'), ('Possible Traps', 'possible_traps'), ('Possible Typo', 'possible_typo'), ('Role-Based', 'role_based'), ('Timeout Exceeded', 'timeout_exceeded'), ('Unroutable IP Address', 'unroutable_ip_address'), ('Alias Address', 'alias_address'), ('Role-Based Catch-All', 'role_based_catch_all'), ('Disposable', 'disposable'), ('Toxix', 'toxic')], db_index=True, max_length=50, null=True),
        ),
    ]
