# Generated by Django 3.1.2 on 2020-11-09 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0013_email_import_job'),
        ('growth', '0058_auto_20201108_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerobounceresult',
            name='did_you_mean_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zero_bounce_result_did_you_mean_emails', related_query_name='zero_bounce_result_did_you_mean_emails', to='relationships.email'),
        ),
    ]
