# Generated by Django 3.1.2 on 2020-11-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0061_auto_20201109_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerobounceresult',
            name='email_str',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
