# Generated by Django 3.1.2 on 2020-11-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0069_auto_20201111_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibre2fashionbuyingoffer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionsellingoffer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
