# Generated by Django 3.1.2 on 2020-11-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0076_auto_20201114_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='okchemresult',
            name='import_job',
        ),
        migrations.AlterField(
            model_name='fibre2fashionbuyingoffer',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionsellingoffer',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
