# Generated by Django 3.1.2 on 2020-11-16 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0080_okchembuyingrequest_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fibre2fashionbuyingoffer',
            old_name='source_link',
            new_name='source_url',
        ),
        migrations.RenameField(
            model_name='fibre2fashionsellingoffer',
            old_name='source_link',
            new_name='source_url',
        ),
    ]
