# Generated by Django 3.1.2 on 2020-11-16 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0015_auto_20201110_1148'),
        ('growth', '0084_chemicalclusterofsingaporeproduct_chemicalclusterofsingaporeservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmasscampaignresult',
            name='invalid_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gmass_campaign_results', related_query_name='gmass_campaign_results', to='relationships.invalidemail'),
        ),
        migrations.AlterField(
            model_name='gmasscampaignresult',
            name='clicks',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='gmasscampaignresult',
            name='gmass_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gmass_campaign_results', related_query_name='gmass_campaign_results', to='growth.gmasscampaign'),
        ),
        migrations.AlterField(
            model_name='gmasscampaignresult',
            name='opens',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
