# Generated by Django 3.1.2 on 2020-11-23 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0018_auto_20201120_1304'),
        ('growth', '0103_gmassemailstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmassemailstatus',
            name='invalid_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gmass_email_statuses', related_query_name='gmass_email_statuses', to='relationships.invalidemail'),
        ),
        migrations.AlterField(
            model_name='gmassemailstatus',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gmass_email_statuses', related_query_name='gmass_email_statuses', to='relationships.email'),
        ),
    ]
