# Generated by Django 3.0.5 on 2020-04-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20200403_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerobounceresult',
            name='zb_free_email',
            field=models.CharField(db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='zb_mx_found',
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
