# Generated by Django 3.0.5 on 2020-04-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_worldofchemicalssupplier_coy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalbooksupplier',
            name='coy_email',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbooksupplier',
            name='coy_href',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbooksupplier',
            name='coy_internal_href',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbooksupplier',
            name='coy_name',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbooksupplier',
            name='coy_nat',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbooksupplier',
            name='coy_tel',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbooksupplier',
            name='source_url',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionlead',
            name='biz_lead',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionlead',
            name='cat',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionlead',
            name='coy_addr',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionlead',
            name='coy_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionlead',
            name='coy_email',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionlead',
            name='coy_name',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionlead',
            name='prod_info_html',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionlead',
            name='ref_no',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionlead',
            name='subcat',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionlead',
            name='title',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionlead',
            name='url',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemsupplier',
            name='business_type',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemsupplier',
            name='city',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemsupplier',
            name='contact_person',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemsupplier',
            name='country_region',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemsupplier',
            name='coy_name',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemsupplier',
            name='email',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemsupplier',
            name='mobile',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemsupplier',
            name='province_state',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemsupplier',
            name='qq',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemsupplier',
            name='street_person',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemsupplier',
            name='tel',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemsupplier',
            name='website',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemsupplier',
            name='zip_code',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_about_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_addr_1',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_addr_2',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_alt_email',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_alt_email_2',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_alt_email_3',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_city',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_country',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_email',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_id',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_name',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_owner_email',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_phone',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_phone_2',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_postal',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_primary_contact',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_state',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_website',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
    ]
