# Generated by Django 3.1.2 on 2021-04-23 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioInboundMessageMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('content_type', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.twilioinboundmessage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwilioInboundMessageLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('payload', models.TextField(db_index=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.twilioinboundmessage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
