# Generated by Django 3.1.2 on 2021-04-23 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0028_auto_20210422_1752'),
        ('chat', '0002_twilioinboundmessagelogentry_twilioinboundmessagemedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMessageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('is_disabled', models.BooleanField(db_index=True)),
                ('grouped', models.DateTimeField(db_index=True)),
                ('initial_body', models.TextField(db_index=True)),
                ('twilio_inbound_messages', models.ManyToManyField(db_index=True, related_name='inbound_message_groups', related_query_name='inbound_message_groups', to='chat.TwilioInboundMessage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InboundMessageGroupRelationshipTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('version', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MethodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='twilioinboundmessagelogentry',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_entries', related_query_name='log_entries', to='chat.twilioinboundmessage'),
        ),
        migrations.AlterField(
            model_name='twilioinboundmessagemedia',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medias', related_query_name='medias', to='chat.twilioinboundmessage'),
        ),
        migrations.CreateModel(
            name='OperationMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
                ('applied', models.DateTimeField(db_index=True)),
                ('order', models.IntegerField(db_index=True)),
                ('output_body', models.TextField(blank=True, db_index=True, null=True)),
                ('inbound_message_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_methods', related_query_name='operation_methods', to='chat.inboundmessagegroup')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_methods', related_query_name='operation_methods', to='chat.method')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='method',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='methods', related_query_name='methods', to='chat.methodcategory'),
        ),
        migrations.CreateModel(
            name='InboundMessageGroupRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('associated', models.DateTimeField(db_index=True)),
                # ('demand_quotes', models.ManyToManyField(db_index=True, related_name='inbound_message_group_relationships', related_query_name='inbound_message_group_relationships', to='relationships.DemandQuote')),
                ('demands', models.ManyToManyField(db_index=True, related_name='inbound_message_group_relationships', related_query_name='inbound_message_group_relationships', to='relationships.Demand')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_message_group_relationships', related_query_name='inbound_message_group_relationships', to='chat.inboundmessagegroup')),
                ('supplies', models.ManyToManyField(db_index=True, related_name='inbound_message_group_relationships', related_query_name='inbound_message_group_relationships', to='relationships.Supply')),
                # ('supply_quotes', models.ManyToManyField(db_index=True, related_name='inbound_message_group_relationships', related_query_name='inbound_message_group_relationships', to='relationships.SupplyQuote')),
                ('tags', models.ManyToManyField(db_index=True, related_name='inbound_message_group_relationships', related_query_name='inbound_message_group_relationships', to='chat.InboundMessageGroupRelationshipTag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
                ('applied', models.DateTimeField(db_index=True)),
                ('order', models.IntegerField(db_index=True)),
                ('inbound_message_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grouping_methods', related_query_name='grouping_methods', to='chat.inboundmessagegroup')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grouping_methods', related_query_name='grouping_methods', to='chat.method')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
