# Generated by Django 3.1.2 on 2021-04-27 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210427_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twiliostatuscallback',
            name='log_entry',
        ),
        migrations.AddField(
            model_name='twiliostatuscallbacklogentry',
            name='callback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='log_entries', related_query_name='log_entries', to='chat.twiliostatuscallback'),
        ),
    ]
