# Generated by Django 3.1.2 on 2021-04-28 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('processor', '0002_remove_basetruth_method'),
        ('chat', '0008_method_is_function'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundmessagegroup',
            name='twilio_inbound_messages',
        ),
        # migrations.RemoveField(
        #     model_name='inboundmessagegrouprelationship',
        #     name='demand_quotes',
        # ),
        migrations.RemoveField(
            model_name='inboundmessagegrouprelationship',
            name='demands',
        ),
        migrations.RemoveField(
            model_name='inboundmessagegrouprelationship',
            name='group',
        ),
        migrations.RemoveField(
            model_name='inboundmessagegrouprelationship',
            name='supplies',
        ),
        # migrations.RemoveField(
        #     model_name='inboundmessagegrouprelationship',
        #     name='supply_quotes',
        # ),
        migrations.RemoveField(
            model_name='inboundmessagegrouprelationship',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='method',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='operationmethod',
            name='inbound_message_group',
        ),
        migrations.RemoveField(
            model_name='operationmethod',
            name='method',
        ),
        migrations.DeleteModel(
            name='GroupingMethod',
        ),
        migrations.DeleteModel(
            name='InboundMessageGroup',
        ),
        migrations.DeleteModel(
            name='InboundMessageGroupRelationship',
        ),
        migrations.DeleteModel(
            name='InboundMessageGroupRelationshipTag',
        ),
        migrations.DeleteModel(
            name='Method',
        ),
        migrations.DeleteModel(
            name='MethodTag',
        ),
        migrations.DeleteModel(
            name='OperationMethod',
        ),
    ]
