# Generated by Django 3.1.2 on 2021-05-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20210514_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='twilioinboundmessage',
            name='sms_status',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
