# Generated by Django 3.1.2 on 2021-05-15 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0062_auto_20210513_1423'),
        ('chat', '0014_auto_20210514_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='twilioinboundmessage',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='twilio_inbound_message_from_users', related_query_name='twilio_inbound_message_from_users', to='relationships.user'),
        ),
        migrations.AddField(
            model_name='twilioinboundmessage',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='twilio_inbound_message_to_users', related_query_name='twilio_inbound_message_to_users', to='relationships.user'),
        ),
    ]
