# Generated by Django 3.1.2 on 2021-05-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_delete_userchatcontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('intent_type', models.CharField(db_index=True, max_length=200)),
                ('step_type', models.CharField(db_index=True, max_length=200)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intent_steps', related_query_name='intent_steps', to='chat.twilioinboundmessage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntentStepExtractedString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('value', models.CharField(db_index=True, max_length=200)),
                ('is_valid', models.BooleanField(db_index=True)),
                ('intent_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intent_step_extracted_strings', related_query_name='intent_step_extracted_strings', to='chat.intentstep')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntentStepExtractedFloat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('value', models.FloatField(db_index=True)),
                ('is_valid', models.BooleanField(db_index=True)),
                ('intent_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intent_step_extracted_floats', related_query_name='intent_step_extracted_floats', to='chat.intentstep')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntentStepExtractedBoolean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('value', models.BooleanField(db_index=True)),
                ('is_valid', models.BooleanField(db_index=True)),
                ('intent_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intent_step_extracted_booleans', related_query_name='intent_step_extracted_booleans', to='chat.intentstep')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
