# Generated by Django 3.1.2 on 2021-05-23 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_intentstep_intentstepextractedboolean_intentstepextractedfloat_intentstepextractedstring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('intent_key', models.CharField(db_index=True, max_length=200)),
                ('message_key', models.CharField(db_index=True, max_length=200)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intent_steps', related_query_name='intent_steps', to='chat.twilioinboundmessage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContextBoolean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('value', models.BooleanField(db_index=True)),
                ('is_valid', models.BooleanField(db_index=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booleans', related_query_name='booleans', to='chat.context')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContextFloat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('value', models.FloatField(db_index=True)),
                ('is_valid', models.BooleanField(db_index=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='floats', related_query_name='floats', to='chat.context')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContextString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('value', models.CharField(db_index=True, max_length=200)),
                ('is_valid', models.BooleanField(db_index=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strings', related_query_name='strings', to='chat.context')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='intentstepextractedboolean',
            name='intent_step',
        ),
        migrations.RemoveField(
            model_name='intentstepextractedfloat',
            name='intent_step',
        ),
        migrations.RemoveField(
            model_name='intentstepextractedstring',
            name='intent_step',
        ),
        migrations.DeleteModel(
            name='IntentStep',
        ),
        migrations.DeleteModel(
            name='IntentStepExtractedBoolean',
        ),
        migrations.DeleteModel(
            name='IntentStepExtractedFloat',
        ),
        migrations.DeleteModel(
            name='IntentStepExtractedString',
        ),
    ]
