# Generated by Django 3.1.2 on 2021-05-23 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_auto_20210523_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDataBoolean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('value', models.BooleanField(db_index=True)),
                ('is_valid', models.BooleanField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageDataFloat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('value', models.FloatField(db_index=True)),
                ('is_valid', models.BooleanField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageDataString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('value', models.CharField(db_index=True, max_length=200)),
                ('is_valid', models.BooleanField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='contextfloat',
            name='context',
        ),
        migrations.RemoveField(
            model_name='contextstring',
            name='context',
        ),
        migrations.RenameModel(
            old_name='Context',
            new_name='MessageDataset',
        ),
        migrations.DeleteModel(
            name='ContextBoolean',
        ),
        migrations.DeleteModel(
            name='ContextFloat',
        ),
        migrations.DeleteModel(
            name='ContextString',
        ),
        migrations.AddField(
            model_name='messagedatastring',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strings', related_query_name='strings', to='chat.messagedataset'),
        ),
        migrations.AddField(
            model_name='messagedatafloat',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='floats', related_query_name='floats', to='chat.messagedataset'),
        ),
        migrations.AddField(
            model_name='messagedataboolean',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booleans', related_query_name='booleans', to='chat.messagedataset'),
        ),
    ]
