# Generated by Django 3.1.2 on 2021-05-24 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_auto_20210523_2010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagedataset',
            unique_together={('intent_key', 'message_key', 'message')},
        ),
    ]
