# Generated by Django 3.1.2 on 2021-05-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_auto_20210525_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedataboolean',
            name='is_valid',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagedatafloat',
            name='is_valid',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagedatastring',
            name='is_valid',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
