# Generated by Django 3.1.2 on 2021-05-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_auto_20210526_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedataset',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_datasets', related_query_name='message_datasets', to='chat.twilioinboundmessage'),
        ),
    ]
