# Generated by Django 3.1.2 on 2021-05-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0035_auto_20210527_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedatavalue',
            name='value_boolean',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagedatavalue',
            name='value_float',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagedatavalue',
            name='value_string',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
