# Generated by Django 3.1.2 on 2020-11-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20201109_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTimestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
