# Generated by Django 3.1.2 on 2020-10-22 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_auto_20201022_1003'),
        ('growth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmasscampaignresult',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gmass_campaign_results', related_query_name='gmass_campaign_results', to='relationships.email'),
        ),
        migrations.AlterField(
            model_name='gmasscampaignresult',
            name='gmass_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', related_query_name='results', to='growth.gmasscampaign'),
        ),
    ]
