# Generated by Django 3.1.2 on 2020-10-23 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_auto_20201022_1003'),
        ('growth', '0007_auto_20201023_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalBookResultEmailType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField(blank=True, null=True, verbose_name='Details in Markdown')),
                ('programmatic_key', models.CharField(blank=True, max_length=100, null=True)),
                ('programmatic_details_md', models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown')),
            ],
            options={
                'verbose_name': 'ChemicalBookResult-Email Type',
                'verbose_name_plural': 'ChemicalBookResult-Email Types',
            },
        ),
        migrations.CreateModel(
            name='ChemicalBookResultEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('details_md', models.TextField(verbose_name='Details in Markdown')),
                ('chemical_book_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemicalbookresult_email_relationships', related_query_name='chemicalbookresult_email_relationships', to='growth.chemicalbookresult')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemicalbookresult_email_relationships', related_query_name='chemicalbookresult_email_relationships', to='relationships.email')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemicalbookresult_email_relationships', related_query_name='chemicalbookresult_email_relationships', to='growth.chemicalbookresultemailtype', verbose_name='ChemicalBookResult-Email Type')),
            ],
            options={
                'verbose_name': 'ChemicalBookResult-Email Relationship',
                'verbose_name_plural': 'ChemicalBookResult-Email Relationships',
            },
        ),
        migrations.AddField(
            model_name='chemicalbookresult',
            name='email',
            field=models.ManyToManyField(related_name='chemical_book_results', related_query_name='chemical_book_results', through='growth.ChemicalBookResultEmail', to='relationships.Email'),
        ),
    ]
