# Generated by Django 3.1.2 on 2020-10-23 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_auto_20201022_1003'),
        ('growth', '0021_worldofchemicalsresultlinktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldOfChemicalResultLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('details_md', models.TextField(verbose_name='Details in Markdown')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worldofchemicalsresult_relationships', related_query_name='worldofchemicalsresult_relationships', to='relationships.link')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worldofchemicalsresult_link_relationships', related_query_name='worldofchemicalsresult_link_relationships', to='growth.worldofchemicalsresultlinktype', verbose_name='WorldOfChemicalsResult-Link Type')),
                ('world_of_chemicals_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worldofchemicalsresult_link_relationships', related_query_name='worldofchemicalsresult_link_relationships', to='growth.worldofchemicalsresult')),
            ],
            options={
                'verbose_name': 'WorldOfChemicalsResult-Link Relationship',
                'verbose_name_plural': 'WorldOfChemicalsResult-Link Relationships',
            },
        ),
    ]
