# Generated by Django 3.1.2 on 2020-11-10 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20201109_1500'),
        ('relationships', '0014_invalidemail'),
        ('growth', '0062_auto_20201109_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fibre2FashionBuyingOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('harvested', models.DateTimeField(db_index=True)),
                ('source_link', models.CharField(db_index=True, max_length=300)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('sub_category', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('reference_no', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('email_str', models.CharField(db_index=True, max_length=100)),
                ('company_name', models.CharField(db_index=True, max_length=100)),
                ('product_info_html', models.TextField()),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fibre2fashion_buying_offer_emails', related_query_name='fibre2fashion_buying_offer_emails', to='relationships.email')),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fibre2fashion_buying_offers', related_query_name='fibre2fashion_buying_offers', to='common.importjob')),
                ('invalid_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fibre2fashion_buying_offer_invalid_emails', related_query_name='fibre2fashion_buying_offer_invalid_emails', to='relationships.invalidemail')),
            ],
            options={
                'verbose_name': 'Fibre2Fashion buying offer',
                'verbose_name_plural': 'Fibre2Fashion buying offers',
            },
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='did_you_mean',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='did_you_mean_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zero_bounce_result_did_you_mean_emails', related_query_name='zero_bounce_result_did_you_mean_emails', to='relationships.email'),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zero_bounce_result_emails', related_query_name='zero_bounce_result_emails', to='relationships.email'),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='gender',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zero_bounce_results', related_query_name='zero_bounce_results', to='common.importjob'),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='invalid_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zero_bounce_result_invalid_emails', related_query_name='zero_bounce_result_invalid_emails', to='relationships.invalidemail'),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='mx_record',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='smtp_provider',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='sub_status',
            field=models.CharField(blank=True, choices=[('antispam_system', 'Anti-Spam System'), ('does_not_accept_mail', 'Does Not Accept Mail'), ('exception_occurred', 'Exception Occurred'), ('failed_smtp_connection', 'Failed SMTP Connection'), ('failed_syntax_check', 'Failed Syntax Check'), ('forcible_disconnect', 'Forcible Disconnect'), ('global_suppression', 'Global Suppression'), ('greylisted', 'Greylisted'), ('leading_period_removed', 'Leading Period Removed'), ('mail_server_did_not_respond', 'Mail Server Did Not Respond'), ('mail_server_temporary_error', 'Mail Server Temporary Error'), ('mailbox_quota_exceeded', 'Mailbox Quota Exceeded'), ('mailbox_not_found', 'Mailbox Not Found'), ('no_dns_entries', 'No DNS Entries'), ('possible_traps', 'Possible Traps'), ('possible_typo', 'Possible Typo'), ('role_based', 'Role-Based'), ('timeout_exceeded', 'Timeout Exceeded'), ('unroutable_ip_address', 'Unroutable IP Address'), ('alias_address', 'Alias Address'), ('role_based_catch_all', 'Role-Based Catch-All'), ('disposable', 'Disposable'), ('toxic', 'Toxic')], db_index=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Fibre2FashionResult',
        ),
    ]
