# Generated by Django 3.1.2 on 2020-11-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0065_auto_20201110_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fibre2fashionbuyingoffer',
            name='company_name',
        ),
    ]
