# Generated by Django 3.1.2 on 2020-11-13 06:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20201109_1500'),
        ('relationships', '0015_auto_20201110_1148'),
        ('growth', '0073_auto_20201112_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookchemresultaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='lookchemresultaddress',
            name='lookchem_result',
        ),
        migrations.RemoveField(
            model_name='lookchemresultaddress',
            name='rtype',
        ),
        migrations.RemoveField(
            model_name='lookchemresultcompany',
            name='company',
        ),
        migrations.RemoveField(
            model_name='lookchemresultcompany',
            name='lookchem_result',
        ),
        migrations.RemoveField(
            model_name='lookchemresultcompany',
            name='rtype',
        ),
        migrations.RemoveField(
            model_name='lookchemresultemail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lookchemresultemail',
            name='lookchem_result',
        ),
        migrations.RemoveField(
            model_name='lookchemresultemail',
            name='rtype',
        ),
        migrations.RemoveField(
            model_name='lookchemresultlink',
            name='link',
        ),
        migrations.RemoveField(
            model_name='lookchemresultlink',
            name='lookchem_result',
        ),
        migrations.RemoveField(
            model_name='lookchemresultlink',
            name='rtype',
        ),
        migrations.DeleteModel(
            name='LookChemResultLinkType',
        ),
        migrations.RemoveField(
            model_name='lookchemresultperson',
            name='lookchem_result',
        ),
        migrations.RemoveField(
            model_name='lookchemresultperson',
            name='person',
        ),
        migrations.RemoveField(
            model_name='lookchemresultperson',
            name='rtype',
        ),
        migrations.RemoveField(
            model_name='lookchemresultphonenumber',
            name='lookchem_result',
        ),
        migrations.RemoveField(
            model_name='lookchemresultphonenumber',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='lookchemresultphonenumber',
            name='rtype',
        ),
        migrations.AlterModelOptions(
            name='lookchemresult',
            options={'verbose_name': 'LookChem Result', 'verbose_name_plural': 'LookChem Results'},
        ),
        migrations.RemoveField(
            model_name='lookchemresult',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='lookchemresult',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='lookchemresult',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='lookchemresult',
            name='links',
        ),
        migrations.RemoveField(
            model_name='lookchemresult',
            name='persons',
        ),
        migrations.RemoveField(
            model_name='lookchemresult',
            name='phone_numbers',
        ),
        migrations.AddField(
            model_name='lookchemresult',
            name='email_str',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lookchemresult',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='look_chem_results', related_query_name='look_chem_results', to='common.importjob'),
        ),
        migrations.AddField(
            model_name='lookchemresult',
            name='invalid_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='look_chem_result_invalid_emails', related_query_name='look_chem_result_invalid_emails', to='relationships.invalidemail'),
        ),
        migrations.AlterField(
            model_name='lookchemresult',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='look_chem_result_emails', related_query_name='look_chem_result_emails', to='relationships.email'),
        ),
        migrations.AlterField(
            model_name='lookchemresult',
            name='harvested',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lookchemresult',
            name='street_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LookChemResultAddress',
        ),
        migrations.DeleteModel(
            name='LookChemResultAddressType',
        ),
        migrations.DeleteModel(
            name='LookChemResultCompany',
        ),
        migrations.DeleteModel(
            name='LookChemResultCompanyType',
        ),
        migrations.DeleteModel(
            name='LookChemResultEmail',
        ),
        migrations.DeleteModel(
            name='LookChemResultEmailType',
        ),
        migrations.DeleteModel(
            name='LookChemResultLink',
        ),
        migrations.DeleteModel(
            name='LookChemResultPerson',
        ),
        migrations.DeleteModel(
            name='LookChemResultPersonType',
        ),
        migrations.DeleteModel(
            name='LookChemResultPhoneNumber',
        ),
        migrations.DeleteModel(
            name='LookChemResultPhoneNumberType',
        ),
    ]
