# Generated by Django 3.1.2 on 2020-11-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0015_auto_20201110_1148'),
        ('common', '0010_auto_20201109_1500'),
        ('growth', '0074_auto_20201113_1427'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChemicalBookResult',
            new_name='ChemicalBookSupplier',
        ),
        migrations.RenameModel(
            old_name='LookChemResult',
            new_name='LookChemSupplier',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresultcountry',
            name='chemical_book_result',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresultcountry',
            name='country',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresultcountry',
            name='rtype',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresultemail',
            name='chemical_book_result',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresultemail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresultemail',
            name='rtype',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresultlink',
            name='chemical_book_result',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresultlink',
            name='link',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresultlink',
            name='rtype',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresultphonenumber',
            name='chemical_book_result',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresultphonenumber',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresultphonenumber',
            name='rtype',
        ),
        migrations.AlterModelOptions(
            name='lookchemsupplier',
            options={'verbose_name': 'LookChem supplier', 'verbose_name_plural': 'LookChem suppliers'},
        ),
        migrations.DeleteModel(
            name='ChemicalBookResultCompany',
        ),
        migrations.DeleteModel(
            name='ChemicalBookResultCompanyType',
        ),
        migrations.DeleteModel(
            name='ChemicalBookResultCountry',
        ),
        migrations.DeleteModel(
            name='ChemicalBookResultCountryType',
        ),
        migrations.DeleteModel(
            name='ChemicalBookResultEmail',
        ),
        migrations.DeleteModel(
            name='ChemicalBookResultEmailType',
        ),
        migrations.DeleteModel(
            name='ChemicalBookResultLink',
        ),
        migrations.DeleteModel(
            name='ChemicalBookResultLinkType',
        ),
        migrations.DeleteModel(
            name='ChemicalBookResultPhoneNumber',
        ),
        migrations.DeleteModel(
            name='ChemicalBookResultPhoneNumberType',
        ),
    ]
