# Generated by Django 3.1.2 on 2020-11-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0098_remove_gmasscampaignresult_gmass_campaign_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmasscampaign',
            name='report_url',
            field=models.URLField(db_index=True, default='https://everybase.co'),
            preserve_default=False,
        ),
    ]
