# Generated by Django 3.1.2 on 2020-11-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0099_gmasscampaign_report_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmasscampaign',
            name='report_accessed_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='gmasscampaign',
            name='report_last_accessed',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
