# Generated by Django 3.1.2 on 2020-11-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0018_auto_20201120_1304'),
        ('growth', '0102_auto_20201123_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmassEmailStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('bounced', models.BooleanField(blank=True, db_index=True, null=True)),
                ('bounce_reason', models.TextField(blank=True, null=True)),
                ('unsubscribed', models.BooleanField(blank=True, db_index=True, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gmass_email_status', related_query_name='gmass_email_status', to='relationships.email')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
