# Generated by Django 3.1.2 on 2020-11-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0107_auto_20201124_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmasscampaign',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
