# Generated by Django 3.0.5 on 2020-10-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeresult',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionresult',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gmasscampaign',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gmasscampaignresult',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcedemail',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
