# Generated by Django 3.0.5 on 2020-10-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemicalclusterofsingaporeresult',
            options={'verbose_name': 'ChemicalClusterOfSingapore result', 'verbose_name_plural': 'ChemicalClusterOfSingapore results'},
        ),
        migrations.AlterModelOptions(
            name='fibre2fashionresult',
            options={'verbose_name': 'Fibre2Fashion result', 'verbose_name_plural': 'Fibre2Fashion results'},
        ),
        migrations.AlterModelOptions(
            name='zerobounceresult',
            options={'verbose_name': 'ZeroBounce result', 'verbose_name_plural': 'ZeroBounce results'},
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeresult',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeresult',
            name='fax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeresult',
            name='source_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeresult',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeresult',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
