# Generated by Django 3.1.2 on 2021-12-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookchemsupplier',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
