# Generated by Django 3.1.2 on 2022-05-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0002_auto_20211215_0207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailStatus',
        ),
    ]
