# Generated by Django 3.0.5 on 2020-10-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0002_auto_20201016_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalclusterofsingaporeresult',
            name='address_str',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
