# Generated by Django 3.1.2 on 2021-08-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0003_note_note_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(blank=True, choices=[('onboarding', 'Onboarding'), ('onboarding_seller', 'Onboarding Seller'), ('onboarding_buyer', 'Onboarding Buyer'), ('information', 'Information'), ('task', 'Task')], max_length=100, null=True),
        ),
    ]
