# Generated by Django 3.0.5 on 2020-10-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0003_chemicalclusterofsingaporeresult_address_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalclusterofsingaporeresult',
            name='email_str',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
