# Generated by Django 3.1.2 on 2021-08-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0004_auto_20210811_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(blank=True, choices=[('onboarding', 'Onboarding'), ('information', 'Information'), ('task', 'Task')], max_length=100, null=True),
        ),
    ]
