# Generated by Django 3.0.5 on 2020-10-14 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0020_auto_20201014_1454'),
        ('growth', '0004_auto_20201014_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerobounceresult',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zero_bounce_results', related_query_name='zero_bounce_results', to='relationships.Email', verbose_name=True),
        ),
    ]
