# Generated by Django 3.1.2 on 2020-10-23 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_auto_20201022_1003'),
        ('growth', '0004_auto_20201023_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalBookResultLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('details_md', models.TextField(verbose_name='Details in Markdown')),
                ('chemical_book_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemicalbookresult_link_relationships', related_query_name='chemicalbookresult_link_relationships', to='growth.chemicalbookresult')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemicalbookresult_link_relationships', related_query_name='chemicalbookresult_link_relationships', to='relationships.link')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemicalbookresult_link_relationships', related_query_name='chemicalbookresult_link_relationships', to='growth.chemicalbookresultlinktype', verbose_name='ChemicalBookResult-Link Type')),
            ],
            options={
                'verbose_name': 'ChemicalBookResult-Link Relationship',
                'verbose_name_plural': 'ChemicalBookResult-Link Relationships',
            },
        ),
        migrations.AddField(
            model_name='chemicalbookresult',
            name='links',
            field=models.ManyToManyField(related_name='chemical_book_results', related_query_name='chemical_book_results', through='growth.ChemicalBookResultLink', to='relationships.Link'),
        ),
    ]
