# Generated by Django 3.0.5 on 2020-10-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0004_chemicalclusterofsingaporeresult_email_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeresult',
            name='source_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
