# Generated by Django 3.1.2 on 2020-10-23 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_auto_20201022_1003'),
        ('growth', '0005_auto_20201023_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalBookResultCompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField(blank=True, null=True, verbose_name='Details in Markdown')),
                ('programmatic_key', models.CharField(blank=True, max_length=100, null=True)),
                ('programmatic_details_md', models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown')),
            ],
            options={
                'verbose_name': 'ChemicalBookResult-Company Type',
                'verbose_name_plural': 'ChemicalBookResult-Company Types',
            },
        ),
        migrations.CreateModel(
            name='ChemicalBookResultCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('details_md', models.TextField(verbose_name='Details in Markdown')),
                ('chemical_book_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemicalbookresult_company_relationships', related_query_name='chemicalbookresult_company_relationships', to='growth.chemicalbookresult')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemicalbookresult_company_relationships', related_query_name='chemicalbookresult_company_relationships', to='relationships.company')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemicalbookresult_company_relationships', related_query_name='chemicalbookresult_company_relationships', to='growth.chemicalbookresultcompanytype', verbose_name='ChemicalBookResult-Company Type')),
            ],
            options={
                'verbose_name': 'ChemicalBookResult-Company Relationship',
                'verbose_name_plural': 'ChemicalBookResult-Company Relationships',
            },
        ),
        migrations.AddField(
            model_name='chemicalbookresult',
            name='companies',
            field=models.ManyToManyField(related_name='chemical_book_results', related_query_name='chemical_book_results', through='growth.ChemicalBookResultCompany', to='relationships.Company'),
        ),
    ]
