# Generated by Django 3.0.5 on 2020-10-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0005_auto_20201016_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeresult',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
