# Generated by Django 3.1.2 on 2021-08-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0102_remove_email_name'),
        ('growth', '0005_auto_20210811_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='growth_notes', related_query_name='growth_notes', to='relationships.user'),
            preserve_default=False,
        ),
    ]
