# Generated by Django 3.0.5 on 2020-10-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0006_auto_20201016_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gmasscampaignresult',
            old_name='gmass_compaign',
            new_name='gmass_campaign',
        ),
    ]
