# Generated by Django 3.1.2 on 2021-08-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0007_auto_20210811_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='email',
        ),
        migrations.RemoveField(
            model_name='note',
            name='phone_number',
        ),
    ]
