# Generated by Django 3.0.5 on 2020-10-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0007_auto_20201016_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmasscampaignresult',
            name='name_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name_1'),
        ),
    ]
