# Generated by Django 3.0.5 on 2020-10-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0008_auto_20201016_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmasscampaignresult',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
