# Generated by Django 3.1.2 on 2021-08-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0008_auto_20210811_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
