# Generated by Django 3.0.5 on 2020-10-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0009_gmasscampaignresult_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibre2fashionresult',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='fibre2fashionresult',
            name='source_link',
            field=models.URLField(),
        ),
    ]
