# Generated by Django 3.0.5 on 2020-10-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0010_auto_20201016_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerobounceresult',
            name='email_address',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
