# Generated by Django 3.1.2 on 2021-08-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0010_auto_20210821_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notetag',
            name='notes',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='tags', related_query_name='tags', to='growth.Note'),
        ),
    ]
