# Generated by Django 3.1.2 on 2021-08-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0012_auto_20210821_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notestatus',
            options={'verbose_name': 'Note status', 'verbose_name_plural': 'Note statuses'},
        ),
    ]
