# Generated by Django 3.0.5 on 2020-10-16 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
        ('growth', '0012_auto_20201017_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerobounceresult',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zero_bounce_results', related_query_name='zero_bounce_results', to='relationships.Email'),
        ),
    ]
