# Generated by Django 3.0.5 on 2020-10-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0013_auto_20201017_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerobounceresult',
            name='did_you_mean',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Did you mean?'),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='mx_found',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MX found'),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='mx_record',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MX record'),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='smtp_provider',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SMTP provider'),
        ),
    ]
