# Generated by Django 3.1.2 on 2020-10-23 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_auto_20201022_1003'),
        ('growth', '0013_auto_20201023_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookChemResultCompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField(blank=True, null=True, verbose_name='Details in Markdown')),
                ('programmatic_key', models.CharField(blank=True, max_length=100, null=True)),
                ('programmatic_details_md', models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown')),
            ],
            options={
                'verbose_name': 'LookChemResult-Company Type',
                'verbose_name_plural': 'LookChemResult-Company Types',
            },
        ),
        migrations.CreateModel(
            name='LookChemResultCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('details_md', models.TextField(verbose_name='Details in Markdown')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lookchemresult_company_relationships', related_query_name='lookchemresult_company_relationships', to='relationships.company')),
                ('lookchem_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lookchemresult_company_relationships', related_query_name='lookchemresult_company_relationships', to='growth.lookchemresult')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lookchemresult_company_relationships', related_query_name='lookchemresult_company_relationships', to='growth.lookchemresultcompanytype', verbose_name='LookChemResult-Company Type')),
            ],
            options={
                'verbose_name': 'LookChemResult-Company Relationship',
                'verbose_name_plural': 'LookChemResult-Company Relationships',
            },
        ),
        migrations.AddField(
            model_name='lookchemresult',
            name='companies',
            field=models.ManyToManyField(related_name='lookchem_results', related_query_name='lookchem_results', through='growth.LookChemResultCompany', to='relationships.Company'),
        ),
    ]
