# Generated by Django 3.1.2 on 2021-08-23 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0103_auto_20210822_1743'),
        ('growth', '0013_auto_20210822_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='started',
            new_name='closed',
        ),
        migrations.RemoveField(
            model_name='note',
            name='status',
        ),
        migrations.AddField(
            model_name='note',
            name='cc_users',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='notes_with_this_user_as_cc', related_query_name='notes_with_this_user_as_cc', to='relationships.User'),
        ),
        migrations.AddField(
            model_name='notestatus',
            name='notes',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='statuses', related_query_name='statuses', to='growth.Note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes_with_this_user_as_main', related_query_name='notes_with_this_user_as_main', to='relationships.user'),
        ),
    ]
