# Generated by Django 3.1.2 on 2021-08-23 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0103_auto_20210822_1743'),
        ('growth', '0014_auto_20210823_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCCGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('cc_users', models.ManyToManyField(blank=True, db_index=True, related_name='user_cc_group_with_this_user_as_cc', related_query_name='user_cc_group_with_this_user_as_cc', to='relationships.User')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_cc_group_with_this_user_as_main', related_query_name='user_cc_group_with_this_user_as_main', to='relationships.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
