# Generated by Django 3.1.2 on 2021-08-23 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0015_userccgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user_cc_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes', related_query_name='notes', to='growth.userccgroup'),
        ),
    ]
