# Generated by Django 3.1.2 on 2021-08-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0103_auto_20210822_1743'),
        ('growth', '0016_note_user_cc_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('cc_users', models.ManyToManyField(blank=True, db_index=True, related_name='user_contact_group_with_this_user_as_cc', related_query_name='user_contact_group_with_this_user_as_cc', to='relationships.User')),
                ('to_users', models.ManyToManyField(blank=True, db_index=True, related_name='user_contact_group_with_this_user_as_to', related_query_name='user_contact_group_with_this_user_as_to', to='relationships.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='note',
            name='contact_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes', related_query_name='notes', to='growth.contactgroup'),
        ),
    ]
