# Generated by Django 3.1.2 on 2020-10-23 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_auto_20201022_1003'),
        ('growth', '0016_auto_20201023_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookChemResultPhoneNumberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField(blank=True, null=True, verbose_name='Details in Markdown')),
                ('programmatic_key', models.CharField(blank=True, max_length=100, null=True)),
                ('programmatic_details_md', models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown')),
            ],
            options={
                'verbose_name': 'LookChemResult-PhoneNumber Type',
                'verbose_name_plural': 'LookChemResult-PhoneNumber Types',
            },
        ),
        migrations.CreateModel(
            name='LookChemResultPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('details_md', models.TextField(verbose_name='Details in Markdown')),
                ('lookchem_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lookchemresult_phonenumber_relationships', related_query_name='lookchemresult_phonenumber_relationships', to='growth.lookchemresult')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lookchemresult_phonenumber_relationships', related_query_name='lookchemresult_phonenumber_relationships', to='relationships.phonenumber')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lookchemresult_phonenumber_relationships', related_query_name='lookchemresult_phonenumber_relationships', to='growth.lookchemresultphonenumbertype', verbose_name='LookChemResult-PhoneNumber Type')),
            ],
            options={
                'verbose_name': 'LookChemResult-PhoneNumber Relationship',
                'verbose_name_plural': 'LookChemResult-PhoneNumber Relationships',
            },
        ),
        migrations.AddField(
            model_name='lookchemresult',
            name='phone_numbers',
            field=models.ManyToManyField(related_name='lookchem_results', related_query_name='lookchem_results', through='growth.LookChemResultPhoneNumber', to='relationships.PhoneNumber'),
        ),
    ]
