# Generated by Django 3.1.2 on 2021-08-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0017_auto_20210823_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user_cc_group',
        ),
        migrations.DeleteModel(
            name='UserCCGroup',
        ),
    ]
