# Generated by Django 3.1.2 on 2020-10-23 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_auto_20201022_1003'),
        ('growth', '0018_auto_20201023_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookChemResultLinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField(blank=True, null=True, verbose_name='Details in Markdown')),
                ('programmatic_key', models.CharField(blank=True, max_length=100, null=True)),
                ('programmatic_details_md', models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown')),
            ],
            options={
                'verbose_name': 'LookChemResult-Link Type',
                'verbose_name_plural': 'LookChemResult-Link Types',
            },
        ),
        migrations.CreateModel(
            name='LookChemResultLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('details_md', models.TextField(verbose_name='Details in Markdown')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lookchemresult_link_relationships', related_query_name='lookchemresult_link_relationships', to='relationships.link')),
                ('lookchem_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lookchemresult_link_relationships', related_query_name='lookchemresult_link_relationships', to='growth.lookchemresult')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lookchemresult_link_relationships', related_query_name='lookchemresult_link_relationships', to='growth.lookchemresultemailtype', verbose_name='LookChemResult-Link Type')),
            ],
            options={
                'verbose_name': 'LookChemResult-Link Relationship',
                'verbose_name_plural': 'LookChemResult-Link Relationships',
            },
        ),
        migrations.AddField(
            model_name='lookchemresult',
            name='links',
            field=models.ManyToManyField(related_name='lookchem_results', related_query_name='lookchem_results', through='growth.LookChemResultLink', to='relationships.Link'),
        ),
    ]
