# Generated by Django 3.1.2 on 2021-08-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0103_auto_20210822_1743'),
        ('growth', '0021_auto_20210826_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
                ('emails', models.ManyToManyField(blank=True, related_name='statuses', related_query_name='statuses', to='relationships.Email')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
