# Generated by Django 3.1.2 on 2021-08-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0022_emailstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmassCampaignTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
                ('gmass_campaigns', models.ManyToManyField(blank=True, related_name='tags', related_query_name='tags', to='growth.GmassCampaign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
