# Generated by Django 3.1.2 on 2020-10-23 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_auto_20201022_1003'),
        ('growth', '0022_worldofchemicalresultlink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorldOfChemicalResultLink',
            new_name='WorldOfChemicalsResultLink',
        ),
    ]
