# Generated by Django 3.1.2 on 2020-10-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_auto_20201022_1003'),
        ('growth', '0023_auto_20201023_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldofchemicalsresult',
            name='links',
            field=models.ManyToManyField(related_name='world_of_chemcials_results', related_query_name='world_of_chemcials_results', through='growth.WorldOfChemicalsResultLink', to='relationships.Link'),
        ),
    ]
