# Generated by Django 3.1.2 on 2021-08-30 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0106_user_registered'),
        ('growth', '0023_gmasscampaigntag'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='growth_notes', related_query_name='growth_notes', to='relationships.user'),
        ),
        migrations.AlterField(
            model_name='note',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='growth_notes', related_query_name='growth_notes', to='relationships.email'),
        ),
        migrations.AlterField(
            model_name='note',
            name='phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='growth_notes', related_query_name='growth_notes', to='relationships.phonenumber'),
        ),
    ]
