# Generated by Django 3.1.2 on 2020-10-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_auto_20201022_1003'),
        ('growth', '0027_auto_20201023_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldofchemicalsresult',
            name='companies',
            field=models.ManyToManyField(related_name='world_of_chemcials_results', related_query_name='world_of_chemcials_results', through='growth.WorldOfChemicalsResultCompany', to='relationships.Company'),
        ),
    ]
