# Generated by Django 3.1.2 on 2020-10-23 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_auto_20201022_1003'),
        ('growth', '0028_worldofchemicalsresult_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldOfChemicalsResultAddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField(blank=True, null=True, verbose_name='Details in Markdown')),
                ('programmatic_key', models.CharField(blank=True, max_length=100, null=True)),
                ('programmatic_details_md', models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown')),
            ],
            options={
                'verbose_name': 'WorldOfChemicalsResult-Address Type',
                'verbose_name_plural': 'WorldOfChemicalsResult-Address Types',
            },
        ),
        migrations.CreateModel(
            name='WorldOfChemicalsResultAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('details_md', models.TextField(verbose_name='Details in Markdown')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worldofchemicalsresult_relationships', related_query_name='worldofchemicalsresult_relationships', to='relationships.address')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worldofchemicalsresult_address_relationships', related_query_name='worldofchemicalsresult_address_relationships', to='growth.worldofchemicalsresultaddresstype', verbose_name='WorldOfChemicalsResult-Address Type')),
                ('world_of_chemicals_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worldofchemicalsresult_address_relationships', related_query_name='worldofchemicalsresult_address_relationships', to='growth.worldofchemicalsresult')),
            ],
            options={
                'verbose_name': 'WorldOfChemicalsResult-Address Relationship',
                'verbose_name_plural': 'WorldOfChemicalsResult-Address Relationships',
            },
        ),
        migrations.AddField(
            model_name='worldofchemicalsresult',
            name='addresses',
            field=models.ManyToManyField(related_name='world_of_chemcials_results', related_query_name='world_of_chemcials_results', through='growth.WorldOfChemicalsResultAddress', to='relationships.Address'),
        ),
    ]
