# Generated by Django 3.1.2 on 2020-10-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0032_auto_20201023_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='coy_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='coy_href',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='coy_internal_href',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='coy_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='coy_nat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='coy_tel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='source_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='did_you_mean',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='mx_found',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='mx_record',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='smtp_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
