# Generated by Django 3.1.2 on 2020-10-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0035_lookchemresult_website_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lookchemresult',
            old_name='website_url',
            new_name='website_as_url',
        ),
    ]
