# Generated by Django 3.1.2 on 2020-10-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0005_auto_20201025_1553'),
        ('growth', '0038_auto_20201025_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibre2fashionresult',
            name='emails',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='fibre2fashion_results', related_query_name='fibre2fashion_results', to='relationships.Email'),
        ),
        migrations.AlterField(
            model_name='fibre2fashionresult',
            name='links',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='fibre2fashion_results', related_query_name='fibre2fashion_results', to='relationships.Link'),
        ),
    ]
