# Generated by Django 3.1.2 on 2020-10-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0006_auto_20201025_1608'),
        ('common', '0004_country_cc_tld'),
        ('growth', '0039_auto_20201025_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='companies',
            field=models.ManyToManyField(db_index=True, related_name='chemical_book_results', related_query_name='chemical_book_results', through='growth.ChemicalBookResultCompany', to='relationships.Company'),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='countries',
            field=models.ManyToManyField(db_index=True, related_name='chemical_book_results', related_query_name='chemical_book_results', through='growth.ChemicalBookResultCountry', to='common.Country'),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='emails',
            field=models.ManyToManyField(db_index=True, related_name='chemical_book_results', related_query_name='chemical_book_results', through='growth.ChemicalBookResultEmail', to='relationships.Email'),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='links',
            field=models.ManyToManyField(db_index=True, related_name='chemical_book_results', related_query_name='chemical_book_results', through='growth.ChemicalBookResultLink', to='relationships.Link'),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='phone_numbers',
            field=models.ManyToManyField(db_index=True, related_name='chemical_book_results', related_query_name='chemical_book_results', through='growth.ChemicalBookResultPhoneNumber', to='relationships.PhoneNumber'),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresultcompany',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresultcompany',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresultcompany',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresultcountry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresultcountry',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresultcountry',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresultemail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresultemail',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresultemail',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresultlink',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresultlink',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresultlink',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresultphonenumber',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresultphonenumber',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresultphonenumber',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeresult',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeresult',
            name='sourced',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeresult',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='emails',
            field=models.ManyToManyField(db_index=True, related_name='data_sources', related_query_name='data_sources', through='growth.SourcedEmail', to='relationships.Email'),
        ),
        migrations.AlterField(
            model_name='fibre2fashionresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionresult',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionresult',
            name='sourced',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionresult',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='gmasscampaign',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='gmasscampaign',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='gmasscampaign',
            name='sent',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='gmasscampaign',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='gmasscampaignresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='gmasscampaignresult',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='gmasscampaignresult',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemresult',
            name='addresses',
            field=models.ManyToManyField(db_index=True, related_name='lookchem_results', related_query_name='lookchem_results', through='growth.LookChemResultAddress', to='relationships.Address'),
        ),
        migrations.AlterField(
            model_name='lookchemresult',
            name='companies',
            field=models.ManyToManyField(db_index=True, related_name='lookchem_results', related_query_name='lookchem_results', through='growth.LookChemResultCompany', to='relationships.Company'),
        ),
        migrations.AlterField(
            model_name='lookchemresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lookchemresult',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemresult',
            name='emails',
            field=models.ManyToManyField(db_index=True, related_name='lookchem_results', related_query_name='lookchem_results', through='growth.LookChemResultEmail', to='relationships.Email'),
        ),
        migrations.AlterField(
            model_name='lookchemresult',
            name='links',
            field=models.ManyToManyField(db_index=True, related_name='lookchem_results', related_query_name='lookchem_results', through='growth.LookChemResultLink', to='relationships.Link'),
        ),
        migrations.AlterField(
            model_name='lookchemresult',
            name='persons',
            field=models.ManyToManyField(db_index=True, related_name='lookchem_results', related_query_name='lookchem_results', through='growth.LookChemResultPerson', to='relationships.Person'),
        ),
        migrations.AlterField(
            model_name='lookchemresult',
            name='phone_numbers',
            field=models.ManyToManyField(db_index=True, related_name='lookchem_results', related_query_name='lookchem_results', through='growth.LookChemResultPhoneNumber', to='relationships.PhoneNumber'),
        ),
        migrations.AlterField(
            model_name='lookchemresult',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemresultaddress',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lookchemresultaddress',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemresultaddress',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemresultcompany',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lookchemresultcompany',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemresultcompany',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemresultemail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lookchemresultemail',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemresultemail',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemresultlink',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lookchemresultlink',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemresultlink',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemresultperson',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lookchemresultperson',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemresultperson',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemresultphonenumber',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lookchemresultphonenumber',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemresultphonenumber',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcedemail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sourcedemail',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sourcedemail',
            name='sourced',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sourcedemail',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='addresses',
            field=models.ManyToManyField(db_index=True, related_name='world_of_chemcials_results', related_query_name='world_of_chemcials_results', through='growth.WorldOfChemicalsResultAddress', to='relationships.Address'),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='companies',
            field=models.ManyToManyField(db_index=True, related_name='world_of_chemcials_results', related_query_name='world_of_chemcials_results', through='growth.WorldOfChemicalsResultCompany', to='relationships.Company'),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='emails',
            field=models.ManyToManyField(db_index=True, related_name='world_of_chemcials_results', related_query_name='world_of_chemcials_results', through='growth.WorldOfChemicalsResultEmail', to='relationships.Email'),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='links',
            field=models.ManyToManyField(db_index=True, related_name='world_of_chemcials_results', related_query_name='world_of_chemcials_results', through='growth.WorldOfChemicalsResultLink', to='relationships.Link'),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='phone_numbers',
            field=models.ManyToManyField(db_index=True, related_name='world_of_chemcials_results', related_query_name='world_of_chemcials_results', through='growth.WorldOfChemicalsResultPhoneNumber', to='relationships.PhoneNumber'),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresultaddress',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresultaddress',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresultaddress',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresultcompany',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresultcompany',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresultcompany',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresultemail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresultemail',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresultemail',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresultlink',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresultlink',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresultlink',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresultphonenumber',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresultphonenumber',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresultphonenumber',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='deleted',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
