# Generated by Django 3.1.2 on 2020-11-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0041_auto_20201104_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmasscampaign',
            name='campaign_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gmasscampaign',
            name='spreadsheet',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gmasscampaign',
            name='subject',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
