# Generated by Django 3.1.2 on 2020-11-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0042_auto_20201104_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fibre2fashionresult',
            old_name='sourced',
            new_name='harvested',
        ),
        migrations.AddField(
            model_name='chemicalclusterofsingaporeresult',
            name='harvested',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeresult',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeresult',
            name='email_str',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeresult',
            name='fax',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeresult',
            name='source_link',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeresult',
            name='telephone',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeresult',
            name='website',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
