# Generated by Django 3.1.2 on 2020-11-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0043_auto_20201104_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerobounceresult',
            name='account',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='did_you_mean',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='email_address',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='free_email',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='gender',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='mx_found',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='mx_record',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='smtp_provider',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='sub_status',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
