# Generated by Django 3.1.2 on 2020-11-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0044_auto_20201104_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerobounceresult',
            name='generated',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
