# Generated by Django 3.1.2 on 2020-11-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0045_zerobounceresult_generated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcedemail',
            old_name='sourced',
            new_name='harvested',
        ),
    ]
