# Generated by Django 3.1.2 on 2020-11-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0048_auto_20201104_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldofchemicalsresult',
            name='harvested',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='coy_addr_1',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='coy_addr_2',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='coy_alt_email',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='coy_alt_email_2',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='coy_alt_email_3',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='coy_city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='coy_country',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='coy_email',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='coy_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='coy_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='coy_owner_email',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='coy_phone',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='coy_phone_2',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='coy_postal',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='coy_pri_contact',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='coy_state',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='coy_website',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalsresult',
            name='source_url',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
