# Generated by Django 3.1.2 on 2020-11-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0050_okchemresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemicalclusterofsingaporeresult',
            old_name='phone_numbers',
            new_name='phone_number',
        ),
    ]
