# Generated by Django 3.1.2 on 2020-11-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0051_auto_20201104_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemicalclusterofsingaporeresult',
            name='sourced',
        ),
    ]
