# Generated by Django 3.1.2 on 2020-11-07 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_importjob'),
        ('growth', '0056_remove_zerobounceresult_batch_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerobounceresult',
            name='import_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zero_bounce_results', related_query_name='zero_bounce_results', to='common.importjob'),
        ),
    ]
