# Generated by Django 3.1.2 on 2020-11-09 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0014_invalidemail'),
        ('growth', '0059_auto_20201109_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerobounceresult',
            name='invalid_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zero_bounce_result_invalid_emails', related_query_name='zero_bounce_result_invalid_emails', to='relationships.invalidemail'),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zero_bounce_result_emails', related_query_name='zero_bounce_result_emails', to='relationships.email'),
        ),
    ]
