# Generated by Django 3.1.2 on 2020-11-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0060_auto_20201109_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zerobounceresult',
            old_name='email_address',
            new_name='email_str',
        ),
    ]
