# Generated by Django 3.1.2 on 2020-11-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0064_fibre2fashionsellingoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerobounceresult',
            name='account',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='sub_status',
            field=models.CharField(blank=True, choices=[('antispam_system', 'Anti-Spam System'), ('does_not_accept_mail', 'Does Not Accept Mail'), ('exception_occurred', 'Exception Occurred'), ('failed_smtp_connection', 'Failed SMTP Connection'), ('failed_syntax_check', 'Failed Syntax Check'), ('forcible_disconnect', 'Forcible Disconnect'), ('global_suppression', 'Global Suppression'), ('greylisted', 'Greylisted'), ('leading_period_removed', 'Leading Period Removed'), ('mail_server_did_not_respond', 'Mail Server Did Not Respond'), ('mail_server_temporary_error', 'Mail Server Temporary Error'), ('mailbox_quota_exceeded', 'Mailbox Quota Exceeded'), ('mailbox_not_found', 'Mailbox Not Found'), ('no_dns_entries', 'No DNS Entries'), ('possible_trap', 'Possible Trap'), ('possible_typo', 'Possible Typo'), ('role_based', 'Role-Based'), ('timeout_exceeded', 'Timeout Exceeded'), ('unroutable_ip_address', 'Unroutable IP Address'), ('alias_address', 'Alias Address'), ('role_based_catch_all', 'Role-Based Catch-All'), ('disposable', 'Disposable'), ('toxic', 'Toxic')], db_index=True, max_length=50, null=True),
        ),
    ]
