# Generated by Django 3.1.2 on 2020-11-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20201109_1500'),
        ('growth', '0066_remove_fibre2fashionbuyingoffer_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibre2fashionsellingoffer',
            name='import_job',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fibre2fashion_selling_offers', related_query_name='fibre2fashion_selling_offers', to='common.importjob'),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='import_job',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zero_bounce_results', related_query_name='zero_bounce_results', to='common.importjob'),
        ),
    ]
