# Generated by Django 3.1.2 on 2020-11-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20201109_1500'),
        ('growth', '0067_auto_20201111_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibre2fashionbuyingoffer',
            name='import_job',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fibre2fashion_buying_offers', related_query_name='fibre2fashion_buying_offers', to='common.importjob'),
        ),
    ]
