# Generated by Django 3.1.2 on 2020-11-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0068_auto_20201111_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibre2fashionbuyingoffer',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionsellingoffer',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
