# Generated by Django 3.1.2 on 2020-11-11 12:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0015_auto_20201110_1148'),
        ('common', '0010_auto_20201109_1500'),
        ('growth', '0070_auto_20201111_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemicalbookresult',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresult',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresult',
            name='coy_email',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresult',
            name='coy_href',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresult',
            name='coy_internal_href',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresult',
            name='coy_name',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresult',
            name='coy_nat',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresult',
            name='coy_tel',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresult',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresult',
            name='links',
        ),
        migrations.RemoveField(
            model_name='chemicalbookresult',
            name='phone_numbers',
        ),
        migrations.AddField(
            model_name='chemicalbookresult',
            name='company_name',
            field=models.CharField(db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemicalbookresult',
            name='corporate_site_url',
            field=models.CharField(db_index=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemicalbookresult',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chemical_book_result_emails', related_query_name='chemical_book_result_emails', to='relationships.email'),
        ),
        migrations.AddField(
            model_name='chemicalbookresult',
            name='email_str',
            field=models.CharField(db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemicalbookresult',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chemical_book_results', related_query_name='chemical_book_results', to='common.importjob'),
        ),
        migrations.AddField(
            model_name='chemicalbookresult',
            name='internal_url',
            field=models.CharField(db_index=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemicalbookresult',
            name='invalid_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chemical_book_result_invalid_emails', related_query_name='chemical_book_result_invalid_emails', to='relationships.invalidemail'),
        ),
        migrations.AddField(
            model_name='chemicalbookresult',
            name='nationality',
            field=models.CharField(db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemicalbookresult',
            name='telephone',
            field=models.CharField(db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='harvested',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='source_url',
            field=models.CharField(db_index=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fibre2fashionbuyingoffer',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fibre2fashion_buying_offers', related_query_name='fibre2fashion_buying_offers', to='common.importjob'),
        ),
        migrations.AlterField(
            model_name='fibre2fashionsellingoffer',
            name='company_address',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionsellingoffer',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fibre2fashion_selling_offers', related_query_name='fibre2fashion_selling_offers', to='common.importjob'),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zero_bounce_results', related_query_name='zero_bounce_results', to='common.importjob'),
        ),
    ]
