# Generated by Django 3.1.2 on 2020-11-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0071_auto_20201111_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='corporate_site_url',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='email_str',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='internal_url',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='nationality',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='telephone',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionbuyingoffer',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionbuyingoffer',
            name='email_str',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionbuyingoffer',
            name='product_info_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionbuyingoffer',
            name='reference_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionbuyingoffer',
            name='sub_category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionbuyingoffer',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionsellingoffer',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionsellingoffer',
            name='company_address',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionsellingoffer',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionsellingoffer',
            name='email_str',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionsellingoffer',
            name='product_info_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionsellingoffer',
            name='reference_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionsellingoffer',
            name='sub_category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionsellingoffer',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
