# Generated by Django 3.1.2 on 2020-11-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0072_auto_20201112_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalbookresult',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
