# Generated by Django 3.1.2 on 2020-11-14 06:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20201109_1500'),
        ('relationships', '0015_auto_20201110_1148'),
        ('growth', '0077_auto_20201114_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemicalbooksupplier',
            options={'verbose_name': 'Chemical Book supplier', 'verbose_name_plural': 'Chemical Book suppliers'},
        ),
        migrations.AlterModelOptions(
            name='okchemresult',
            options={'verbose_name': 'OKChem buying request', 'verbose_name_plural': 'OKChem buying requests'},
        ),
        migrations.AddField(
            model_name='okchemresult',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ok_chem_suppliers', related_query_name='ok_chem_supplier', to='common.importjob'),
        ),
        migrations.AlterField(
            model_name='chemicalbooksupplier',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chemical_book_supplier_emails', related_query_name='chemical_book_supplier_emails', to='relationships.email'),
        ),
        migrations.AlterField(
            model_name='chemicalbooksupplier',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chemical_book_suppliers', related_query_name='chemical_book_suppliers', to='common.importjob'),
        ),
        migrations.AlterField(
            model_name='chemicalbooksupplier',
            name='invalid_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chemical_book_supplier_invalid_emails', related_query_name='chemical_book_supplier_invalid_emails', to='relationships.invalidemail'),
        ),
        migrations.AlterField(
            model_name='lookchemsupplier',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='look_chem_suppliers', related_query_name='look_chem_suppliers', to='common.importjob'),
        ),
        migrations.AlterField(
            model_name='okchemresult',
            name='harvested',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='okchemresult',
            name='request',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='world_of_chemicals_suppliers', related_query_name='world_of_chemicals_suppliers', to='common.importjob'),
        ),
    ]
