# Generated by Django 3.1.2 on 2020-11-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0079_auto_20201114_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='okchembuyingrequest',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
