# Generated by Django 3.1.2 on 2020-11-16 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0081_auto_20201116_0920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChemicalClusterOfSingaporeResult',
        ),
    ]
