# Generated by Django 3.1.2 on 2020-11-16 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20201109_1500'),
        ('relationships', '0015_auto_20201110_1148'),
        ('growth', '0082_delete_chemicalclusterofsingaporeresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalClusterOfSingaporeCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('harvested', models.DateTimeField(db_index=True)),
                ('source_url', models.CharField(db_index=True, max_length=300)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('email_str', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('website', models.CharField(db_index=True, max_length=300)),
                ('address', models.CharField(db_index=True, max_length=300)),
                ('nature_of_business', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('executive_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('executive_telephone', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('executive_email_str', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chemical_cluster_of_singapore_company_emails', related_query_name='chemical_cluster_of_singapore_company_emails', to='relationships.email')),
                ('executive_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chemical_cluster_of_singapore_company_executive_emails', related_query_name='chemical_cluster_of_singapore_company_executive_emails', to='relationships.email')),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chemical_cluster_of_singapore_companies', related_query_name='chemical_cluster_of_singapore_companies', to='common.importjob')),
                ('invalid_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chemical_cluster_of_singapore_company_invalid_emails', related_query_name='chemical_cluster_of_singapore_company_invalid_emails', to='relationships.invalidemail')),
                ('invalid_executive_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chemical_cluster_of_singapore_company_invalid_executive_emails', related_query_name='chemical_cluster_of_singapore_company_invalid_executive_emails', to='relationships.invalidemail')),
            ],
            options={
                'verbose_name': 'Chemical Cluster of Singapore company',
                'verbose_name_plural': 'Chemical Cluster of Singapore companies',
            },
        ),
    ]
