# Generated by Django 3.1.2 on 2020-11-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0085_auto_20201116_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmasscampaign',
            name='sent',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
