# Generated by Django 3.1.2 on 2020-11-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0086_auto_20201116_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lookchemsupplier',
            old_name='coy_name',
            new_name='company_name',
        ),
    ]
