# Generated by Django 3.1.2 on 2020-11-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0087_auto_20201116_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalbooksupplier',
            name='source_url',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporecompany',
            name='source_url',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeproduct',
            name='source_url',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporeservice',
            name='source_url',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionbuyingoffer',
            name='source_url',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionsellingoffer',
            name='source_url',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
    ]
