# Generated by Django 3.1.2 on 2020-11-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0088_auto_20201116_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcedemail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sourcedemail',
            name='source',
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
        migrations.DeleteModel(
            name='SourcedEmail',
        ),
    ]
