# Generated by Django 3.1.2 on 2020-11-16 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20201109_1500'),
        ('growth', '0089_auto_20201116_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmasscampaign',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gmass_campaigns', related_query_name='gmass_campaigns', to='common.importjob'),
        ),
        migrations.AddField(
            model_name='gmasscampaignresult',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gmass_campaign_results', related_query_name='gmass_campaign_results', to='common.importjob'),
        ),
    ]
