# Generated by Django 3.1.2 on 2020-11-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0090_auto_20201116_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalbooksupplier',
            name='email_str',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporecompany',
            name='email_str',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalclusterofsingaporecompany',
            name='executive_email_str',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionbuyingoffer',
            name='email_str',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionsellingoffer',
            name='email_str',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='gmasscampaignresult',
            name='email_address',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemsupplier',
            name='email_str',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='lookchemsupplier',
            name='website',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='okchembuyingrequest',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='okchembuyingrequest',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_alt_email',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_alt_email_2',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_alt_email_3',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_email',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='worldofchemicalssupplier',
            name='coy_owner_email',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='zerobounceresult',
            name='email_str',
            field=models.CharField(db_index=True, max_length=400),
        ),
    ]
