# Generated by Django 3.1.2 on 2020-11-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0091_auto_20201120_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalclusterofsingaporecompany',
            name='nature_of_business',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
