# Generated by Django 3.1.2 on 2020-11-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0093_auto_20201120_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalclusterofsingaporecompany',
            name='address',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
