# Generated by Django 3.1.2 on 2020-11-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0094_auto_20201120_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okchembuyingrequest',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
    ]
