# Generated by Django 3.1.2 on 2020-11-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0096_auto_20201121_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmasscampaignresult',
            name='gmass_campaign_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
