# Generated by Django 3.1.2 on 2020-11-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0097_gmasscampaignresult_gmass_campaign_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmasscampaignresult',
            name='gmass_campaign_identifier',
        ),
    ]
