# Generated by Django 3.1.2 on 2020-11-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0100_auto_20201121_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmasscampaign',
            name='campaign_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
