# Generated by Django 3.1.2 on 2020-11-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0101_auto_20201122_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmasscampaign',
            name='report_accessed_count',
        ),
        migrations.RemoveField(
            model_name='gmasscampaignresult',
            name='bounce_reason',
        ),
    ]
