# Generated by Django 3.1.2 on 2020-11-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0106_auto_20201123_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gmassemailstatus',
            options={'verbose_name': 'Gmass email status', 'verbose_name_plural': 'Gmass email statuses'},
        ),
    ]
