# Generated by Django 3.1.2 on 2020-11-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0108_gmasscampaign_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fibre2fashionbuyingoffer',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
