# Generated by Django 3.1.2 on 2020-11-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0109_fibre2fashionbuyingoffer_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibre2fashionbuyingoffer',
            name='source_url',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fibre2fashionsellingoffer',
            name='source_url',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, unique=True),
        ),
    ]
