# Generated by Django 3.0.2 on 2020-01-20 07:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateFilePresignedURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued', models.DateTimeField(auto_now_add=True)),
                ('lifespan', models.IntegerField()),
                ('url', models.URLField()),
                ('s3_bucket_name', models.CharField(max_length=63)),
                ('s3_object_key', models.CharField(max_length=1024)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_create_file_presigned_urls', to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=10)),
                ('level', models.CharField(choices=[('material', 'Material-Level'), ('batch', 'Batch-Level')], default='material', max_length=20)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('s3_bucket_name', models.CharField(max_length=63)),
                ('s3_object_key', models.CharField(max_length=1024)),
                ('s3_object_content_length', models.IntegerField(blank=True, default=None, null=True)),
                ('s3_object_e_tag', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('s3_object_content_type', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('s3_object_last_modified', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_presigned_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='documents.CreateFilePresignedURL')),
                ('document', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.Document')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_uploaded', to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='ReadFilePresignedURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('lifespan', models.IntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_presigned_urls', to='documents.File')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_read_file_presigned_urls', to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Material')),
            ],
            options={
                'verbose_name': 'Document-Material',
                'verbose_name_plural': 'Document-Materials',
            },
        ),
        migrations.CreateModel(
            name='DocumentBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Batch')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
            ],
            options={
                'verbose_name': 'Document-Batch',
                'verbose_name_plural': 'Document-Batches',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='batches',
            field=models.ManyToManyField(related_name='documents', through='documents.DocumentBatch', to='materials.Batch'),
        ),
        migrations.AddField(
            model_name='document',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.DocumentType'),
        ),
        migrations.AddField(
            model_name='document',
            name='materials',
            field=models.ManyToManyField(related_name='documents', through='documents.DocumentMaterial', to='materials.Material'),
        ),
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.Organization'),
        ),
    ]
