# Generated by Django 3.0 on 2020-01-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentbatch',
            options={'verbose_name': 'Document-Batch', 'verbose_name_plural': 'Document-Batches'},
        ),
        migrations.AlterModelOptions(
            name='documentmaterial',
            options={'verbose_name': 'Document-Material', 'verbose_name_plural': 'Document-Materials'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'Document Type', 'verbose_name_plural': 'Document Types'},
        ),
    ]
