# Generated by Django 3.0.2 on 2020-01-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createfilepresignedurl',
            name='filetype',
            field=models.CharField(default='application/pdf', max_length=100),
            preserve_default=False,
        ),
    ]
