# Generated by Django 3.0.2 on 2020-01-21 02:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_createfilepresignedurl_filetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createfilepresignedurl',
            options={'verbose_name': 'Create-File-Presigned-URL', 'verbose_name_plural': 'Create-File-Presigned-URLs'},
        ),
        migrations.AlterModelOptions(
            name='readfilepresignedurl',
            options={'verbose_name': 'Read-File-Presigned-URL', 'verbose_name_plural': 'Read-File-Presigned-URLs'},
        ),
        migrations.RemoveField(
            model_name='createfilepresignedurl',
            name='url',
        ),
        migrations.AddField(
            model_name='createfilepresignedurl',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='readfilepresignedurl',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
