# Generated by Django 3.0 on 2020-01-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20200116_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
