# Generated by Django 3.0 on 2020-01-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20200116_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='level',
            field=models.CharField(choices=[('material', 'Material-Level'), ('batch', 'Batch-Level')], default='material', max_length=20),
        ),
    ]
