# Generated by Django 3.0.2 on 2020-01-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20200121_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readfilepresignedurl',
            name='url',
        ),
        migrations.AddField(
            model_name='readfilepresignedurl',
            name='s3_bucket_name',
            field=models.CharField(default='', max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readfilepresignedurl',
            name='s3_object_key',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
