# Generated by Django 3.0.2 on 2020-01-17 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documenttype_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='s3_bucket_name',
            new_name='bucket_name',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='s3_object_key',
            new_name='object_key',
        ),
        migrations.RemoveField(
            model_name='file',
            name='created',
        ),
        migrations.RemoveField(
            model_name='file',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='file',
            name='s3_bucket_arn',
        ),
        migrations.RemoveField(
            model_name='file',
            name='s3_bucket_region',
        ),
        migrations.RemoveField(
            model_name='file',
            name='s3_object_content_length',
        ),
        migrations.RemoveField(
            model_name='file',
            name='s3_object_content_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='s3_object_e_tag',
        ),
        migrations.RemoveField(
            model_name='file',
            name='s3_object_last_modified',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated',
        ),
        migrations.AddField(
            model_name='file',
            name='expires_in',
            field=models.IntegerField(default=3600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='file_uploaded',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='object_content_length',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='object_content_type',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='object_e_tag',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='object_last_modified',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='presigned_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='presigned_url_issued',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
