# Generated by Django 3.0.2 on 2020-01-21 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200121_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readfilepresignedurl',
            name='s3_bucket_name',
        ),
        migrations.RemoveField(
            model_name='readfilepresignedurl',
            name='s3_object_key',
        ),
    ]
