# Generated by Django 3.0.2 on 2020-01-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20200117_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
