# Generated by Django 3.0.2 on 2020-01-22 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('documents', '0005_auto_20200121_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmaterial',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentmaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='readfilepresignedurl',
            name='file',
        ),
        migrations.RemoveField(
            model_name='readfilepresignedurl',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='document',
            name='batches',
        ),
        migrations.RemoveField(
            model_name='document',
            name='materials',
        ),
        migrations.AddField(
            model_name='document',
            name='batch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='materials.Batch'),
        ),
        migrations.AddField(
            model_name='document',
            name='material',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='materials.Material'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DocumentBatch',
        ),
        migrations.DeleteModel(
            name='DocumentMaterial',
        ),
        migrations.DeleteModel(
            name='ReadFilePresignedURL',
        ),
    ]
