# Generated by Django 3.0.2 on 2020-01-22 03:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_id'),
        ('documents', '0006_auto_20200122_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued', models.DateTimeField(auto_now_add=True)),
                ('lifespan', models.IntegerField()),
                ('presigned_url_response', django.contrib.postgres.fields.jsonb.JSONField()),
                ('filetype', models.CharField(max_length=100)),
                ('s3_bucket_name', models.CharField(max_length=63)),
                ('s3_object_key', models.CharField(max_length=1024)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_create_file_presigned_urls', to='accounts.Account')),
            ],
            options={
                'verbose_name': 'Create-File-Presigned-URL',
                'verbose_name_plural': 'Create-File-Presigned-URLs',
            },
        ),
        migrations.RemoveField(
            model_name='file',
            name='create_presigned_url',
        ),
        migrations.DeleteModel(
            name='CreateFilePresignedURL',
        ),
        migrations.AddField(
            model_name='file',
            name='temp_file',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='file', to='documents.TempFile'),
            preserve_default=False,
        ),
    ]
