# Generated by Django 3.0.2 on 2020-01-17 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20200117_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploader',
            field=models.ForeignKey(default='123e4567-e89b-12d3-a456-426655440000', on_delete=django.db.models.deletion.CASCADE, related_name='files_uploaded', to='documents.Document'),
            preserve_default=False,
        ),
    ]
