# Generated by Django 3.0.2 on 2020-01-17 15:11

from django.db import migrations, models
import django.db.models.deletion
import everybase.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_file_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.Document'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_uploaded',
            field=models.FileField(blank=True, default=None, null=True, storage=everybase.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploader',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_uploaded', to='documents.Document'),
        ),
    ]
