# Generated by Django 3.0.2 on 2020-01-22 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_id'),
        ('documents', '0007_auto_20200122_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='uploader',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='file',
            name='s3_object_content_length',
        ),
        migrations.RemoveField(
            model_name='file',
            name='s3_object_content_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='s3_object_e_tag',
        ),
        migrations.RemoveField(
            model_name='file',
            name='s3_object_last_modified',
        ),
        migrations.RemoveField(
            model_name='tempfile',
            name='requester',
        ),
        migrations.AddField(
            model_name='tempfile',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='created_temp_files', to='accounts.Account'),
            preserve_default=False,
        ),
    ]
