# Generated by Django 3.0.2 on 2020-01-22 10:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20200122_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.RemoveField(
            model_name='file',
            name='temp_file',
        ),
        migrations.AddField(
            model_name='file',
            name='filetype',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='presigned_url_issued',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='presigned_url_lifespan',
            field=models.IntegerField(default=3600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='presigned_url_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TempFile',
        ),
    ]
