# Generated by Django 3.0.2 on 2020-01-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20200122_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='uploaded',
        ),
        migrations.AddField(
            model_name='file',
            name='saved',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
