# Generated by Django 3.0.2 on 2020-01-23 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20200123_1922'),
        ('documents', '0010_auto_20200122_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='batch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='materials.Batch'),
        ),
        migrations.AlterField(
            model_name='document',
            name='deleted',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='deleted',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.Document'),
        ),
        migrations.AlterField(
            model_name='file',
            name='saved',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
