# Generated by Django 3.0.5 on 2020-05-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloakedlink',
            name='redirect',
            field=models.BooleanField(default=False),
        ),
    ]
