# Generated by Django 3.0.5 on 2020-10-21 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0001_initial'),
        ('relationships', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='demand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='leads.Demand'),
        ),
        migrations.AddField(
            model_name='issue',
            name='demand_commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='leads.DemandCommission'),
        ),
        migrations.AddField(
            model_name='issue',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='leads.Match'),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='communication.IssueStatus'),
        ),
        migrations.AddField(
            model_name='issue',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='leads.Supply'),
        ),
        migrations.AddField(
            model_name='issue',
            name='supply_commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='leads.SupplyCommission'),
        ),
        migrations.AddField(
            model_name='issue',
            name='supply_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='leads.SupplyQuote'),
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='issues', related_query_name='issues', to='communication.IssueTag'),
        ),
        migrations.AddField(
            model_name='conversationvoice',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_voices', related_query_name='conversation_voices', to='communication.Conversation'),
        ),
        migrations.AddField(
            model_name='conversationvoice',
            name='our_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_voice_our_numbers', related_query_name='conversation_voice_our_numbers', to='relationships.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='conversationvoice',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_voices', related_query_name='conversation_voices', to='communication.ConversationVoiceStatus'),
        ),
        migrations.AddField(
            model_name='conversationvoice',
            name='their_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_voice_their_numbers', related_query_name='conversation_voice_their_numbers', to='relationships.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='conversationvideo',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_videos', related_query_name='conversation_videos', to='communication.Conversation'),
        ),
        migrations.AddField(
            model_name='conversationvideo',
            name='our_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_video_our_numbers', related_query_name='conversation_video_our_numbers', to='relationships.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='conversationvideo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_videos', related_query_name='conversation_videos', to='communication.ConversationVideoStatus'),
        ),
        migrations.AddField(
            model_name='conversationvideo',
            name='their_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_video_their_numbers', related_query_name='conversation_video_their_numbers', to='relationships.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='conversationemail',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_emails', related_query_name='conversation_emails', to='communication.Conversation'),
        ),
        migrations.AddField(
            model_name='conversationemail',
            name='our_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_email_our_emails', related_query_name='conversation_email_our_emails', to='relationships.Email'),
        ),
        migrations.AddField(
            model_name='conversationemail',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_emails', related_query_name='conversation_emails', to='communication.ConversationEmailStatus'),
        ),
        migrations.AddField(
            model_name='conversationemail',
            name='their_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_email_their_emails', related_query_name='conversation_email_their_emails', to='relationships.Email'),
        ),
        migrations.AddField(
            model_name='conversationchat',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_chats', related_query_name='conversation_chats', to='communication.Conversation'),
        ),
        migrations.AddField(
            model_name='conversationchat',
            name='our_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_chat_our_numbers', related_query_name='conversation_chat_our_numbers', to='relationships.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='conversationchat',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_chats', related_query_name='conversation_chats', to='communication.ConversationChatStatus'),
        ),
        migrations.AddField(
            model_name='conversationchat',
            name='their_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_chat_their_numbers', related_query_name='conversation_chat_their_numbers', to='relationships.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', related_query_name='conversations', to='communication.ConversationChannel'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='chats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', related_query_name='conversations', to='communication.ConversationChat'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='emails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', related_query_name='conversations', to='communication.ConversationEmail'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', related_query_name='conversations', to='communication.Issue'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='videos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', related_query_name='conversations', to='communication.ConversationVideo'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='voices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', related_query_name='conversations', to='communication.ConversationVoice'),
        ),
    ]
