# Generated by Django 3.0.5 on 2020-10-21 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_remove_issuestatus_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuestatus',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', related_query_name='children', to='communication.IssueStatus'),
        ),
    ]
