# Generated by Django 3.1.2 on 2020-12-12 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_auto_20201210_2342'),
        ('communication', '0009_auto_20201210_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='demand_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='leads.demandquote'),
        ),
    ]
