# Generated by Django 3.0.5 on 2020-10-16 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_auto_20201015_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationvideo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationvideo',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='conversationvideo',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
