# Generated by Django 3.0.5 on 2020-10-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20201007_1911'),
        ('relationships', '0001_initial'),
        ('communication', '0002_conversation_conversationchannel_conversationchat_conversationchatstatus_conversationemail_conversat'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='deleted',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='demand',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='leads.Demand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='demand_commission',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='leads.DemandCommission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='description_md',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='match',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='leads.Match'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='outcome_md',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='scheduled',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='supply',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='leads.Supply'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='supply_commission',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='leads.SupplyCommission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='supply_quote',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='leads.SupplyQuote'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='conversationvoice',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_voices', related_query_name='conversation_voices', to='communication.Conversation'),
        ),
        migrations.AddField(
            model_name='conversationvoice',
            name='from_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_voice_froms', related_query_name='conversation_voice_froms', to='relationships.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='conversationvoice',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_voices', related_query_name='conversation_voices', to='communication.ConversationVoiceStatus'),
        ),
        migrations.AddField(
            model_name='conversationvoice',
            name='to_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_voice_tos', related_query_name='conversation_voice_tos', to='relationships.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='conversationvideo',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_videos', related_query_name='conversation_videos', to='communication.Conversation'),
        ),
        migrations.AddField(
            model_name='conversationvideo',
            name='from_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_video_froms', related_query_name='conversation_video_froms', to='relationships.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='conversationvideo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_videos', related_query_name='conversation_videos', to='communication.ConversationVideoStatus'),
        ),
        migrations.AddField(
            model_name='conversationvideo',
            name='to_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_video_tos', related_query_name='conversation_video_tos', to='relationships.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='conversationemail',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_emails', related_query_name='conversation_emails', to='communication.Conversation'),
        ),
        migrations.AddField(
            model_name='conversationemail',
            name='from_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_email_froms', related_query_name='conversation_email_froms', to='relationships.Email'),
        ),
        migrations.AddField(
            model_name='conversationemail',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_emails', related_query_name='conversation_emails', to='communication.ConversationEmailStatus'),
        ),
        migrations.AddField(
            model_name='conversationemail',
            name='to_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_email_tos', related_query_name='conversation_email_tos', to='relationships.Email'),
        ),
        migrations.AddField(
            model_name='conversationchat',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_chats', related_query_name='conversation_chats', to='communication.Conversation'),
        ),
        migrations.AddField(
            model_name='conversationchat',
            name='from_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_chat_froms', related_query_name='conversation_chat_froms', to='relationships.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='conversationchat',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_chats', related_query_name='conversation_chats', to='communication.ConversationChatStatus'),
        ),
        migrations.AddField(
            model_name='conversationchat',
            name='to_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_chat_tos', related_query_name='conversation_chat_tos', to='relationships.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', related_query_name='conversations', to='communication.ConversationChannel'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='chats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', related_query_name='conversations', to='communication.ConversationChat'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='emails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', related_query_name='conversations', to='communication.ConversationEmail'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', related_query_name='conversations', to='communication.Issue'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='videos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', related_query_name='conversations', to='communication.ConversationVideo'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='voices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', related_query_name='conversations', to='communication.ConversationVoice'),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='communication.IssueStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(related_name='issues', related_query_name='issues', to='communication.IssueTag'),
        ),
    ]
