# Generated by Django 3.0.5 on 2020-10-16 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_auto_20201016_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationemail',
            old_name='from_email',
            new_name='our_email',
        ),
        migrations.RenameField(
            model_name='conversationemail',
            old_name='to_email',
            new_name='their_email',
        ),
    ]
