# Generated by Django 3.0.5 on 2020-10-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_auto_20201007_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationchannel',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='conversationchannel',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='conversationchannel',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conversationchatstatus',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='conversationchatstatus',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='conversationchatstatus',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conversationemailstatus',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='conversationemailstatus',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='conversationemailstatus',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conversationvideostatus',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='conversationvideostatus',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='conversationvideostatus',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conversationvoicestatus',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='conversationvoicestatus',
            name='programmatic_details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown'),
        ),
        migrations.AlterField(
            model_name='conversationvoicestatus',
            name='programmatic_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
