# Generated by Django 3.0.5 on 2020-10-14 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_auto_20201012_1746'),
        ('communication', '0005_auto_20201008_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='agenda_md',
            field=models.TextField(blank=True, null=True, verbose_name='Agenda in Markdown'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='chats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', related_query_name='conversations', to='communication.ConversationChat'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='emails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', related_query_name='conversations', to='communication.ConversationEmail'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='front_conversation_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Front conversation ID'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', related_query_name='conversations', to='communication.Issue'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='minutes_md',
            field=models.TextField(blank=True, null=True, verbose_name='Minutes in Markdown'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='videos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', related_query_name='conversations', to='communication.ConversationVideo'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='voices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', related_query_name='conversations', to='communication.ConversationVoice'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='demand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='leads.Demand'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='demand_commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='leads.DemandCommission'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description_md',
            field=models.TextField(blank=True, null=True, verbose_name='Description in Markdown'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='leads.Match'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='outcome_md',
            field=models.TextField(blank=True, null=True, verbose_name='Outcome in Markdown'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='scheduled',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='issue',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='leads.Supply'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='supply_commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='leads.SupplyCommission'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='supply_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', related_query_name='issues', to='leads.SupplyQuote'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='issues', related_query_name='issues', to='communication.IssueTag'),
        ),
    ]
