# Generated by Django 3.0.5 on 2020-10-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_auto_20201016_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationvoice',
            old_name='from_number',
            new_name='our_number',
        ),
        migrations.RenameField(
            model_name='conversationvoice',
            old_name='to_number',
            new_name='their_number',
        ),
    ]
