# Generated by Django 3.0.5 on 2020-10-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_auto_20201016_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationvideo',
            old_name='from_number',
            new_name='our_number',
        ),
        migrations.RenameField(
            model_name='conversationvideo',
            old_name='to_number',
            new_name='their_number',
        ),
    ]
