# Generated by Django 3.1.2 on 2020-11-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_auto_20201106_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='front_conversation_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Front conversation ID'),
        ),
    ]
