# Generated by Django 3.0.5 on 2020-10-14 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_auto_20201014_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='issue',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', related_query_name='conversations', to='communication.Issue'),
            preserve_default=False,
        ),
    ]
