# Generated by Django 3.0.5 on 2020-10-16 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
        ('communication', '0008_auto_20201016_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationvideo',
            name='our_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_video_our_numbers', related_query_name='conversation_video_our_numbers', to='relationships.PhoneNumber'),
        ),
        migrations.AlterField(
            model_name='conversationvideo',
            name='their_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_video_their_numbers', related_query_name='conversation_video_their_numbers', to='relationships.PhoneNumber'),
        ),
    ]
