# Generated by Django 3.0.5 on 2020-10-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0009_auto_20201014_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationchatstatus',
            options={'verbose_name': 'Conversation chat status', 'verbose_name_plural': 'Conversation chat statuses'},
        ),
        migrations.AlterModelOptions(
            name='conversationemailstatus',
            options={'verbose_name': 'Conversation email status', 'verbose_name_plural': 'Conversation email statuses'},
        ),
        migrations.AlterModelOptions(
            name='conversationvideostatus',
            options={'verbose_name': 'Conversation video status', 'verbose_name_plural': 'Conversation video statuses'},
        ),
        migrations.AlterModelOptions(
            name='conversationvoicestatus',
            options={'verbose_name': 'Conversation voice status', 'verbose_name_plural': 'Conversation voice statuses'},
        ),
        migrations.AlterModelOptions(
            name='issuestatus',
            options={'verbose_name': 'Issue status', 'verbose_name_plural': 'Issue statuses'},
        ),
    ]
