# Generated by Django 3.0.5 on 2020-10-14 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0024_auto_20201014_1731'),
        ('communication', '0010_auto_20201014_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationchat',
            name='from_number',
        ),
        migrations.RemoveField(
            model_name='conversationchat',
            name='to_number',
        ),
        migrations.AddField(
            model_name='conversationchat',
            name='our_number',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='conversation_chat_our_numbers', related_query_name='conversation_chat_our_numbers', to='relationships.PhoneNumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationchat',
            name='their_number',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='conversation_chat_their_numbers', related_query_name='conversation_chat_their_numbers', to='relationships.PhoneNumber'),
            preserve_default=False,
        ),
    ]
