# Generated by Django 3.1.2 on 2021-01-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0012_auto_20210107_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='front_conversation_id',
        ),
    ]
