# Generated by Django 3.1.2 on 2021-04-27 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0005_auto_20210427_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMessageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('body', models.TextField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseTruth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('text_output', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('integer_output', models.IntegerField(blank=True, db_index=True, null=True)),
                ('float_output', models.FloatField(blank=True, db_index=True, null=True)),
                ('message_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_truths', related_query_name='base_truths', to='processor.testmessagegroup')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_truths', related_query_name='base_truths', to='chat.method')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
