# Generated by Django 3.1.2 on 2021-04-28 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_auto_20210428_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetruth',
            name='method',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='base_truths', related_query_name='base_truths', to='processor.method'),
            preserve_default=False,
        ),
    ]
