# Generated by Django 3.1.2 on 2021-04-28 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0004_basetruth_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('ran', models.DateTimeField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestRunType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('programmatic_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('programmatic_details', models.TextField(blank=True, null=True, verbose_name='Programmatic details')),
                ('settings', models.CharField(choices=[('a', 'Run All Methods on All Message Groups'), ('b', 'Run Base Truth Methods Only')], db_index=True, max_length=2)),
                ('methods', models.ManyToManyField(blank=True, db_index=True, related_name='test_run_types', related_query_name='test_run_types', to='processor.Method')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestRunResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('expected_output', models.TextField(db_index=True)),
                ('actual_output', models.TextField(db_index=True)),
                ('matched', models.BooleanField(db_index=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_run_results', related_query_name='test_run_results', to='processor.method')),
                ('test_message_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_run_results', related_query_name='test_run_results', to='processor.testmessagegroup')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_run_results', related_query_name='test_run_results', to='processor.testrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='testrun',
            name='test_run_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_runs', related_query_name='test_runs', to='processor.testruntype'),
        ),
    ]
