# Generated by Django 3.1.2 on 2021-04-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0007_auto_20210428_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetruth',
            name='float_output',
        ),
        migrations.RemoveField(
            model_name='basetruth',
            name='integer_output',
        ),
        migrations.RemoveField(
            model_name='basetruth',
            name='text_output',
        ),
        migrations.AddField(
            model_name='basetruth',
            name='expected_output',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
