# Generated by Django 3.1.2 on 2021-04-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0008_auto_20210428_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundmessagegroup',
            name='initial_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='operationmethod',
            name='output_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testrunresult',
            name='actual_output',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testrunresult',
            name='expected_output',
            field=models.TextField(),
        ),
    ]
