# Generated by Django 3.1.2 on 2021-05-05 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0041_auto_20210505_1629'),
        ('payments', '0003_paymentevent_paymenteventtype_stripesession'),
        ('processor', '0013_auto_20210505_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagebodymetadataentity',
            name='entity_type',
            field=models.CharField(choices=[('newline', 'Newline'), ('domain_dot', 'Domain Dot'), ('tld', 'TLD'), ('url', 'URL'), ('decimal_point', 'Decimal Point'), ('number_separator', 'Number Separator'), ('number_uom', 'Number UOM'), ('number', 'Number'), ('fullstop', 'Fullstop'), ('exclamation_mark', 'Exclamation Mark'), ('email', 'Email'), ('currency', 'Currency'), ('price', 'Price'), ('excluded_price', 'Excluded Price'), ('location', 'Location'), ('incoterm_availability', 'Incoterm/Availability'), ('application', 'Application'), ('phone_number', 'Phone Number'), ('company', 'Company'), ('product_type', 'Product Type'), ('product', 'Product'), ('product_specification_type', 'Product Specification Type'), ('uom', 'UOM'), ('moq', 'MOQ'), ('quantity', 'Quantity'), ('packing', 'Packing')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='MatchingKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('keyword', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('edit_distance_tolerance', models.IntegerField(db_index=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matching_keywords', related_query_name='matching_keywords', to='relationships.application')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matching_keywords', related_query_name='matching_keywords', to='relationships.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matching_keywords', related_query_name='matching_keywords', to='payments.currency')),
                ('excluded_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matching_keywords', related_query_name='matching_keywords', to='relationships.excludedprice')),
                ('incoterm_availability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matching_keywords', related_query_name='matching_keywords', to='relationships.incotermavailability')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matching_keywords', related_query_name='matching_keywords', to='relationships.location')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matching_keywords', related_query_name='matching_keywords', to='relationships.product')),
                ('product_specification_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matching_keywords', related_query_name='matching_keywords', to='relationships.productspecificationtype')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matching_keywords', related_query_name='matching_keywords', to='relationships.producttype')),
                ('unit_of_measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matching_keywords', related_query_name='matching_keywords', to='relationships.unitofmeasure')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
