# Generated by Django 3.1.2 on 2020-11-03 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20201103_1520'),
        ('communication', '0006_auto_20201025_1608'),
        ('relationships', '0007_auto_20201103_1520'),
        ('files', '0004_auto_20201102_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDemandType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField(blank=True, null=True, verbose_name='Details in Markdown')),
                ('programmatic_key', models.CharField(blank=True, max_length=100, null=True)),
                ('programmatic_details_md', models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown')),
            ],
            options={
                'verbose_name': 'File-demand type',
                'verbose_name_plural': 'File-demand types',
            },
        ),
        migrations.CreateModel(
            name='FileIssueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField(blank=True, null=True, verbose_name='Details in Markdown')),
                ('programmatic_key', models.CharField(blank=True, max_length=100, null=True)),
                ('programmatic_details_md', models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown')),
            ],
            options={
                'verbose_name': 'File-issue type',
                'verbose_name_plural': 'File-issue types',
            },
        ),
        migrations.CreateModel(
            name='FilePersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField(blank=True, null=True, verbose_name='Details in Markdown')),
                ('programmatic_key', models.CharField(blank=True, max_length=100, null=True)),
                ('programmatic_details_md', models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown')),
            ],
            options={
                'verbose_name': 'File-person type',
                'verbose_name_plural': 'File-person types',
            },
        ),
        migrations.CreateModel(
            name='FileSupplyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField(blank=True, null=True, verbose_name='Details in Markdown')),
                ('programmatic_key', models.CharField(blank=True, max_length=100, null=True)),
                ('programmatic_details_md', models.TextField(blank=True, null=True, verbose_name='Programmatic details in Markdown')),
            ],
            options={
                'verbose_name': 'File-supply type',
                'verbose_name_plural': 'File-supply types',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='s3_bucket_name',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='s3_object_content_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='s3_object_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='s3_object_e_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='s3_object_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='s3_object_last_modified',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='upload_confirmed',
            field=models.DateTimeField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='files', related_query_name='files', to='files.FileTag'),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('s3_bucket_name', 's3_object_key')},
        ),
        migrations.CreateModel(
            name='FileSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('details_md', models.TextField(verbose_name='Details in Markdown')),
                ('afile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_supply_relationships', related_query_name='file_supply_relationships', to='files.file')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_supply_relationships', related_query_name='file_supply_relationships', to='files.filesupplytype', verbose_name='File-supply relationship type')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_supply_relationships', related_query_name='file_supply_relationships', to='leads.supply')),
            ],
            options={
                'verbose_name': 'File-supply relationship',
                'verbose_name_plural': 'File-supply relationships',
            },
        ),
        migrations.CreateModel(
            name='FilePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('details_md', models.TextField(verbose_name='Details in Markdown')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_person_relationships', related_query_name='file_person_relationships', to='files.file')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_person_relationships', related_query_name='file_person_relationships', to='relationships.person')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_person_relationships', related_query_name='file_person_relationships', to='files.filepersontype', verbose_name='File-person relationship type')),
            ],
            options={
                'verbose_name': 'File-person relationship',
                'verbose_name_plural': 'File-person relationships',
            },
        ),
        migrations.CreateModel(
            name='FileIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('details_md', models.TextField(verbose_name='Details in Markdown')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_issue_relationships', related_query_name='file_issue_relationships', to='files.file')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_issue_relationships', related_query_name='file_issue_relationships', to='communication.issue')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_issue_relationships', related_query_name='file_issue_relationships', to='files.fileissuetype', verbose_name='File-issue relationship type')),
            ],
            options={
                'verbose_name': 'File-issue relationship',
                'verbose_name_plural': 'File-issue relationships',
            },
        ),
        migrations.CreateModel(
            name='FileDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('details_md', models.TextField(verbose_name='Details in Markdown')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_demand_relationships', related_query_name='file_demand_relationships', to='leads.demand')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_demand_relationships', related_query_name='file_demand_relationships', to='files.file')),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_demand_relationships', related_query_name='file_demand_relationships', to='files.filedemandtype', verbose_name='File-demand relationship type')),
            ],
            options={
                'verbose_name': 'File-demand relationship',
                'verbose_name_plural': 'File-demand relationships',
            },
        ),
        migrations.RemoveField(
            model_name='file',
            name='anonymization_source',
        ),
        migrations.RemoveField(
            model_name='file',
            name='s3_url',
        ),
        migrations.RemoveField(
            model_name='file',
            name='source_issue',
        ),
        migrations.RemoveField(
            model_name='file',
            name='source_person',
        ),
        migrations.RemoveField(
            model_name='file',
            name='tags',
        ),
    ]
