# Generated by Django 3.1.2 on 2020-11-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_auto_20201025_1608'),
        ('leads', '0004_auto_20201103_1520'),
        ('files', '0006_auto_20201103_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='demand_leads',
            field=models.ManyToManyField(db_index=True, related_name='files', related_query_name='files', through='files.FileDemand', to='leads.Demand'),
        ),
        migrations.AddField(
            model_name='file',
            name='issues',
            field=models.ManyToManyField(db_index=True, related_name='files', related_query_name='files', through='files.FileIssue', to='communication.Issue'),
        ),
        migrations.AddField(
            model_name='file',
            name='supply_leads',
            field=models.ManyToManyField(db_index=True, related_name='files', related_query_name='files', through='files.FileSupply', to='leads.Supply'),
        ),
    ]
