# Generated by Django 3.1.2 on 2020-11-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20201103_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='demand_leads',
            new_name='demands',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='supply_leads',
            new_name='supplies',
        ),
    ]
