# Generated by Django 3.1.2 on 2020-11-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0007_auto_20201103_1520'),
        ('files', '0008_auto_20201103_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='persons',
            field=models.ManyToManyField(db_index=True, related_name='files', related_query_name='files', through='files.FilePerson', to='relationships.Person'),
        ),
    ]
