# Generated by Django 3.1.2 on 2020-11-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_remove_file_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_confirmed',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
