# Generated by Django 3.1.2 on 2020-12-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_auto_20201106_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedemandtype',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='fileissuetype',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='filepersontype',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='filesupplytype',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='filetag',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
    ]
