# Purposes of sending emails

LOGIN = 'LOGIN'
REGISTER = 'REGISTER'
UPDATE_EMAIL = 'UPDATE_EMAIL'

EMAIL_PURPOSE_CHOICES = [
    (LOGIN, LOGIN),
    (REGISTER, REGISTER),
    (UPDATE_EMAIL, UPDATE_EMAIL)
]