# Generated by Django 3.1.2 on 2021-03-28 05:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('upload_confirmed', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('s3_bucket_name', models.CharField(blank=True, db_index=True, max_length=63, null=True)),
                ('s3_object_key', models.CharField(blank=True, db_index=True, max_length=1024, null=True)),
                ('s3_object_content_length', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('s3_object_e_tag', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('s3_object_content_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('s3_object_last_modified', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
            ],
            options={
                'unique_together': {('s3_bucket_name', 's3_object_key')},
            },
        ),
    ]
