# Generated by Django 3.0.5 on 2020-09-22 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_md', models.TextField()),
                ('programmatic_key', models.CharField(max_length=100)),
                ('programmatic_details_md', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='files.FileTag')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('s3_url', models.CharField(max_length=100)),
                ('details_md', models.TextField()),
                ('anonymization_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anonymization_copies', to='files.File')),
                ('source_issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='communication.Issue')),
                ('source_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='communication.Person')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='files.FileTag')),
            ],
        ),
    ]
