# Generated by Django 3.1.2 on 2021-11-26 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file_type', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('filename', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('presigned_url_issued', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('presigned_url_lifespan', models.IntegerField(blank=True, db_index=True, null=True)),
                ('presigned_url_response', models.JSONField(blank=True, null=True)),
                ('s3_bucket_name', models.CharField(blank=True, db_index=True, max_length=63, null=True)),
                ('s3_object_key', models.CharField(blank=True, db_index=True, max_length=1024, null=True)),
                ('s3_object_content_length', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('s3_object_e_tag', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('s3_object_content_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('s3_object_last_modified', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('access_count', models.IntegerField(db_index=True)),
            ],
        ),
    ]
