# Generated by Django 3.0.5 on 2020-10-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('relationships', '0001_initial'),
        ('communication', '0002_conversation_conversationchannel_conversationchat_conversationchatstatus_conversationemail_conversat'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetag',
            name='details_md',
        ),
        migrations.RemoveField(
            model_name='filetag',
            name='id',
        ),
        migrations.RemoveField(
            model_name='filetag',
            name='name',
        ),
        migrations.RemoveField(
            model_name='filetag',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='filetag',
            name='programmatic_details_md',
        ),
        migrations.RemoveField(
            model_name='filetag',
            name='programmatic_key',
        ),
        migrations.AddField(
            model_name='filetag',
            name='parentchildrenchoice_ptr',
            field=models.OneToOneField(auto_created=True, default=-1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.ParentChildrenChoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='anonymization_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anonymization_copies', related_query_name='anonymization_copies', to='files.File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='source_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', related_query_name='files', to='communication.Issue'),
        ),
        migrations.AlterField(
            model_name='file',
            name='source_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', related_query_name='files', to='relationships.Person'),
        ),
        migrations.AlterField(
            model_name='file',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', related_query_name='files', to='files.FileTag'),
        ),
    ]
