# Generated by Django 3.1.2 on 2022-02-14 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20211126_1456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileAccess',
        ),
    ]
