# Generated by Django 3.1.2 on 2021-09-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_current_lead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='current_lead',
            new_name='lead',
        ),
    ]
