# Generated by Django 3.0.5 on 2020-10-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20201007_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
