# Generated by Django 3.0.5 on 2020-10-14 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_auto_20201008_1740'),
        ('relationships', '0019_auto_20201013_1615'),
        ('files', '0003_auto_20201008_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='anonymization_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anonymization_copies', related_query_name='anonymization_copies', to='files.File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='details_md',
            field=models.TextField(blank=True, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='file',
            name='s3_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='source_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', related_query_name='files', to='communication.Issue'),
        ),
        migrations.AlterField(
            model_name='file',
            name='source_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', related_query_name='files', to='relationships.Person'),
        ),
        migrations.AlterField(
            model_name='file',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', related_query_name='files', to='files.FileTag'),
        ),
    ]
