# Generated by Django 3.1.2 on 2022-02-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_delete_fileaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='thumbnail_s3_bucket_name',
            field=models.CharField(blank=True, db_index=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='thumbnail_s3_object_key',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
    ]
