# Generated by Django 3.1.2 on 2022-02-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20220214_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_type',
            new_name='mime_type',
        ),
    ]
