# Generated by Django 3.0.5 on 2020-10-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20201014_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
