# Generated by Django 3.1.2 on 2021-11-09 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0160_auto_20211103_2126'),
        ('files', '0004_remove_file_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='upload_confirmed',
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='presigned_url_issued',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='presigned_url_lifespan',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='presigned_url_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', related_query_name='uploaded_files', to='relationships.user'),
        ),
    ]
