# Generated by Django 3.1.2 on 2020-11-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20201103_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesupply',
            old_name='afile',
            new_name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='files', related_query_name='files', to='files.FileTag'),
        ),
    ]
