# Generated by Django 3.1.2 on 2021-11-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20211109_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='lifespan',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
