# Generated by Django 3.1.2 on 2022-02-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20220219_0441'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('s3_bucket_name', 's3_object_key')},
        ),
    ]
