# Generated by Django 3.1.2 on 2021-11-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_file_lifespan'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
