# Generated by Django 3.1.2 on 2022-03-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20220220_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='height',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='thumbnail_height',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='thumbnail_width',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='width',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
