# Generated by Django 3.1.2 on 2021-11-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_file_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='lifespan',
            new_name='unlinked_lead_lifespan',
        ),
    ]
