# Generated by Django 3.1.2 on 2022-10-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20220301_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='lead',
        ),
    ]
