# Generated by Django 3.1.2 on 2021-11-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_auto_20211111_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='unlinked_lead_lifespan',
        ),
    ]
