# Generated by Django 3.1.2 on 2020-11-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_file_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='uuid',
        ),
    ]
