# Generated by Django 3.1.2 on 2020-11-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_auto_20201106_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='s3_bucket_name',
            field=models.CharField(blank=True, db_index=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='s3_object_content_length',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='s3_object_content_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='s3_object_e_tag',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='s3_object_key',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
    ]
