# Generated by Django 3.1.2 on 2020-12-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_auto_20201210_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedemand',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='fileissue',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='fileperson',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
        migrations.AlterField(
            model_name='filesupply',
            name='details_md',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details in Markdown'),
        ),
    ]
