"""Data Keys

Data keys are prefixed with the context - intent, message - in which they
are captured, and postfixed by its type. I.e.,

<Intent Key>__<Message Key>__<Data Name>__<Data Type>

E.g.,

NEW_SUPPLY__SUPPLY__GET_PRODUCT__PRODUCT_TYPE__STRING
"""

UNKNOWN = 'UNKNOWN' # Unknown data

# New Supply, Get Product
NEW_SUPPLY__SUPPLY__GET_PRODUCT__PRODUCT_TYPE__STRING = 'NEW_SUPPLY__SUPPLY__GET_PRODUCT__PRODUCT_TYPE__STRING' # Product type string

# New Supply, Get Availability
NEW_SUPPLY__SUPPLY__GET_AVAILABILITY__AVAILABILITY__CHOICE = 'NEW_SUPPLY__SUPPLY__GET_AVAILABILITY__AVAILABILITY__CHOICE' # Availability choice
## Options for choice
NEW_SUPPLY__SUPPLY__GET_AVAILABILITY__AVAILABILITY__READY_OTG = 'NEW_SUPPLY__SUPPLY__GET_AVAILABILITY__AVAILABILITY__READY_OTG' # Choose ready/OTG
NEW_SUPPLY__SUPPLY__GET_AVAILABILITY__AVAILABILITY__PRE_ORDER = 'NEW_SUPPLY__SUPPLY__GET_AVAILABILITY__AVAILABILITY__PRE_ORDER' # Choose pre-order




NEW_SUPPLY__SUPPLY__GET_COUNTRY_STATE__COUNTRY_STATE__STRING = 'NEW_SUPPLY__SUPPLY__GET_COUNTRY_STATE__COUNTRY_STATE__STRING'

# Choices for model fields
# Note: remember to makemigrations when updating this list
choices = [
    (UNKNOWN, UNKNOWN),
    (NEW_SUPPLY__SUPPLY__GET_PRODUCT__PRODUCT_TYPE__STRING, NEW_SUPPLY__SUPPLY__GET_PRODUCT__PRODUCT_TYPE__STRING),
    (NEW_SUPPLY__SUPPLY__GET_COUNTRY_STATE__COUNTRY_STATE__STRING, NEW_SUPPLY__SUPPLY__GET_COUNTRY_STATE__COUNTRY_STATE__STRING)
]