"""Mapping of context to handler"""

from chat import handlers
from chat.libraries import intents, messages

handler_context_map = {
    intents.SPEAK_HUMAN: {
        messages.CONFIRM_HUMAN: handlers.SPEAK_HUMAN__CONFIRM_HUMAN
    },
    intents.EXPLAIN_SERVICE: {
        messages.EXPLAIN_SERVICE: handlers.EXPLAIN_SERVICE__EXPLAIN_SERVICE
    },
    intents.REGISTER: {
        messages.REGISTER__GET_NAME: handlers.REGISTER__REGISTER__GET_NAME # DONE
    },
    intents.MENU: {
        messages.MENU: handlers.MENU__MENU
    },
    intents.DISCUSS_W_BUYER: {
        messages.SUPPLY__GET_PRODUCT: handlers.DISCUSS_W_BUYER__SUPPLY__GET_PRODUCT,
        messages.SUPPLY__GET_AVAILABILITY: handlers.DISCUSS_W_BUYER__SUPPLY__GET_AVAILABILITY,
        messages.SUPPLY__GET_COUNTRY_STATE_READY_OTG: handlers.DISCUSS_W_BUYER__SUPPLY__GET_COUNTRY_STATE_READY_OTG,
        messages.SUPPLY__GET_COUNTRY_STATE_PRE_ORDER: handlers.DISCUSS_W_BUYER__SUPPLY__GET_COUNTRY_STATE_PRE_ORDER,
        messages.SUPPLY__CONFIRM_PACKING: handlers.DISCUSS_W_BUYER__SUPPLY__CONFIRM_PACKING,
        messages.SUPPLY__GET_PACKING: handlers.DISCUSS_W_BUYER__SUPPLY__GET_PACKING,
        messages.SUPPLY__GET_QUANTITY_READY_OTG_KNOWN_PACKING: handlers.DISCUSS_W_BUYER__SUPPLY__GET_QUANTITY_READY_OTG_KNOWN_PACKING,
        messages.SUPPLY__GET_QUANTITY_READY_OTG_UNKNOWN_PACKING: handlers.DISCUSS_W_BUYER__SUPPLY__GET_QUANTITY_READY_OTG_UNKNOWN_PACKING,
        messages.SUPPLY__GET_QUANTITY_PRE_ORDER: handlers.DISCUSS_W_BUYER__SUPPLY__GET_QUANTITY_PRE_ORDER,
        messages.SUPPLY__GET_PRICE_READY_OTG_KNOWN_PACKING: handlers.DISCUSS_W_BUYER__SUPPLY__GET_PRICE_READY_OTG_KNOWN_PACKING,
        messages.SUPPLY__GET_PRICE_READY_OTG_UNKNOWN_PACKING: handlers.DISCUSS_W_BUYER__SUPPLY__GET_PRICE_READY_OTG_UNKNOWN_PACKING,
        messages.SUPPLY__GET_PRICE_PRE_ORDER: handlers.DISCUSS_W_BUYER__SUPPLY__GET_PRICE_PRE_ORDER,
        messages.SUPPLY__GET_DEPOSIT: handlers.DISCUSS_W_BUYER__SUPPLY__GET_DEPOSIT,
        messages.SUPPLY__GET_ACCEPT_LC: handlers.DISCUSS_W_BUYER__SUPPLY__GET_ACCEPT_LC,
        messages.STILL_INTERESTED__CONFIRM: handlers.DISCUSS_W_BUYER__STILL_INTERESTED__CONFIRM,
        messages.STILL_INTERESTED__THANK_YOU: handlers.DISCUSS_W_BUYER__STILL_INTERESTED__THANK_YOU,
        messages.DISCUSS__ASK: handlers.DISCUSS_W_BUYER__DISCUSS__ASK,
        messages.DISCUSS__THANK_YOU: handlers.DISCUSS_W_BUYER__DISCUSS__THANK_YOU,
        messages.DISCUSS__ALREADY_CONNECTED: handlers.DISCUSS_W_BUYER__DISCUSS__ALREADY_CONNECTED,
        messages.DISCUSS__CONFIRM_INTEREST: handlers.DISCUSS_W_BUYER__DISCUSS__CONFIRM_INTEREST,
        messages.DISCUSS__CONFIRM_DETAILS: handlers.DISCUSS_W_BUYER__DISCUSS__CONFIRM_DETAILS
    },
    intents.NEW_SUPPLY: {
        messages.SUPPLY__GET_PRODUCT: handlers.NEW_SUPPLY__SUPPLY__GET_PRODUCT, # Done
        messages.SUPPLY__GET_AVAILABILITY: handlers.NEW_SUPPLY__SUPPLY__GET_AVAILABILITY, # Done
        messages.SUPPLY__GET_COUNTRY_STATE_READY_OTG: handlers.NEW_SUPPLY__SUPPLY__GET_COUNTRY_STATE_READY_OTG,
        messages.SUPPLY__GET_COUNTRY_STATE_PRE_ORDER: handlers.NEW_SUPPLY__SUPPLY__GET_COUNTRY_STATE_PRE_ORDER,
        messages.SUPPLY__CONFIRM_PACKING: handlers.NEW_SUPPLY__SUPPLY__CONFIRM_PACKING,
        messages.SUPPLY__GET_PACKING: handlers.NEW_SUPPLY__SUPPLY__GET_PACKING,
        messages.SUPPLY__GET_QUANTITY_READY_OTG_KNOWN_PACKING: handlers.NEW_SUPPLY__SUPPLY__GET_QUANTITY_READY_OTG_KNOWN_PACKING,
        messages.SUPPLY__GET_QUANTITY_READY_OTG_UNKNOWN_PACKING: handlers.NEW_SUPPLY__SUPPLY__GET_QUANTITY_READY_OTG_UNKNOWN_PACKING,
        messages.SUPPLY__GET_QUANTITY_PRE_ORDER: handlers.NEW_SUPPLY__SUPPLY__GET_QUANTITY_PRE_ORDER,
        messages.SUPPLY__GET_PRICE_READY_OTG_KNOWN_PACKING: handlers.NEW_SUPPLY__SUPPLY__GET_PRICE_READY_OTG_KNOWN_PACKING,
        messages.SUPPLY__GET_PRICE_READY_OTG_UNKNOWN_PACKING: handlers.NEW_SUPPLY__SUPPLY__GET_PRICE_READY_OTG_UNKNOWN_PACKING,
        messages.SUPPLY__GET_PRICE_PRE_ORDER: handlers.NEW_SUPPLY__SUPPLY__GET_PRICE_PRE_ORDER,
        messages.SUPPLY__GET_DEPOSIT: handlers.NEW_SUPPLY__SUPPLY__GET_DEPOSIT,
        messages.SUPPLY__GET_ACCEPT_LC: handlers.NEW_SUPPLY__SUPPLY__GET_ACCEPT_LC,
        messages.SUPPLY__THANK_YOU: handlers.NEW_SUPPLY__SUPPLY__THANK_YOU
    },
    intents.NEW_DEMAND: {
        messages.DEMAND__GET_PRODUCT: handlers.NEW_DEMAND__DEMAND__GET_PRODUCT,
        messages.DEMAND__GET_COUNTRY_STATE: handlers.NEW_DEMAND__DEMAND__GET_COUNTRY_STATE,
        messages.DEMAND__GET_QUANTITY_KNOWN_PRODUCT_TYPE: handlers.NEW_DEMAND__DEMAND__GET_QUANTITY_KNOWN_PRODUCT_TYPE,
        messages.DEMAND__GET_QUANTITY_UNKNOWN_PRODUCT_TYPE: handlers.NEW_DEMAND__DEMAND__GET_QUANTITY_UNKNOWN_PRODUCT_TYPE,
        messages.DEMAND__GET_PRICE_KNOWN_PRODUCT_TYPE: handlers.NEW_DEMAND__DEMAND__GET_PRICE_KNOWN_PRODUCT_TYPE,
        messages.DEMAND__GET_PRICE_UNKNOWN_PRODUCT_TYPE: handlers.NEW_DEMAND__DEMAND__GET_PRICE_UNKNOWN_PRODUCT_TYPE,
        messages.DEMAND__THANK_YOU: handlers.NEW_DEMAND__DEMAND__THANK_YOU
    },
    intents.DISCUSS_W_SELLER: {
        messages.DEMAND__GET_PRODUCT: handlers.DISCUSS_W_SELLER__DEMAND__GET_PRODUCT,
        messages.DEMAND__GET_COUNTRY_STATE: handlers.DISCUSS_W_SELLER__DEMAND__GET_COUNTRY_STATE,
        messages.DEMAND__GET_QUANTITY_KNOWN_PRODUCT_TYPE: handlers.DISCUSS_W_SELLER__DEMAND__GET_QUANTITY_KNOWN_PRODUCT_TYPE,
        messages.DEMAND__GET_QUANTITY_UNKNOWN_PRODUCT_TYPE: handlers.DISCUSS_W_SELLER__DEMAND__GET_QUANTITY_UNKNOWN_PRODUCT_TYPE,
        messages.DEMAND__GET_PRICE_KNOWN_PRODUCT_TYPE: handlers.DISCUSS_W_SELLER__DEMAND__GET_PRICE_KNOWN_PRODUCT_TYPE,
        messages.DEMAND__GET_PRICE_UNKNOWN_PRODUCT_TYPE: handlers.DISCUSS_W_SELLER__DEMAND__GET_PRICE_UNKNOWN_PRODUCT_TYPE,
        messages.DISCUSS__CONFIRM_INTEREST: handlers.DISCUSS_W_SELLER__DISCUSS__CONFIRM_INTEREST,
        messages.STILL_INTERESTED__CONFIRM: handlers.DISCUSS_W_SELLER__STILL_INTERESTED__CONFIRM,
        messages.STILL_INTERESTED__THANK_YOU: handlers.DISCUSS_W_SELLER__STILL_INTERESTED__THANK_YOU,
        messages.DISCUSS__CONFIRM_DETAILS: handlers.DISCUSS_W_SELLER__DISCUSS__CONFIRM_DETAILS,
        messages.DISCUSS__ALREADY_CONNECTED: handlers.DISCUSS_W_SELLER__DISCUSS__ALREADY_CONNECTED,
        messages.DISCUSS__ASK: handlers.DISCUSS_W_SELLER__DISCUSS__ASK,
        messages.DISCUSS__THANK_YOU: handlers.DISCUSS_W_SELLER__DISCUSS__THANK_YOU
    },
    intents.QNA: {
        messages.YOUR_QUESTION: handlers.QNA__YOUR_QUESTION,
        messages.YOUR_ANSWER: handlers.QNA__YOUR_ANSWER,
        messages.ASK_QUESTION: handlers.QNA__ASK_QUESTION,
        messages.THANK_FOR_QUESTION: handlers.QNA__THANK_FOR_QUESTION,
        messages.REPLY: handlers.QNA__REPLY,
        messages.THANK_FOR_REPLY: handlers.QNA__THANK_FOR_REPLY,
        messages.STOP_DISCUSSION_REASON: handlers.QNA__STOP_DISCUSSION_REASON,
        messages.STOP_DISCUSSION_THANK_YOU: handlers.QNA__STOP_DISCUSSION__STOP_DISCUSSION__THANK_YOU
    },
    intents.CONNECT: {
        messages.PLEASE_PAY: handlers.CONNECT__PLEASE_PAY,
        messages.CONNECTED: handlers.CONNECT__CONNECTED
    },
    intents.NO_INTENT: {
        messages.NO_MESSAGE: handlers.NO_INTENT__NO_MESSAGE # DONE
    },
}

def get_handler(message, intent_key, message_key):
    """Get handler for message and context (i.e., intent_key, message_key).

    Parameters
    ----------
    message : TwilioInboundMessage
        Message for which we're getting a MessageHandler for
    intent_key : str
        Intent key
    message_key : str
        Message key

    Returns
    -------
    MessageHandler for message
    """
    return handler_context_map[intent_key]\
        [message_key](message, intent_key, message_key)