"""Intent keys"""

NO_INTENT = 'NO_INTENT' # Where user has no intent

SPEAK_HUMAN = 'SPEAK_HUMAN'
EXPLAIN_SERVICE = 'EXPLAIN_SERVICE'
REGISTER = 'REGISTER'
NEW_SUPPLY = 'NEW_SUPPLY'
NEW_DEMAND = 'NEW_DEMAND'
DISCUSS_W_BUYER = 'DISCUSS_W_BUYER'
DISCUSS_W_SELLER = 'DISCUSS_W_SELLER'
STOP_DISCUSSION = 'STOP_DISCUSSION'
CONNECT = 'CONNECT'

# Choices for model fields
choices = [
    (NO_INTENT, NO_INTENT),
    (SPEAK_HUMAN, SPEAK_HUMAN),
    (EXPLAIN_SERVICE, EXPLAIN_SERVICE),
    (REGISTER, REGISTER),
    (NEW_SUPPLY, NEW_SUPPLY),
    (NEW_DEMAND, NEW_DEMAND),
    (DISCUSS_W_BUYER, DISCUSS_W_BUYER),
    (DISCUSS_W_SELLER, DISCUSS_W_SELLER),
    (STOP_DISCUSSION, STOP_DISCUSSION),
    (CONNECT, CONNECT)
]