# Generated by Django 3.0.2 on 2020-03-15 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200315_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productslist',
            name='agent',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
