# Generated by Django 3.0.2 on 2020-03-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200315_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
