# Generated by Django 3.0.2 on 2020-03-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200315_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productslistaccesslogentry',
            options={'verbose_name_plural': 'Product list access log entries'},
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
