# Generated by Django 3.0.2 on 2020-03-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200315_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInterestsLists',
        ),
    ]
