# Generated by Django 3.0.2 on 2020-03-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200315_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslistaccesslogentry',
            name='referrer',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='productslistaccesslogentry',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
