# Generated by Django 3.0.2 on 2020-03-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200315_2238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductInterestsList',
            new_name='ProductsInterestsList',
        ),
        migrations.AlterModelOptions(
            name='productslistaccesslogentry',
            options={'ordering': ['-accessed'], 'verbose_name_plural': 'Products list access log entries'},
        ),
    ]
