# Generated by Django 3.0.2 on 2020-03-15 08:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_productinterestslists'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInterestsList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='products.Lead')),
                ('products', models.ManyToManyField(related_name='interests_lists', to='products.Product')),
                ('products_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests_lists', to='products.ProductsList')),
            ],
        ),
    ]
