# Generated by Django 3.0.2 on 2020-03-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productinterestslist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productslistaccesslogentry',
            old_name='product_list',
            new_name='products_list',
        ),
        migrations.AlterField(
            model_name='productslist',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
